#include "decoder/riscv/mem_xlat.h"

namespace Dyninst {
namespace InstructionAPI {
namespace riscv {

// clang-format off
  bool is_mem_load(entryID eid) {
    switch(eid) {
      case riscv64_op_amoadd_d:
      case riscv64_op_amoadd_d_aq:
      case riscv64_op_amoadd_d_aq_rl:
      case riscv64_op_amoadd_d_rl:
      case riscv64_op_amoadd_w:
      case riscv64_op_amoadd_w_aq:
      case riscv64_op_amoadd_w_aq_rl:
      case riscv64_op_amoadd_w_rl:
      case riscv64_op_amoand_d:
      case riscv64_op_amoand_d_aq:
      case riscv64_op_amoand_d_aq_rl:
      case riscv64_op_amoand_d_rl:
      case riscv64_op_amoand_w:
      case riscv64_op_amoand_w_aq:
      case riscv64_op_amoand_w_aq_rl:
      case riscv64_op_amoand_w_rl:
      case riscv64_op_amomax_d:
      case riscv64_op_amomax_d_aq:
      case riscv64_op_amomax_d_aq_rl:
      case riscv64_op_amomax_d_rl:
      case riscv64_op_amomaxu_d:
      case riscv64_op_amomaxu_d_aq:
      case riscv64_op_amomaxu_d_aq_rl:
      case riscv64_op_amomaxu_d_rl:
      case riscv64_op_amomaxu_w:
      case riscv64_op_amomaxu_w_aq:
      case riscv64_op_amomaxu_w_aq_rl:
      case riscv64_op_amomaxu_w_rl:
      case riscv64_op_amomax_w:
      case riscv64_op_amomax_w_aq:
      case riscv64_op_amomax_w_aq_rl:
      case riscv64_op_amomax_w_rl:
      case riscv64_op_amomin_d:
      case riscv64_op_amomin_d_aq:
      case riscv64_op_amomin_d_aq_rl:
      case riscv64_op_amomin_d_rl:
      case riscv64_op_amominu_d:
      case riscv64_op_amominu_d_aq:
      case riscv64_op_amominu_d_aq_rl:
      case riscv64_op_amominu_d_rl:
      case riscv64_op_amominu_w:
      case riscv64_op_amominu_w_aq:
      case riscv64_op_amominu_w_aq_rl:
      case riscv64_op_amominu_w_rl:
      case riscv64_op_amomin_w:
      case riscv64_op_amomin_w_aq:
      case riscv64_op_amomin_w_aq_rl:
      case riscv64_op_amomin_w_rl:
      case riscv64_op_amoor_d:
      case riscv64_op_amoor_d_aq:
      case riscv64_op_amoor_d_aq_rl:
      case riscv64_op_amoor_d_rl:
      case riscv64_op_amoor_w:
      case riscv64_op_amoor_w_aq:
      case riscv64_op_amoor_w_aq_rl:
      case riscv64_op_amoor_w_rl:
      case riscv64_op_amoswap_d:
      case riscv64_op_amoswap_d_aq:
      case riscv64_op_amoswap_d_aq_rl:
      case riscv64_op_amoswap_d_rl:
      case riscv64_op_amoswap_w:
      case riscv64_op_amoswap_w_aq:
      case riscv64_op_amoswap_w_aq_rl:
      case riscv64_op_amoswap_w_rl:
      case riscv64_op_amoxor_d:
      case riscv64_op_amoxor_d_aq:
      case riscv64_op_amoxor_d_aq_rl:
      case riscv64_op_amoxor_d_rl:
      case riscv64_op_amoxor_w:
      case riscv64_op_amoxor_w_aq:
      case riscv64_op_amoxor_w_aq_rl:
      case riscv64_op_amoxor_w_rl:
      case riscv64_op_c_fld:
      case riscv64_op_c_fldsp:
      case riscv64_op_c_flw:
      case riscv64_op_c_flwsp:
      case riscv64_op_c_ld:
      case riscv64_op_c_ldsp:
      case riscv64_op_c_lw:
      case riscv64_op_c_lwsp:
      case riscv64_op_fld:
      case riscv64_op_flw:
      case riscv64_op_lb:
      case riscv64_op_lbu:
      case riscv64_op_ld:
      case riscv64_op_lh:
      case riscv64_op_lhu:
      case riscv64_op_lr_d:
      case riscv64_op_lr_w:
      case riscv64_op_lw:
      case riscv64_op_lwu:
        return true;
      default:
        return false;
    }
  }
  // clang-format off
  bool is_mem_store(entryID eid) {
    switch(eid) {
      case riscv64_op_amoadd_d:
      case riscv64_op_amoadd_d_aq:
      case riscv64_op_amoadd_d_aq_rl:
      case riscv64_op_amoadd_d_rl:
      case riscv64_op_amoadd_w:
      case riscv64_op_amoadd_w_aq:
      case riscv64_op_amoadd_w_aq_rl:
      case riscv64_op_amoadd_w_rl:
      case riscv64_op_amoand_d:
      case riscv64_op_amoand_d_aq:
      case riscv64_op_amoand_d_aq_rl:
      case riscv64_op_amoand_d_rl:
      case riscv64_op_amoand_w:
      case riscv64_op_amoand_w_aq:
      case riscv64_op_amoand_w_aq_rl:
      case riscv64_op_amoand_w_rl:
      case riscv64_op_amomax_d:
      case riscv64_op_amomax_d_aq:
      case riscv64_op_amomax_d_aq_rl:
      case riscv64_op_amomax_d_rl:
      case riscv64_op_amomaxu_d:
      case riscv64_op_amomaxu_d_aq:
      case riscv64_op_amomaxu_d_aq_rl:
      case riscv64_op_amomaxu_d_rl:
      case riscv64_op_amomaxu_w:
      case riscv64_op_amomaxu_w_aq:
      case riscv64_op_amomaxu_w_aq_rl:
      case riscv64_op_amomaxu_w_rl:
      case riscv64_op_amomax_w:
      case riscv64_op_amomax_w_aq:
      case riscv64_op_amomax_w_aq_rl:
      case riscv64_op_amomax_w_rl:
      case riscv64_op_amomin_d:
      case riscv64_op_amomin_d_aq:
      case riscv64_op_amomin_d_aq_rl:
      case riscv64_op_amomin_d_rl:
      case riscv64_op_amominu_d:
      case riscv64_op_amominu_d_aq:
      case riscv64_op_amominu_d_aq_rl:
      case riscv64_op_amominu_d_rl:
      case riscv64_op_amominu_w:
      case riscv64_op_amominu_w_aq:
      case riscv64_op_amominu_w_aq_rl:
      case riscv64_op_amominu_w_rl:
      case riscv64_op_amomin_w:
      case riscv64_op_amomin_w_aq:
      case riscv64_op_amomin_w_aq_rl:
      case riscv64_op_amomin_w_rl:
      case riscv64_op_amoor_d:
      case riscv64_op_amoor_d_aq:
      case riscv64_op_amoor_d_aq_rl:
      case riscv64_op_amoor_d_rl:
      case riscv64_op_amoor_w:
      case riscv64_op_amoor_w_aq:
      case riscv64_op_amoor_w_aq_rl:
      case riscv64_op_amoor_w_rl:
      case riscv64_op_amoswap_d:
      case riscv64_op_amoswap_d_aq:
      case riscv64_op_amoswap_d_aq_rl:
      case riscv64_op_amoswap_d_rl:
      case riscv64_op_amoswap_w:
      case riscv64_op_amoswap_w_aq:
      case riscv64_op_amoswap_w_aq_rl:
      case riscv64_op_amoswap_w_rl:
      case riscv64_op_amoxor_d:
      case riscv64_op_amoxor_d_aq:
      case riscv64_op_amoxor_d_aq_rl:
      case riscv64_op_amoxor_d_rl:
      case riscv64_op_amoxor_w:
      case riscv64_op_amoxor_w_aq:
      case riscv64_op_amoxor_w_aq_rl:
      case riscv64_op_amoxor_w_rl:
      case riscv64_op_c_fsd:
      case riscv64_op_c_fsdsp:
      case riscv64_op_c_fsw:
      case riscv64_op_c_fswsp:
      case riscv64_op_c_sd:
      case riscv64_op_c_sdsp:
      case riscv64_op_c_sw:
      case riscv64_op_c_swsp:
      case riscv64_op_fsd:
      case riscv64_op_fsw:
      case riscv64_op_sb:
      case riscv64_op_sc_d:
      case riscv64_op_sc_d_aq:
      case riscv64_op_sc_d_aq_rl:
      case riscv64_op_sc_d_rl:
      case riscv64_op_sc_w:
      case riscv64_op_sc_w_aq:
      case riscv64_op_sc_w_aq_rl:
      case riscv64_op_sc_w_rl:
      case riscv64_op_sd:
      case riscv64_op_sh:
      case riscv64_op_sw:
        return true;
      default:
        return false;
    }
  }
  // clang-format off
  int8_t mem_size(entryID eid) {
    switch(eid) {
      case riscv64_op_lb:
      case riscv64_op_lbu:
      case riscv64_op_sb:
        return 1;
      case riscv64_op_lh:
      case riscv64_op_lhu:
      case riscv64_op_sh:
        return 2;
      case riscv64_op_c_flw:
      case riscv64_op_c_flwsp:
      case riscv64_op_c_fsw:
      case riscv64_op_c_fswsp:
      case riscv64_op_c_lw:
      case riscv64_op_c_lwsp:
      case riscv64_op_c_sw:
      case riscv64_op_c_swsp:
      case riscv64_op_flw:
      case riscv64_op_fsw:
      case riscv64_op_lr_w:
      case riscv64_op_lr_w_aq:
      case riscv64_op_lr_w_aq_rl:
      case riscv64_op_lr_w_rl:
      case riscv64_op_lw:
      case riscv64_op_lwu:
      case riscv64_op_sc_w:
      case riscv64_op_sc_w_aq:
      case riscv64_op_sc_w_aq_rl:
      case riscv64_op_sc_w_rl:
      case riscv64_op_sw:
        return 4;
      case riscv64_op_c_fld:
      case riscv64_op_c_fldsp:
      case riscv64_op_c_fsd:
      case riscv64_op_c_fsdsp:
      case riscv64_op_c_ld:
      case riscv64_op_c_ldsp:
      case riscv64_op_c_sd:
      case riscv64_op_c_sdsp:
      case riscv64_op_fld:
      case riscv64_op_fsd:
      case riscv64_op_ld:
      case riscv64_op_lr_d:
      case riscv64_op_lr_d_aq:
      case riscv64_op_lr_d_aq_rl:
      case riscv64_op_lr_d_rl:
      case riscv64_op_sc_d:
      case riscv64_op_sc_d_aq:
      case riscv64_op_sc_d_aq_rl:
      case riscv64_op_sc_d_rl:
      case riscv64_op_sd:
        return 8;
      // Atomic instructions
      case riscv64_op_amoadd_w:
      case riscv64_op_amoadd_w_aq:
      case riscv64_op_amoadd_w_aq_rl:
      case riscv64_op_amoadd_w_rl:
      case riscv64_op_amoand_w:
      case riscv64_op_amoand_w_aq:
      case riscv64_op_amoand_w_aq_rl:
      case riscv64_op_amoand_w_rl:
      case riscv64_op_amomaxu_w:
      case riscv64_op_amomaxu_w_aq:
      case riscv64_op_amomaxu_w_aq_rl:
      case riscv64_op_amomaxu_w_rl:
      case riscv64_op_amomax_w:
      case riscv64_op_amomax_w_aq:
      case riscv64_op_amomax_w_aq_rl:
      case riscv64_op_amomax_w_rl:
      case riscv64_op_amominu_w:
      case riscv64_op_amominu_w_aq:
      case riscv64_op_amominu_w_aq_rl:
      case riscv64_op_amominu_w_rl:
      case riscv64_op_amomin_w:
      case riscv64_op_amomin_w_aq:
      case riscv64_op_amomin_w_aq_rl:
      case riscv64_op_amomin_w_rl:
      case riscv64_op_amoor_w:
      case riscv64_op_amoor_w_aq:
      case riscv64_op_amoor_w_aq_rl:
      case riscv64_op_amoor_w_rl:
      case riscv64_op_amoswap_w:
      case riscv64_op_amoswap_w_aq:
      case riscv64_op_amoswap_w_aq_rl:
      case riscv64_op_amoswap_w_rl:
      case riscv64_op_amoxor_w:
      case riscv64_op_amoxor_w_aq:
      case riscv64_op_amoxor_w_aq_rl:
      case riscv64_op_amoxor_w_rl:
        return 4;
      case riscv64_op_amoadd_d:
      case riscv64_op_amoadd_d_aq:
      case riscv64_op_amoadd_d_aq_rl:
      case riscv64_op_amoadd_d_rl:
      case riscv64_op_amoand_d:
      case riscv64_op_amoand_d_aq:
      case riscv64_op_amoand_d_aq_rl:
      case riscv64_op_amoand_d_rl:
      case riscv64_op_amomax_d:
      case riscv64_op_amomax_d_aq:
      case riscv64_op_amomax_d_aq_rl:
      case riscv64_op_amomax_d_rl:
      case riscv64_op_amomaxu_d:
      case riscv64_op_amomaxu_d_aq:
      case riscv64_op_amomaxu_d_aq_rl:
      case riscv64_op_amomaxu_d_rl:
      case riscv64_op_amomin_d:
      case riscv64_op_amomin_d_aq:
      case riscv64_op_amomin_d_aq_rl:
      case riscv64_op_amomin_d_rl:
      case riscv64_op_amominu_d:
      case riscv64_op_amominu_d_aq:
      case riscv64_op_amominu_d_aq_rl:
      case riscv64_op_amominu_d_rl:
      case riscv64_op_amoor_d:
      case riscv64_op_amoor_d_aq:
      case riscv64_op_amoor_d_aq_rl:
      case riscv64_op_amoor_d_rl:
      case riscv64_op_amoswap_d:
      case riscv64_op_amoswap_d_aq:
      case riscv64_op_amoswap_d_aq_rl:
      case riscv64_op_amoswap_d_rl:
      case riscv64_op_amoxor_d:
      case riscv64_op_amoxor_d_aq:
      case riscv64_op_amoxor_d_aq_rl:
      case riscv64_op_amoxor_d_rl:
        return 8;
      default:
        return 0;
    }
  }
}}}
