test1_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_1.dll test1_1.obj $(TEST_LINKS)

test1_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_2.dll test1_2.obj $(TEST_LINKS)

test1_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_3.dll test1_3.obj $(TEST_LINKS)

test1_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_4.dll test1_4.obj $(TEST_LINKS)

test1_5.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_5.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_5.dll test1_5.obj $(TEST_LINKS)

test1_6.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_6.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_6.dll test1_6.obj $(TEST_LINKS)

test1_7.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_7.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_7.dll test1_7.obj $(TEST_LINKS)

test1_8.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_8.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_8.dll test1_8.obj $(TEST_LINKS)

test1_9.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_9.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_9.dll test1_9.obj $(TEST_LINKS)

test1_10.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_10.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_10.dll test1_10.obj $(TEST_LINKS)

test1_11.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_11.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_11.dll test1_11.obj $(TEST_LINKS)

test1_12.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_12.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_12.dll test1_12.obj $(TEST_LINKS)

test1_13.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_13.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_13.dll test1_13.obj $(TEST_LINKS)

test1_14.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_14.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_14.dll test1_14.obj $(TEST_LINKS)

test1_15.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_15.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_15.dll test1_15.obj $(TEST_LINKS)

test1_16.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_16.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_16.dll test1_16.obj $(TEST_LINKS)

test1_17.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_17.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_17.dll test1_17.obj $(TEST_LINKS)

test1_18.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_18.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_18.dll test1_18.obj $(TEST_LINKS)

test1_19.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_19.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_19.dll test1_19.obj $(TEST_LINKS)

test1_20.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_20.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_20.dll test1_20.obj $(TEST_LINKS)

test1_21.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_21.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_21.dll test1_21.obj $(TEST_LINKS)

test1_22.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_22.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_22.dll test1_22.obj $(TEST_LINKS)

test1_23.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_23.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_23.dll test1_23.obj $(TEST_LINKS)

test1_24.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_24.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_24.dll test1_24.obj $(TEST_LINKS)

test1_25.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_25.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_25.dll test1_25.obj $(TEST_LINKS)

test1_26.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_26.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_26.dll test1_26.obj $(TEST_LINKS)

test1_27.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_27.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_27.dll test1_27.obj $(TEST_LINKS)

test1_28.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_28.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_28.dll test1_28.obj $(TEST_LINKS)

test1_29.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_29.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_29.dll test1_29.obj $(TEST_LINKS)

test1_30.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_30.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_30.dll test1_30.obj $(TEST_LINKS)

test1_31.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_31.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_31.dll test1_31.obj $(TEST_LINKS)

test1_32.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_32.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_32.dll test1_32.obj $(TEST_LINKS)

test1_33.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_33.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_33.dll test1_33.obj $(TEST_LINKS)

test1_34.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_34.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_34.dll test1_34.obj $(TEST_LINKS)

test1_35.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_35.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_35.dll test1_35.obj $(TEST_LINKS)

test1_36.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_36.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_36.dll test1_36.obj $(TEST_LINKS)

test1_37.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_37.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_37.dll test1_37.obj $(TEST_LINKS)

test1_38.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_38.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_38.dll test1_38.obj $(TEST_LINKS)

test1_39.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_39.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_39.dll test1_39.obj $(TEST_LINKS)

test1_40.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test1_40.C
  $(LINK) $(LDFLAGS) -DLL -out:test1_40.dll test1_40.obj $(TEST_LINKS)

test2_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_1.dll test2_1.obj $(TEST_LINKS)

test2_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_2.dll test2_2.obj $(TEST_LINKS)

test2_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_3.dll test2_3.obj $(TEST_LINKS)

test2_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_4.dll test2_4.obj $(TEST_LINKS)

test2_5.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_5.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_5.dll test2_5.obj $(TEST_LINKS)

test2_6.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_6.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_6.dll test2_6.obj $(TEST_LINKS)

test2_7.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_7.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_7.dll test2_7.obj $(TEST_LINKS)

test2_8.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_8.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_8.dll test2_8.obj $(TEST_LINKS)

test2_9.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_9.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_9.dll test2_9.obj $(TEST_LINKS)

test2_10.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_10.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_10.dll test2_10.obj $(TEST_LINKS)

test2_11.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_11.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_11.dll test2_11.obj $(TEST_LINKS)

test2_12.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_12.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_12.dll test2_12.obj $(TEST_LINKS)

test2_13.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_13.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_13.dll test2_13.obj $(TEST_LINKS)

test2_14.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test2_14.C
  $(LINK) $(LDFLAGS) -DLL -out:test2_14.dll test2_14.obj $(TEST_LINKS)

test3_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test3_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test3_1.dll test3_1.obj $(TEST_LINKS)

test3_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test3_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test3_2.dll test3_2.obj $(TEST_LINKS)

test3_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test3_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test3_3.dll test3_3.obj $(TEST_LINKS)

test3_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test3_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test3_4.dll test3_4.obj $(TEST_LINKS)

test3_5.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test3_5.C
  $(LINK) $(LDFLAGS) -DLL -out:test3_5.dll test3_5.obj $(TEST_LINKS)

test4_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test4_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test4_1.dll test4_1.obj $(TEST_LINKS)

test4_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test4_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test4_2.dll test4_2.obj $(TEST_LINKS)

test4_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test4_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test4_3.dll test4_3.obj $(TEST_LINKS)

test4_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test4_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test4_4.dll test4_4.obj $(TEST_LINKS)

test5_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_1.dll test5_1.obj $(TEST_LINKS)

test5_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_2.dll test5_2.obj $(TEST_LINKS)

test5_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_3.dll test5_3.obj $(TEST_LINKS)

test5_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_4.dll test5_4.obj $(TEST_LINKS)

test5_5.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_5.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_5.dll test5_5.obj $(TEST_LINKS)

test5_6.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_6.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_6.dll test5_6.obj $(TEST_LINKS)

test5_7.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_7.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_7.dll test5_7.obj $(TEST_LINKS)

test5_8.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_8.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_8.dll test5_8.obj $(TEST_LINKS)

test5_9.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test5_9.C
  $(LINK) $(LDFLAGS) -DLL -out:test5_9.dll test5_9.obj $(TEST_LINKS)

test6_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_1.dll test6_1.obj $(TEST_LINKS)

test6_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_2.dll test6_2.obj $(TEST_LINKS)

test6_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_3.dll test6_3.obj $(TEST_LINKS)

test6_4.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_4.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_4.dll test6_4.obj $(TEST_LINKS)

test6_5.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_5.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_5.dll test6_5.obj $(TEST_LINKS)

test6_6.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_6.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_6.dll test6_6.obj $(TEST_LINKS)

test6_7.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_7.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_7.dll test6_7.obj $(TEST_LINKS)

test6_8.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test6_8.C
  $(LINK) $(LDFLAGS) -DLL -out:test6_8.dll test6_8.obj $(TEST_LINKS)

test8_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test8_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test8_1.dll test8_1.obj $(TEST_LINKS)

test8_2.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test8_2.C
  $(LINK) $(LDFLAGS) -DLL -out:test8_2.dll test8_2.obj $(TEST_LINKS)

test8_3.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test8_3.C
  $(LINK) $(LDFLAGS) -DLL -out:test8_3.dll test8_3.obj $(TEST_LINKS)

test13_1.dll:
  $(CXX) $(CXXFLAGS_NORM) -c ../src/test13_1.C
  $(LINK) $(LDFLAGS) -DLL -out:test13_1.dll test13_1.obj $(TEST_LINKS)
