#include "registers/MachRegister.h"
#include "registers/AMDGPU/amdgpu_gfx90a_regs.h"
#include "type_query_check.h"

constexpr auto arch = Dyninst::Arch_amdgpu_gfx90a;

static bool is_arithmetic_vector(Dyninst::MachRegister);

int main() {
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::pc_all, isPC);

  TYPE_QUERIES_CHECK_INVALID(getFramePointer, Dyninst::Arch_amdgpu_gfx90a);
  TYPE_QUERIES_CHECK_INVALID(getStackPointer, Dyninst::Arch_amdgpu_gfx90a);
  TYPE_QUERIES_CHECK_INVALID(getSyscallNumberReg, Dyninst::Arch_amdgpu_gfx90a);
  TYPE_QUERIES_CHECK_INVALID(getSyscallReturnValueReg, Dyninst::Arch_amdgpu_gfx90a);
  TYPE_QUERIES_CHECK_INVALID(getSyscallNumberOReg, Dyninst::Arch_amdgpu_gfx90a);
  TYPE_QUERIES_CHECK_INVALID(getZeroFlag, Dyninst::Arch_amdgpu_gfx90a);

  /*********************************************************************
   *      General Purpose
   *********************************************************************/
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s0, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s101, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::ttmp0, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::ttmp15, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s0, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s101, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v0, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v255, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc0, isGeneralPurpose);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc255, isGeneralPurpose);

  /*********************************************************************
   *      Control/Status
  *********************************************************************/
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::s0, isControlStatus);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::s101, isControlStatus);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::v0, isControlStatus);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::v255, isControlStatus);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::acc0, isControlStatus);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::acc255, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::vcc, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::vcc_lo, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::vcc_hi, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::exec, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::exec_lo, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::exec_hi, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::src_scc, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::src_vccz, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::src_execz, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::xnack_mask_lo, isControlStatus);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::xnack_mask_hi, isControlStatus);

  /*********************************************************************
   *      Floating-Point
  *********************************************************************/
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s0, isFloatingPoint);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::s101, isFloatingPoint);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v0, isFloatingPoint);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v255, isFloatingPoint);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc0, isFloatingPoint);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc255, isFloatingPoint);

  /*********************************************************************
   *      Vector
  *********************************************************************/
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v0, isVector);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::v255, isVector);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc0, isVector);
  TYPE_QUERIES_CHECK(Dyninst::amdgpu_gfx90a::acc255, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::ttmp0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::ttmp15, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::mrt0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::mrt7, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::null, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::pos0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::pos3, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::param0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::param31, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::attr0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::attr31, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::s0, isVector);
  TYPE_QUERIES_CHECK_FALSE(Dyninst::amdgpu_gfx90a::s101, isVector);

  /*********************************************************************
   *      Filtering
  *********************************************************************/
  {
    for(auto reg : Dyninst::MachRegister::getAllRegistersForArch(arch)) {
      if(reg.isVector() && !reg.isControlStatus()) {
        TYPE_QUERIES_ASSERT_TRUE(reg, is_arithmetic_vector(reg));
      }
      if(is_arithmetic_vector(reg)) {
        TYPE_QUERIES_ASSERT_TRUE(reg, reg.isVector() && !reg.isControlStatus());
      }
    }
  }
  return EXIT_SUCCESS;
}

static bool is_arithmetic_vector(Dyninst::MachRegister reg) {
  switch(reg) {
    case Dyninst::amdgpu_gfx90a::iacc0:
    case Dyninst::amdgpu_gfx90a::iacc1:
    case Dyninst::amdgpu_gfx90a::iacc2:
    case Dyninst::amdgpu_gfx90a::iacc3:
    case Dyninst::amdgpu_gfx90a::iacc4:
    case Dyninst::amdgpu_gfx90a::iacc5:
    case Dyninst::amdgpu_gfx90a::iacc6:
    case Dyninst::amdgpu_gfx90a::iacc7:
    case Dyninst::amdgpu_gfx90a::iacc8:
    case Dyninst::amdgpu_gfx90a::iacc9:
    case Dyninst::amdgpu_gfx90a::iacc10:
    case Dyninst::amdgpu_gfx90a::iacc11:
    case Dyninst::amdgpu_gfx90a::iacc12:
    case Dyninst::amdgpu_gfx90a::iacc13:
    case Dyninst::amdgpu_gfx90a::iacc14:
    case Dyninst::amdgpu_gfx90a::iacc15:
    case Dyninst::amdgpu_gfx90a::iacc16:
    case Dyninst::amdgpu_gfx90a::iacc17:
    case Dyninst::amdgpu_gfx90a::iacc18:
    case Dyninst::amdgpu_gfx90a::iacc19:
    case Dyninst::amdgpu_gfx90a::iacc20:
    case Dyninst::amdgpu_gfx90a::iacc21:
    case Dyninst::amdgpu_gfx90a::iacc22:
    case Dyninst::amdgpu_gfx90a::iacc23:
    case Dyninst::amdgpu_gfx90a::iacc24:
    case Dyninst::amdgpu_gfx90a::iacc25:
    case Dyninst::amdgpu_gfx90a::iacc26:
    case Dyninst::amdgpu_gfx90a::iacc27:
    case Dyninst::amdgpu_gfx90a::iacc28:
    case Dyninst::amdgpu_gfx90a::iacc29:
    case Dyninst::amdgpu_gfx90a::iacc30:
    case Dyninst::amdgpu_gfx90a::iacc31:
    case Dyninst::amdgpu_gfx90a::iacc32:
    case Dyninst::amdgpu_gfx90a::iacc33:
    case Dyninst::amdgpu_gfx90a::iacc34:
    case Dyninst::amdgpu_gfx90a::iacc35:
    case Dyninst::amdgpu_gfx90a::iacc36:
    case Dyninst::amdgpu_gfx90a::iacc37:
    case Dyninst::amdgpu_gfx90a::iacc38:
    case Dyninst::amdgpu_gfx90a::iacc39:
    case Dyninst::amdgpu_gfx90a::iacc40:
    case Dyninst::amdgpu_gfx90a::iacc41:
    case Dyninst::amdgpu_gfx90a::iacc42:
    case Dyninst::amdgpu_gfx90a::iacc43:
    case Dyninst::amdgpu_gfx90a::iacc44:
    case Dyninst::amdgpu_gfx90a::iacc45:
    case Dyninst::amdgpu_gfx90a::iacc46:
    case Dyninst::amdgpu_gfx90a::iacc47:
    case Dyninst::amdgpu_gfx90a::iacc48:
    case Dyninst::amdgpu_gfx90a::iacc49:
    case Dyninst::amdgpu_gfx90a::iacc50:
    case Dyninst::amdgpu_gfx90a::iacc51:
    case Dyninst::amdgpu_gfx90a::iacc52:
    case Dyninst::amdgpu_gfx90a::iacc53:
    case Dyninst::amdgpu_gfx90a::iacc54:
    case Dyninst::amdgpu_gfx90a::iacc55:
    case Dyninst::amdgpu_gfx90a::iacc56:
    case Dyninst::amdgpu_gfx90a::iacc57:
    case Dyninst::amdgpu_gfx90a::iacc58:
    case Dyninst::amdgpu_gfx90a::iacc59:
    case Dyninst::amdgpu_gfx90a::iacc60:
    case Dyninst::amdgpu_gfx90a::iacc61:
    case Dyninst::amdgpu_gfx90a::iacc62:
    case Dyninst::amdgpu_gfx90a::iacc63:
    case Dyninst::amdgpu_gfx90a::iacc64:
    case Dyninst::amdgpu_gfx90a::iacc65:
    case Dyninst::amdgpu_gfx90a::iacc66:
    case Dyninst::amdgpu_gfx90a::iacc67:
    case Dyninst::amdgpu_gfx90a::iacc68:
    case Dyninst::amdgpu_gfx90a::iacc69:
    case Dyninst::amdgpu_gfx90a::iacc70:
    case Dyninst::amdgpu_gfx90a::iacc71:
    case Dyninst::amdgpu_gfx90a::iacc72:
    case Dyninst::amdgpu_gfx90a::iacc73:
    case Dyninst::amdgpu_gfx90a::iacc74:
    case Dyninst::amdgpu_gfx90a::iacc75:
    case Dyninst::amdgpu_gfx90a::iacc76:
    case Dyninst::amdgpu_gfx90a::iacc77:
    case Dyninst::amdgpu_gfx90a::iacc78:
    case Dyninst::amdgpu_gfx90a::iacc79:
    case Dyninst::amdgpu_gfx90a::iacc80:
    case Dyninst::amdgpu_gfx90a::iacc81:
    case Dyninst::amdgpu_gfx90a::iacc82:
    case Dyninst::amdgpu_gfx90a::iacc83:
    case Dyninst::amdgpu_gfx90a::iacc84:
    case Dyninst::amdgpu_gfx90a::iacc85:
    case Dyninst::amdgpu_gfx90a::iacc86:
    case Dyninst::amdgpu_gfx90a::iacc87:
    case Dyninst::amdgpu_gfx90a::iacc88:
    case Dyninst::amdgpu_gfx90a::iacc89:
    case Dyninst::amdgpu_gfx90a::iacc90:
    case Dyninst::amdgpu_gfx90a::iacc91:
    case Dyninst::amdgpu_gfx90a::iacc92:
    case Dyninst::amdgpu_gfx90a::iacc93:
    case Dyninst::amdgpu_gfx90a::iacc94:
    case Dyninst::amdgpu_gfx90a::iacc95:
    case Dyninst::amdgpu_gfx90a::iacc96:
    case Dyninst::amdgpu_gfx90a::iacc97:
    case Dyninst::amdgpu_gfx90a::iacc98:
    case Dyninst::amdgpu_gfx90a::iacc99:
    case Dyninst::amdgpu_gfx90a::iacc100:
    case Dyninst::amdgpu_gfx90a::iacc101:
    case Dyninst::amdgpu_gfx90a::iacc102:
    case Dyninst::amdgpu_gfx90a::iacc103:
    case Dyninst::amdgpu_gfx90a::iacc104:
    case Dyninst::amdgpu_gfx90a::iacc105:
    case Dyninst::amdgpu_gfx90a::iacc106:
    case Dyninst::amdgpu_gfx90a::iacc107:
    case Dyninst::amdgpu_gfx90a::iacc108:
    case Dyninst::amdgpu_gfx90a::iacc109:
    case Dyninst::amdgpu_gfx90a::iacc110:
    case Dyninst::amdgpu_gfx90a::iacc111:
    case Dyninst::amdgpu_gfx90a::iacc112:
    case Dyninst::amdgpu_gfx90a::iacc113:
    case Dyninst::amdgpu_gfx90a::iacc114:
    case Dyninst::amdgpu_gfx90a::iacc115:
    case Dyninst::amdgpu_gfx90a::iacc116:
    case Dyninst::amdgpu_gfx90a::iacc117:
    case Dyninst::amdgpu_gfx90a::iacc118:
    case Dyninst::amdgpu_gfx90a::iacc119:
    case Dyninst::amdgpu_gfx90a::iacc120:
    case Dyninst::amdgpu_gfx90a::iacc121:
    case Dyninst::amdgpu_gfx90a::iacc122:
    case Dyninst::amdgpu_gfx90a::iacc123:
    case Dyninst::amdgpu_gfx90a::iacc124:
    case Dyninst::amdgpu_gfx90a::iacc125:
    case Dyninst::amdgpu_gfx90a::iacc126:
    case Dyninst::amdgpu_gfx90a::iacc127:
    case Dyninst::amdgpu_gfx90a::iacc128:
    case Dyninst::amdgpu_gfx90a::iacc129:
    case Dyninst::amdgpu_gfx90a::iacc130:
    case Dyninst::amdgpu_gfx90a::iacc131:
    case Dyninst::amdgpu_gfx90a::iacc132:
    case Dyninst::amdgpu_gfx90a::iacc133:
    case Dyninst::amdgpu_gfx90a::iacc134:
    case Dyninst::amdgpu_gfx90a::iacc135:
    case Dyninst::amdgpu_gfx90a::iacc136:
    case Dyninst::amdgpu_gfx90a::iacc137:
    case Dyninst::amdgpu_gfx90a::iacc138:
    case Dyninst::amdgpu_gfx90a::iacc139:
    case Dyninst::amdgpu_gfx90a::iacc140:
    case Dyninst::amdgpu_gfx90a::iacc141:
    case Dyninst::amdgpu_gfx90a::iacc142:
    case Dyninst::amdgpu_gfx90a::iacc143:
    case Dyninst::amdgpu_gfx90a::iacc144:
    case Dyninst::amdgpu_gfx90a::iacc145:
    case Dyninst::amdgpu_gfx90a::iacc146:
    case Dyninst::amdgpu_gfx90a::iacc147:
    case Dyninst::amdgpu_gfx90a::iacc148:
    case Dyninst::amdgpu_gfx90a::iacc149:
    case Dyninst::amdgpu_gfx90a::iacc150:
    case Dyninst::amdgpu_gfx90a::iacc151:
    case Dyninst::amdgpu_gfx90a::iacc152:
    case Dyninst::amdgpu_gfx90a::iacc153:
    case Dyninst::amdgpu_gfx90a::iacc154:
    case Dyninst::amdgpu_gfx90a::iacc155:
    case Dyninst::amdgpu_gfx90a::iacc156:
    case Dyninst::amdgpu_gfx90a::iacc157:
    case Dyninst::amdgpu_gfx90a::iacc158:
    case Dyninst::amdgpu_gfx90a::iacc159:
    case Dyninst::amdgpu_gfx90a::iacc160:
    case Dyninst::amdgpu_gfx90a::iacc161:
    case Dyninst::amdgpu_gfx90a::iacc162:
    case Dyninst::amdgpu_gfx90a::iacc163:
    case Dyninst::amdgpu_gfx90a::iacc164:
    case Dyninst::amdgpu_gfx90a::iacc165:
    case Dyninst::amdgpu_gfx90a::iacc166:
    case Dyninst::amdgpu_gfx90a::iacc167:
    case Dyninst::amdgpu_gfx90a::iacc168:
    case Dyninst::amdgpu_gfx90a::iacc169:
    case Dyninst::amdgpu_gfx90a::iacc170:
    case Dyninst::amdgpu_gfx90a::iacc171:
    case Dyninst::amdgpu_gfx90a::iacc172:
    case Dyninst::amdgpu_gfx90a::iacc173:
    case Dyninst::amdgpu_gfx90a::iacc174:
    case Dyninst::amdgpu_gfx90a::iacc175:
    case Dyninst::amdgpu_gfx90a::iacc176:
    case Dyninst::amdgpu_gfx90a::iacc177:
    case Dyninst::amdgpu_gfx90a::iacc178:
    case Dyninst::amdgpu_gfx90a::iacc179:
    case Dyninst::amdgpu_gfx90a::iacc180:
    case Dyninst::amdgpu_gfx90a::iacc181:
    case Dyninst::amdgpu_gfx90a::iacc182:
    case Dyninst::amdgpu_gfx90a::iacc183:
    case Dyninst::amdgpu_gfx90a::iacc184:
    case Dyninst::amdgpu_gfx90a::iacc185:
    case Dyninst::amdgpu_gfx90a::iacc186:
    case Dyninst::amdgpu_gfx90a::iacc187:
    case Dyninst::amdgpu_gfx90a::iacc188:
    case Dyninst::amdgpu_gfx90a::iacc189:
    case Dyninst::amdgpu_gfx90a::iacc190:
    case Dyninst::amdgpu_gfx90a::iacc191:
    case Dyninst::amdgpu_gfx90a::iacc192:
    case Dyninst::amdgpu_gfx90a::iacc193:
    case Dyninst::amdgpu_gfx90a::iacc194:
    case Dyninst::amdgpu_gfx90a::iacc195:
    case Dyninst::amdgpu_gfx90a::iacc196:
    case Dyninst::amdgpu_gfx90a::iacc197:
    case Dyninst::amdgpu_gfx90a::iacc198:
    case Dyninst::amdgpu_gfx90a::iacc199:
    case Dyninst::amdgpu_gfx90a::iacc200:
    case Dyninst::amdgpu_gfx90a::iacc201:
    case Dyninst::amdgpu_gfx90a::iacc202:
    case Dyninst::amdgpu_gfx90a::iacc203:
    case Dyninst::amdgpu_gfx90a::iacc204:
    case Dyninst::amdgpu_gfx90a::iacc205:
    case Dyninst::amdgpu_gfx90a::iacc206:
    case Dyninst::amdgpu_gfx90a::iacc207:
    case Dyninst::amdgpu_gfx90a::iacc208:
    case Dyninst::amdgpu_gfx90a::iacc209:
    case Dyninst::amdgpu_gfx90a::iacc210:
    case Dyninst::amdgpu_gfx90a::iacc211:
    case Dyninst::amdgpu_gfx90a::iacc212:
    case Dyninst::amdgpu_gfx90a::iacc213:
    case Dyninst::amdgpu_gfx90a::iacc214:
    case Dyninst::amdgpu_gfx90a::iacc215:
    case Dyninst::amdgpu_gfx90a::iacc216:
    case Dyninst::amdgpu_gfx90a::iacc217:
    case Dyninst::amdgpu_gfx90a::iacc218:
    case Dyninst::amdgpu_gfx90a::iacc219:
    case Dyninst::amdgpu_gfx90a::iacc220:
    case Dyninst::amdgpu_gfx90a::iacc221:
    case Dyninst::amdgpu_gfx90a::iacc222:
    case Dyninst::amdgpu_gfx90a::iacc223:
    case Dyninst::amdgpu_gfx90a::iacc224:
    case Dyninst::amdgpu_gfx90a::iacc225:
    case Dyninst::amdgpu_gfx90a::iacc226:
    case Dyninst::amdgpu_gfx90a::iacc227:
    case Dyninst::amdgpu_gfx90a::iacc228:
    case Dyninst::amdgpu_gfx90a::iacc229:
    case Dyninst::amdgpu_gfx90a::iacc230:
    case Dyninst::amdgpu_gfx90a::iacc231:
    case Dyninst::amdgpu_gfx90a::iacc232:
    case Dyninst::amdgpu_gfx90a::iacc233:
    case Dyninst::amdgpu_gfx90a::iacc234:
    case Dyninst::amdgpu_gfx90a::iacc235:
    case Dyninst::amdgpu_gfx90a::iacc236:
    case Dyninst::amdgpu_gfx90a::iacc237:
    case Dyninst::amdgpu_gfx90a::iacc238:
    case Dyninst::amdgpu_gfx90a::iacc239:
    case Dyninst::amdgpu_gfx90a::iacc240:
    case Dyninst::amdgpu_gfx90a::iacc241:
    case Dyninst::amdgpu_gfx90a::iacc242:
    case Dyninst::amdgpu_gfx90a::iacc243:
    case Dyninst::amdgpu_gfx90a::iacc244:
    case Dyninst::amdgpu_gfx90a::iacc245:
    case Dyninst::amdgpu_gfx90a::iacc246:
    case Dyninst::amdgpu_gfx90a::iacc247:
    case Dyninst::amdgpu_gfx90a::iacc248:
    case Dyninst::amdgpu_gfx90a::iacc249:
    case Dyninst::amdgpu_gfx90a::iacc250:
    case Dyninst::amdgpu_gfx90a::iacc251:
    case Dyninst::amdgpu_gfx90a::iacc252:
    case Dyninst::amdgpu_gfx90a::iacc253:
    case Dyninst::amdgpu_gfx90a::iacc254:
    case Dyninst::amdgpu_gfx90a::iacc255:

    case Dyninst::amdgpu_gfx90a::iv0:
    case Dyninst::amdgpu_gfx90a::iv1:
    case Dyninst::amdgpu_gfx90a::iv2:
    case Dyninst::amdgpu_gfx90a::iv3:
    case Dyninst::amdgpu_gfx90a::iv4:
    case Dyninst::amdgpu_gfx90a::iv5:
    case Dyninst::amdgpu_gfx90a::iv6:
    case Dyninst::amdgpu_gfx90a::iv7:
    case Dyninst::amdgpu_gfx90a::iv8:
    case Dyninst::amdgpu_gfx90a::iv9:
    case Dyninst::amdgpu_gfx90a::iv10:
    case Dyninst::amdgpu_gfx90a::iv11:
    case Dyninst::amdgpu_gfx90a::iv12:
    case Dyninst::amdgpu_gfx90a::iv13:
    case Dyninst::amdgpu_gfx90a::iv14:
    case Dyninst::amdgpu_gfx90a::iv15:
    case Dyninst::amdgpu_gfx90a::iv16:
    case Dyninst::amdgpu_gfx90a::iv17:
    case Dyninst::amdgpu_gfx90a::iv18:
    case Dyninst::amdgpu_gfx90a::iv19:
    case Dyninst::amdgpu_gfx90a::iv20:
    case Dyninst::amdgpu_gfx90a::iv21:
    case Dyninst::amdgpu_gfx90a::iv22:
    case Dyninst::amdgpu_gfx90a::iv23:
    case Dyninst::amdgpu_gfx90a::iv24:
    case Dyninst::amdgpu_gfx90a::iv25:
    case Dyninst::amdgpu_gfx90a::iv26:
    case Dyninst::amdgpu_gfx90a::iv27:
    case Dyninst::amdgpu_gfx90a::iv28:
    case Dyninst::amdgpu_gfx90a::iv29:
    case Dyninst::amdgpu_gfx90a::iv30:
    case Dyninst::amdgpu_gfx90a::iv31:
    case Dyninst::amdgpu_gfx90a::iv32:
    case Dyninst::amdgpu_gfx90a::iv33:
    case Dyninst::amdgpu_gfx90a::iv34:
    case Dyninst::amdgpu_gfx90a::iv35:
    case Dyninst::amdgpu_gfx90a::iv36:
    case Dyninst::amdgpu_gfx90a::iv37:
    case Dyninst::amdgpu_gfx90a::iv38:
    case Dyninst::amdgpu_gfx90a::iv39:
    case Dyninst::amdgpu_gfx90a::iv40:
    case Dyninst::amdgpu_gfx90a::iv41:
    case Dyninst::amdgpu_gfx90a::iv42:
    case Dyninst::amdgpu_gfx90a::iv43:
    case Dyninst::amdgpu_gfx90a::iv44:
    case Dyninst::amdgpu_gfx90a::iv45:
    case Dyninst::amdgpu_gfx90a::iv46:
    case Dyninst::amdgpu_gfx90a::iv47:
    case Dyninst::amdgpu_gfx90a::iv48:
    case Dyninst::amdgpu_gfx90a::iv49:
    case Dyninst::amdgpu_gfx90a::iv50:
    case Dyninst::amdgpu_gfx90a::iv51:
    case Dyninst::amdgpu_gfx90a::iv52:
    case Dyninst::amdgpu_gfx90a::iv53:
    case Dyninst::amdgpu_gfx90a::iv54:
    case Dyninst::amdgpu_gfx90a::iv55:
    case Dyninst::amdgpu_gfx90a::iv56:
    case Dyninst::amdgpu_gfx90a::iv57:
    case Dyninst::amdgpu_gfx90a::iv58:
    case Dyninst::amdgpu_gfx90a::iv59:
    case Dyninst::amdgpu_gfx90a::iv60:
    case Dyninst::amdgpu_gfx90a::iv61:
    case Dyninst::amdgpu_gfx90a::iv62:
    case Dyninst::amdgpu_gfx90a::iv63:
    case Dyninst::amdgpu_gfx90a::iv64:
    case Dyninst::amdgpu_gfx90a::iv65:
    case Dyninst::amdgpu_gfx90a::iv66:
    case Dyninst::amdgpu_gfx90a::iv67:
    case Dyninst::amdgpu_gfx90a::iv68:
    case Dyninst::amdgpu_gfx90a::iv69:
    case Dyninst::amdgpu_gfx90a::iv70:
    case Dyninst::amdgpu_gfx90a::iv71:
    case Dyninst::amdgpu_gfx90a::iv72:
    case Dyninst::amdgpu_gfx90a::iv73:
    case Dyninst::amdgpu_gfx90a::iv74:
    case Dyninst::amdgpu_gfx90a::iv75:
    case Dyninst::amdgpu_gfx90a::iv76:
    case Dyninst::amdgpu_gfx90a::iv77:
    case Dyninst::amdgpu_gfx90a::iv78:
    case Dyninst::amdgpu_gfx90a::iv79:
    case Dyninst::amdgpu_gfx90a::iv80:
    case Dyninst::amdgpu_gfx90a::iv81:
    case Dyninst::amdgpu_gfx90a::iv82:
    case Dyninst::amdgpu_gfx90a::iv83:
    case Dyninst::amdgpu_gfx90a::iv84:
    case Dyninst::amdgpu_gfx90a::iv85:
    case Dyninst::amdgpu_gfx90a::iv86:
    case Dyninst::amdgpu_gfx90a::iv87:
    case Dyninst::amdgpu_gfx90a::iv88:
    case Dyninst::amdgpu_gfx90a::iv89:
    case Dyninst::amdgpu_gfx90a::iv90:
    case Dyninst::amdgpu_gfx90a::iv91:
    case Dyninst::amdgpu_gfx90a::iv92:
    case Dyninst::amdgpu_gfx90a::iv93:
    case Dyninst::amdgpu_gfx90a::iv94:
    case Dyninst::amdgpu_gfx90a::iv95:
    case Dyninst::amdgpu_gfx90a::iv96:
    case Dyninst::amdgpu_gfx90a::iv97:
    case Dyninst::amdgpu_gfx90a::iv98:
    case Dyninst::amdgpu_gfx90a::iv99:
    case Dyninst::amdgpu_gfx90a::iv100:
    case Dyninst::amdgpu_gfx90a::iv101:
    case Dyninst::amdgpu_gfx90a::iv102:
    case Dyninst::amdgpu_gfx90a::iv103:
    case Dyninst::amdgpu_gfx90a::iv104:
    case Dyninst::amdgpu_gfx90a::iv105:
    case Dyninst::amdgpu_gfx90a::iv106:
    case Dyninst::amdgpu_gfx90a::iv107:
    case Dyninst::amdgpu_gfx90a::iv108:
    case Dyninst::amdgpu_gfx90a::iv109:
    case Dyninst::amdgpu_gfx90a::iv110:
    case Dyninst::amdgpu_gfx90a::iv111:
    case Dyninst::amdgpu_gfx90a::iv112:
    case Dyninst::amdgpu_gfx90a::iv113:
    case Dyninst::amdgpu_gfx90a::iv114:
    case Dyninst::amdgpu_gfx90a::iv115:
    case Dyninst::amdgpu_gfx90a::iv116:
    case Dyninst::amdgpu_gfx90a::iv117:
    case Dyninst::amdgpu_gfx90a::iv118:
    case Dyninst::amdgpu_gfx90a::iv119:
    case Dyninst::amdgpu_gfx90a::iv120:
    case Dyninst::amdgpu_gfx90a::iv121:
    case Dyninst::amdgpu_gfx90a::iv122:
    case Dyninst::amdgpu_gfx90a::iv123:
    case Dyninst::amdgpu_gfx90a::iv124:
    case Dyninst::amdgpu_gfx90a::iv125:
    case Dyninst::amdgpu_gfx90a::iv126:
    case Dyninst::amdgpu_gfx90a::iv127:
    case Dyninst::amdgpu_gfx90a::iv128:
    case Dyninst::amdgpu_gfx90a::iv129:
    case Dyninst::amdgpu_gfx90a::iv130:
    case Dyninst::amdgpu_gfx90a::iv131:
    case Dyninst::amdgpu_gfx90a::iv132:
    case Dyninst::amdgpu_gfx90a::iv133:
    case Dyninst::amdgpu_gfx90a::iv134:
    case Dyninst::amdgpu_gfx90a::iv135:
    case Dyninst::amdgpu_gfx90a::iv136:
    case Dyninst::amdgpu_gfx90a::iv137:
    case Dyninst::amdgpu_gfx90a::iv138:
    case Dyninst::amdgpu_gfx90a::iv139:
    case Dyninst::amdgpu_gfx90a::iv140:
    case Dyninst::amdgpu_gfx90a::iv141:
    case Dyninst::amdgpu_gfx90a::iv142:
    case Dyninst::amdgpu_gfx90a::iv143:
    case Dyninst::amdgpu_gfx90a::iv144:
    case Dyninst::amdgpu_gfx90a::iv145:
    case Dyninst::amdgpu_gfx90a::iv146:
    case Dyninst::amdgpu_gfx90a::iv147:
    case Dyninst::amdgpu_gfx90a::iv148:
    case Dyninst::amdgpu_gfx90a::iv149:
    case Dyninst::amdgpu_gfx90a::iv150:
    case Dyninst::amdgpu_gfx90a::iv151:
    case Dyninst::amdgpu_gfx90a::iv152:
    case Dyninst::amdgpu_gfx90a::iv153:
    case Dyninst::amdgpu_gfx90a::iv154:
    case Dyninst::amdgpu_gfx90a::iv155:
    case Dyninst::amdgpu_gfx90a::iv156:
    case Dyninst::amdgpu_gfx90a::iv157:
    case Dyninst::amdgpu_gfx90a::iv158:
    case Dyninst::amdgpu_gfx90a::iv159:
    case Dyninst::amdgpu_gfx90a::iv160:
    case Dyninst::amdgpu_gfx90a::iv161:
    case Dyninst::amdgpu_gfx90a::iv162:
    case Dyninst::amdgpu_gfx90a::iv163:
    case Dyninst::amdgpu_gfx90a::iv164:
    case Dyninst::amdgpu_gfx90a::iv165:
    case Dyninst::amdgpu_gfx90a::iv166:
    case Dyninst::amdgpu_gfx90a::iv167:
    case Dyninst::amdgpu_gfx90a::iv168:
    case Dyninst::amdgpu_gfx90a::iv169:
    case Dyninst::amdgpu_gfx90a::iv170:
    case Dyninst::amdgpu_gfx90a::iv171:
    case Dyninst::amdgpu_gfx90a::iv172:
    case Dyninst::amdgpu_gfx90a::iv173:
    case Dyninst::amdgpu_gfx90a::iv174:
    case Dyninst::amdgpu_gfx90a::iv175:
    case Dyninst::amdgpu_gfx90a::iv176:
    case Dyninst::amdgpu_gfx90a::iv177:
    case Dyninst::amdgpu_gfx90a::iv178:
    case Dyninst::amdgpu_gfx90a::iv179:
    case Dyninst::amdgpu_gfx90a::iv180:
    case Dyninst::amdgpu_gfx90a::iv181:
    case Dyninst::amdgpu_gfx90a::iv182:
    case Dyninst::amdgpu_gfx90a::iv183:
    case Dyninst::amdgpu_gfx90a::iv184:
    case Dyninst::amdgpu_gfx90a::iv185:
    case Dyninst::amdgpu_gfx90a::iv186:
    case Dyninst::amdgpu_gfx90a::iv187:
    case Dyninst::amdgpu_gfx90a::iv188:
    case Dyninst::amdgpu_gfx90a::iv189:
    case Dyninst::amdgpu_gfx90a::iv190:
    case Dyninst::amdgpu_gfx90a::iv191:
    case Dyninst::amdgpu_gfx90a::iv192:
    case Dyninst::amdgpu_gfx90a::iv193:
    case Dyninst::amdgpu_gfx90a::iv194:
    case Dyninst::amdgpu_gfx90a::iv195:
    case Dyninst::amdgpu_gfx90a::iv196:
    case Dyninst::amdgpu_gfx90a::iv197:
    case Dyninst::amdgpu_gfx90a::iv198:
    case Dyninst::amdgpu_gfx90a::iv199:
    case Dyninst::amdgpu_gfx90a::iv200:
    case Dyninst::amdgpu_gfx90a::iv201:
    case Dyninst::amdgpu_gfx90a::iv202:
    case Dyninst::amdgpu_gfx90a::iv203:
    case Dyninst::amdgpu_gfx90a::iv204:
    case Dyninst::amdgpu_gfx90a::iv205:
    case Dyninst::amdgpu_gfx90a::iv206:
    case Dyninst::amdgpu_gfx90a::iv207:
    case Dyninst::amdgpu_gfx90a::iv208:
    case Dyninst::amdgpu_gfx90a::iv209:
    case Dyninst::amdgpu_gfx90a::iv210:
    case Dyninst::amdgpu_gfx90a::iv211:
    case Dyninst::amdgpu_gfx90a::iv212:
    case Dyninst::amdgpu_gfx90a::iv213:
    case Dyninst::amdgpu_gfx90a::iv214:
    case Dyninst::amdgpu_gfx90a::iv215:
    case Dyninst::amdgpu_gfx90a::iv216:
    case Dyninst::amdgpu_gfx90a::iv217:
    case Dyninst::amdgpu_gfx90a::iv218:
    case Dyninst::amdgpu_gfx90a::iv219:
    case Dyninst::amdgpu_gfx90a::iv220:
    case Dyninst::amdgpu_gfx90a::iv221:
    case Dyninst::amdgpu_gfx90a::iv222:
    case Dyninst::amdgpu_gfx90a::iv223:
    case Dyninst::amdgpu_gfx90a::iv224:
    case Dyninst::amdgpu_gfx90a::iv225:
    case Dyninst::amdgpu_gfx90a::iv226:
    case Dyninst::amdgpu_gfx90a::iv227:
    case Dyninst::amdgpu_gfx90a::iv228:
    case Dyninst::amdgpu_gfx90a::iv229:
    case Dyninst::amdgpu_gfx90a::iv230:
    case Dyninst::amdgpu_gfx90a::iv231:
    case Dyninst::amdgpu_gfx90a::iv232:
    case Dyninst::amdgpu_gfx90a::iv233:
    case Dyninst::amdgpu_gfx90a::iv234:
    case Dyninst::amdgpu_gfx90a::iv235:
    case Dyninst::amdgpu_gfx90a::iv236:
    case Dyninst::amdgpu_gfx90a::iv237:
    case Dyninst::amdgpu_gfx90a::iv238:
    case Dyninst::amdgpu_gfx90a::iv239:
    case Dyninst::amdgpu_gfx90a::iv240:
    case Dyninst::amdgpu_gfx90a::iv241:
    case Dyninst::amdgpu_gfx90a::iv242:
    case Dyninst::amdgpu_gfx90a::iv243:
    case Dyninst::amdgpu_gfx90a::iv244:
    case Dyninst::amdgpu_gfx90a::iv245:
    case Dyninst::amdgpu_gfx90a::iv246:
    case Dyninst::amdgpu_gfx90a::iv247:
    case Dyninst::amdgpu_gfx90a::iv248:
    case Dyninst::amdgpu_gfx90a::iv249:
    case Dyninst::amdgpu_gfx90a::iv250:
    case Dyninst::amdgpu_gfx90a::iv251:
    case Dyninst::amdgpu_gfx90a::iv252:
    case Dyninst::amdgpu_gfx90a::iv253:
    case Dyninst::amdgpu_gfx90a::iv254:
    case Dyninst::amdgpu_gfx90a::iv255:
      return true;
  }
  return false;
}
