/* src/config.h.  Generated by configure.  */
/***********************************************************************
 * Copyright © 2003 Dorian C. Arnold, Philip C. Roth, Barton P. Miller *
 *                  Detailed MRNet usage rights in "LICENSE" file.     *
 **********************************************************************/

#if !defined(__config_h)
#define __config_h 1


#define DEFAULT_PORT 7777
#define MAX_STRING_SIZE (1024*4)
#define MAX_LINELENGTH 1024
#define DEFAULT_RSH_COMMAND "ssh"
#define RSH_COMMAND_ENV "MRNET_RSH"
#define RUNAUTH_COMMAND_ENV "MRNET_RUNAUTH"

#define COMMNODE_EXE "mrnet_commnode"

#define OUTPUT_LEVEL 1

//Autoconfigured macros below
/* #undef WORDS_BIGENDIAN */

#define SIZEOF_CHAR 1
#define SIZEOF_INT 4
#define SIZEOF_SHORT 2
#define SIZEOF_LONG 4
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8

#define SIZEOF_INT16 2
#define SIZEOF_INT32 4
#define SIZEOF_INT64 8

#endif /* !defined(__config_h) */

