#include "baseTramp-x86.h"
#include "emitter.h"
#include "codegen/codegen.h"
#include "registerSpace/registerSpace.h"
#include "registerSpace/RegisterConversion.h"

#include "Instruction.h"
#include "InstructionCategories.h"
#include "InstructionDecoder.h"
#include "registers/x86_64_regs.h"
#include "arch-regs-x86.h"

#include <set>

bool baseTramp_x86::generateSaves(codeGen &gen, registerSpace *) {
  return gen.codeEmitter()->emitBTSaves(this, gen);
}

bool baseTramp_x86::generateRestores(codeGen &gen, registerSpace *) {
  return gen.codeEmitter()->emitBTRestores(this, gen);
}

// Decode the instrumentation body that was just generated into
// gen ([bodyStart, gen.getIndex())) and record every architectural register
// it writes -- including the individual condition flags -- through
// codeGen::markRegDefined. Emitters already mark the GPRs they allocate, but
// they never mark the flags, and an opaque PatchAPI snippet (raw bytes copied
// into the buffer) marks nothing at all. Decoding the generated bytes makes
// definedRegs authoritative for both, which lets shouldRegenBaseTramp /
// emitBTSaves drop the lahf/seto flags spill (and any GPR save) around
// instrumentation that provably clobbers nothing, e.g. a bare ptwrite.
//
// Anything that cannot be bounded reverts to a conservative clobber set,
// with the bound matched to what is actually known:
//  - a call, syscall, or interrupt transfers control to code we do not scan,
//    but the System V ABI bounds its effect: callee-saved registers come
//    back intact, so only the call-clobbered GPRs and the flags (which no
//    ABI preserves) are marked;
//  - a decode failure means nothing is known about that instruction or the
//    rest of the body, so every GPR and flag is marked.
// Branch targets are not checked; AST-generated control flow stays inside
// the body.
//
// 64-bit only for now: a 32-bit mutatee (this codegen arch also serves those
// via cap_32_64) models all condition flags as the single
// IA32_FLAG_VIRTUAL_REGISTER slot, so the per-flag register numbering used
// here does not apply and those tramps keep the conservative saves.
namespace {

// The individual flag slots the x86-64 register space tracks, plus
// REGNUM_EFLAGS, the whole-flags-register aggregate that liveness overrides
// and decoded aggregate writes use (see registerSpace::checkVolatileRegisters
// and saveVolatileRegisters, which handle the same aggregate-vs-individual
// split). Listed explicitly: no assumption about enum ordering.
const Dyninst::Register x86_64FlagSlots[] = {
    REGNUM_OF, REGNUM_SF, REGNUM_ZF, REGNUM_AF, REGNUM_PF, REGNUM_CF,
    REGNUM_TF, REGNUM_IF, REGNUM_DF, REGNUM_NT, REGNUM_RF, REGNUM_EFLAGS};

template <size_t N>
void markClobbers(codeGen &gen, const Dyninst::MachRegister (&regs)[N]) {
  for (const auto &mr : regs) {
    Dyninst::Register r = convertRegID(mr);
    if (r != REGNUM_IGNORED) gen.markRegDefined(r);
  }
}

// All condition flags: no ABI preserves them across a call.
void markFlagClobbers(codeGen &gen) {
  namespace dr = Dyninst::x86_64;
  static const Dyninst::MachRegister flags[] = {
      dr::of, dr::sf, dr::zf, dr::af, dr::pf, dr::cf, dr::df, dr::flags};
  markClobbers(gen, flags);
}

// The System V AMD64 call-clobbered GPRs: what a standard-ABI callee may
// leave modified.
void markCallClobbers(codeGen &gen) {
  namespace dr = Dyninst::x86_64;
  static const Dyninst::MachRegister volatiles[] = {
      dr::rax, dr::rcx, dr::rdx, dr::rsi, dr::rdi,
      dr::r8,  dr::r9,  dr::r10, dr::r11};
  markFlagClobbers(gen);
  markClobbers(gen, volatiles);
}

// Undecodable code: nothing is bounded, mark every GPR and flag. (RSP is
// included for completeness; the save logic never saves it.)
void markAllClobbers(codeGen &gen) {
  namespace dr = Dyninst::x86_64;
  static const Dyninst::MachRegister gprs[] = {
      dr::rax, dr::rcx, dr::rdx, dr::rbx, dr::rsp, dr::rbp, dr::rsi, dr::rdi,
      dr::r8,  dr::r9,  dr::r10, dr::r11, dr::r12, dr::r13, dr::r14, dr::r15};
  markFlagClobbers(gen);
  markClobbers(gen, gprs);
}

} // namespace

void baseTramp_x86::accumulateBodyClobbers(codeGen &gen, codeBufIndex_t bodyStart) {
  namespace di = Dyninst::InstructionAPI;

  if (gen.getArch() != Dyninst::Arch_x86_64) return;

  codeBufIndex_t bodyEnd = gen.getIndex();
  if (bodyEnd <= bodyStart) return;

  // On x86 a codeGen index is a byte offset.
  const unsigned char *body = (const unsigned char *)gen.start_ptr() + bodyStart;
  size_t len = bodyEnd - bodyStart;

  di::InstructionDecoder dec(body, len, gen.getArch());
  size_t consumed = 0;
  while (consumed < len) {
    di::Instruction insn = dec.decode();
    if (!insn.isValid() || insn.size() == 0) {
      markAllClobbers(gen);
      return;
    }
    consumed += insn.size();
    switch (insn.getCategory()) {
      case di::c_CallInsn:
      case di::c_SysEnterInsn:
      case di::c_SyscallInsn:
      case di::c_InterruptInsn:
        markCallClobbers(gen);
        continue;
      default:
        break;
    }
    std::set<di::RegisterAST::Ptr> writes;
    insn.getWriteSet(writes);
    for (const auto &w : writes) {
      Dyninst::Register r = convertRegID(w->getID());
      if (r != REGNUM_IGNORED) gen.markRegDefined(r);
    }
  }
}

// False only when the generated body provably never writes a flag: every
// flag slot (and the EFLAGS aggregate) is clear in definedRegs, which
// baseTramp_x86::accumulateBodyClobbers filled from the generated code.
// Conservative (true) until the body has been generated once.
bool baseTramp_x86::mayClobberVolatileRegs() {
  if (!validOptimizationInfo()) return true;
  for (auto r : x86_64FlagSlots)
    if (definedRegs[r]) return true;
  return false;
}

// The flags parallel of shouldRegenBaseTramp's unneeded-GPR
// check. emitBTSaves decides the flags save before the body exists, so on the
// first pass live flags are always saved (lahf/seto + rax spill). If the
// generated body never wrote a flag (see accumulateBodyClobbers above),
// report the save as unneeded so the tramp regenerates; with
// validOptimizationInfo set, emitBTSaves then skips the save.
bool baseTramp_x86::savedUnneededVolatileRegs(registerSpace *rs) {
  if (rs->getAddressWidth() != 8) return false;

  bool flagsSaved = false;
  for (auto r : x86_64FlagSlots)
    if ((*rs)[r]->liveState == registerSlot::spilled) {
      flagsSaved = true;
      break;
    }

  return flagsSaved && !mayClobberVolatileRegs();
}
