	case amdgpu_op_s_branch:
	case amdgpu_op_s_cbranch_scc0:
	case amdgpu_op_s_cbranch_scc1:
	case amdgpu_op_s_cbranch_vccz:
	case amdgpu_op_s_cbranch_vccnz:
	case amdgpu_op_s_cbranch_execz:
	case amdgpu_op_s_cbranch_execnz:
	case amdgpu_op_s_cbranch_cdbgsys:
	case amdgpu_op_s_cbranch_cdbguser:
	case amdgpu_op_s_cbranch_cdbgsys_and_user:
	case amdgpu_op_s_setpc_b64:
	case amdgpu_op_s_swappc_b64:
	case amdgpu_op_s_rfe_b64:
	case amdgpu_op_s_cbranch_g_fork:
	case amdgpu_op_s_cbranch_i_fork:
	case amdgpu_op_s_call_b64:
