#include "InstructionDecoder-Capstone.h"

using std::make_pair;

namespace Dyninst {

    namespace InstructionAPI {

        void InstructionDecoder_Capstone::decodeOperands_riscv64(const Instruction* insn, cs_detail *d) {
        }

        entryID InstructionDecoder_Capstone::opcodeTranslation_riscv64(unsigned int cap_id) {
            switch (cap_id) {
                case RISCV_INS_ADD:
                    return riscv64_op_add;
                case RISCV_INS_ADDI:
                    return riscv64_op_addi;
                case RISCV_INS_ADDIW:
                    return riscv64_op_addiw;
                case RISCV_INS_ADDW:
                    return riscv64_op_addw;
                case RISCV_INS_AMOADD_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOADD_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOADD_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOADD_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOADD_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOADD_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOADD_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOADD_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOAND_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOAND_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOAND_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOAND_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOAND_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOAND_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOAND_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOAND_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAXU_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOMAXU_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMAXU_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAXU_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAXU_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOMAXU_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMAXU_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAXU_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAX_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOMAX_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMAX_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAX_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAX_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOMAX_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMAX_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMAX_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMINU_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOMINU_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMINU_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMINU_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMINU_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOMINU_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMINU_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMINU_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMIN_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOMIN_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMIN_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMIN_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMIN_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOMIN_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOMIN_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOMIN_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOOR_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOOR_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOOR_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOOR_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOOR_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOOR_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOOR_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOOR_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOSWAP_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOSWAP_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOSWAP_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOSWAP_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOSWAP_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOSWAP_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOSWAP_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOSWAP_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOXOR_D:
                    return riscv64_op_d;
                case RISCV_INS_AMOXOR_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOXOR_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOXOR_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOXOR_W:
                    return riscv64_op_w;
                case RISCV_INS_AMOXOR_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_AMOXOR_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AMOXOR_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_AND:
                    return riscv64_op_and;
                case RISCV_INS_ANDI:
                    return riscv64_op_andi;
                case RISCV_INS_AUIPC:
                    return riscv64_op_auipc;
                case RISCV_INS_BEQ:
                    return riscv64_op_beq;
                case RISCV_INS_BGE:
                    return riscv64_op_bge;
                case RISCV_INS_BGEU:
                    return riscv64_op_bgeu;
                case RISCV_INS_BLT:
                    return riscv64_op_blt;
                case RISCV_INS_BLTU:
                    return riscv64_op_bltu;
                case RISCV_INS_BNE:
                    return riscv64_op_bne;
                case RISCV_INS_CSRRC:
                    return riscv64_op_csrrc;
                case RISCV_INS_CSRRCI:
                    return riscv64_op_csrrci;
                case RISCV_INS_CSRRS:
                    return riscv64_op_csrrs;
                case RISCV_INS_CSRRSI:
                    return riscv64_op_csrrsi;
                case RISCV_INS_CSRRW:
                    return riscv64_op_csrrw;
                case RISCV_INS_CSRRWI:
                    return riscv64_op_csrrwi;
                case RISCV_INS_C_ADD:
                    return riscv64_op_add;
                case RISCV_INS_C_ADDI:
                    return riscv64_op_addi;
                case RISCV_INS_C_ADDI16SP:
                    return riscv64_op_addi16sp;
                case RISCV_INS_C_ADDI4SPN:
                    return riscv64_op_addi4spn;
                case RISCV_INS_C_ADDIW:
                    return riscv64_op_addiw;
                case RISCV_INS_C_ADDW:
                    return riscv64_op_addw;
                case RISCV_INS_C_AND:
                    return riscv64_op_and;
                case RISCV_INS_C_ANDI:
                    return riscv64_op_andi;
                case RISCV_INS_C_BEQZ:
                    return riscv64_op_beqz;
                case RISCV_INS_C_BNEZ:
                    return riscv64_op_bnez;
                case RISCV_INS_C_EBREAK:
                    return riscv64_op_ebreak;
                case RISCV_INS_C_FLD:
                    return riscv64_op_fld;
                case RISCV_INS_C_FLDSP:
                    return riscv64_op_fldsp;
                case RISCV_INS_C_FLW:
                    return riscv64_op_flw;
                case RISCV_INS_C_FLWSP:
                    return riscv64_op_flwsp;
                case RISCV_INS_C_FSD:
                    return riscv64_op_fsd;
                case RISCV_INS_C_FSDSP:
                    return riscv64_op_fsdsp;
                case RISCV_INS_C_FSW:
                    return riscv64_op_fsw;
                case RISCV_INS_C_FSWSP:
                    return riscv64_op_fswsp;
                case RISCV_INS_C_J:
                    return riscv64_op_j;
                case RISCV_INS_C_JAL:
                    return riscv64_op_jal;
                case RISCV_INS_C_JALR:
                    return riscv64_op_jalr;
                case RISCV_INS_C_JR:
                    return riscv64_op_jr;
                case RISCV_INS_C_LD:
                    return riscv64_op_ld;
                case RISCV_INS_C_LDSP:
                    return riscv64_op_ldsp;
                case RISCV_INS_C_LI:
                    return riscv64_op_li;
                case RISCV_INS_C_LUI:
                    return riscv64_op_lui;
                case RISCV_INS_C_LW:
                    return riscv64_op_lw;
                case RISCV_INS_C_LWSP:
                    return riscv64_op_lwsp;
                case RISCV_INS_C_MV:
                    return riscv64_op_mv;
                case RISCV_INS_C_NOP:
                    return riscv64_op_nop;
                case RISCV_INS_C_OR:
                    return riscv64_op_or;
                case RISCV_INS_C_SD:
                    return riscv64_op_sd;
                case RISCV_INS_C_SDSP:
                    return riscv64_op_sdsp;
                case RISCV_INS_C_SLLI:
                    return riscv64_op_slli;
                case RISCV_INS_C_SRAI:
                    return riscv64_op_srai;
                case RISCV_INS_C_SRLI:
                    return riscv64_op_srli;
                case RISCV_INS_C_SUB:
                    return riscv64_op_sub;
                case RISCV_INS_C_SUBW:
                    return riscv64_op_subw;
                case RISCV_INS_C_SW:
                    return riscv64_op_sw;
                case RISCV_INS_C_SWSP:
                    return riscv64_op_swsp;
                case RISCV_INS_C_UNIMP:
                    return riscv64_op_unimp;
                case RISCV_INS_C_XOR:
                    return riscv64_op_xor;
                case RISCV_INS_DIV:
                    return riscv64_op_div;
                case RISCV_INS_DIVU:
                    return riscv64_op_divu;
                case RISCV_INS_DIVUW:
                    return riscv64_op_divuw;
                case RISCV_INS_DIVW:
                    return riscv64_op_divw;
                case RISCV_INS_EBREAK:
                    return riscv64_op_ebreak;
                case RISCV_INS_ECALL:
                    return riscv64_op_ecall;
                case RISCV_INS_FADD_D:
                    return riscv64_op_d;
                case RISCV_INS_FADD_S:
                    return riscv64_op_s;
                case RISCV_INS_FCLASS_D:
                    return riscv64_op_d;
                case RISCV_INS_FCLASS_S:
                    return riscv64_op_s;
                case RISCV_INS_FCVT_D_L:
                    return riscv64_op_l;
                case RISCV_INS_FCVT_D_LU:
                    return riscv64_op_lu;
                case RISCV_INS_FCVT_D_S:
                    return riscv64_op_s;
                case RISCV_INS_FCVT_D_W:
                    return riscv64_op_w;
                case RISCV_INS_FCVT_D_WU:
                    return riscv64_op_wu;
                case RISCV_INS_FCVT_LU_D:
                    return riscv64_op_d;
                case RISCV_INS_FCVT_LU_S:
                    return riscv64_op_s;
                case RISCV_INS_FCVT_L_D:
                    return riscv64_op_d;
                case RISCV_INS_FCVT_L_S:
                    return riscv64_op_s;
                case RISCV_INS_FCVT_S_D:
                    return riscv64_op_d;
                case RISCV_INS_FCVT_S_L:
                    return riscv64_op_l;
                case RISCV_INS_FCVT_S_LU:
                    return riscv64_op_lu;
                case RISCV_INS_FCVT_S_W:
                    return riscv64_op_w;
                case RISCV_INS_FCVT_S_WU:
                    return riscv64_op_wu;
                case RISCV_INS_FCVT_WU_D:
                    return riscv64_op_d;
                case RISCV_INS_FCVT_WU_S:
                    return riscv64_op_s;
                case RISCV_INS_FCVT_W_D:
                    return riscv64_op_d;
                case RISCV_INS_FCVT_W_S:
                    return riscv64_op_s;
                case RISCV_INS_FDIV_D:
                    return riscv64_op_d;
                case RISCV_INS_FDIV_S:
                    return riscv64_op_s;
                case RISCV_INS_FENCE:
                    return riscv64_op_fence;
                case RISCV_INS_FENCE_I:
                    return riscv64_op_i;
                case RISCV_INS_FENCE_TSO:
                    return riscv64_op_tso;
                case RISCV_INS_FEQ_D:
                    return riscv64_op_d;
                case RISCV_INS_FEQ_S:
                    return riscv64_op_s;
                case RISCV_INS_FLD:
                    return riscv64_op_fld;
                case RISCV_INS_FLE_D:
                    return riscv64_op_d;
                case RISCV_INS_FLE_S:
                    return riscv64_op_s;
                case RISCV_INS_FLT_D:
                    return riscv64_op_d;
                case RISCV_INS_FLT_S:
                    return riscv64_op_s;
                case RISCV_INS_FLW:
                    return riscv64_op_flw;
                case RISCV_INS_FMADD_D:
                    return riscv64_op_d;
                case RISCV_INS_FMADD_S:
                    return riscv64_op_s;
                case RISCV_INS_FMAX_D:
                    return riscv64_op_d;
                case RISCV_INS_FMAX_S:
                    return riscv64_op_s;
                case RISCV_INS_FMIN_D:
                    return riscv64_op_d;
                case RISCV_INS_FMIN_S:
                    return riscv64_op_s;
                case RISCV_INS_FMSUB_D:
                    return riscv64_op_d;
                case RISCV_INS_FMSUB_S:
                    return riscv64_op_s;
                case RISCV_INS_FMUL_D:
                    return riscv64_op_d;
                case RISCV_INS_FMUL_S:
                    return riscv64_op_s;
                case RISCV_INS_FMV_D_X:
                    return riscv64_op_x;
                case RISCV_INS_FMV_W_X:
                    return riscv64_op_x;
                case RISCV_INS_FMV_X_D:
                    return riscv64_op_d;
                case RISCV_INS_FMV_X_W:
                    return riscv64_op_w;
                case RISCV_INS_FNMADD_D:
                    return riscv64_op_d;
                case RISCV_INS_FNMADD_S:
                    return riscv64_op_s;
                case RISCV_INS_FNMSUB_D:
                    return riscv64_op_d;
                case RISCV_INS_FNMSUB_S:
                    return riscv64_op_s;
                case RISCV_INS_FSD:
                    return riscv64_op_fsd;
                case RISCV_INS_FSGNJN_D:
                    return riscv64_op_d;
                case RISCV_INS_FSGNJN_S:
                    return riscv64_op_s;
                case RISCV_INS_FSGNJX_D:
                    return riscv64_op_d;
                case RISCV_INS_FSGNJX_S:
                    return riscv64_op_s;
                case RISCV_INS_FSGNJ_D:
                    return riscv64_op_d;
                case RISCV_INS_FSGNJ_S:
                    return riscv64_op_s;
                case RISCV_INS_FSQRT_D:
                    return riscv64_op_d;
                case RISCV_INS_FSQRT_S:
                    return riscv64_op_s;
                case RISCV_INS_FSUB_D:
                    return riscv64_op_d;
                case RISCV_INS_FSUB_S:
                    return riscv64_op_s;
                case RISCV_INS_FSW:
                    return riscv64_op_fsw;
                case RISCV_INS_JAL:
                    return riscv64_op_jal;
                case RISCV_INS_JALR:
                    return riscv64_op_jalr;
                case RISCV_INS_LB:
                    return riscv64_op_lb;
                case RISCV_INS_LBU:
                    return riscv64_op_lbu;
                case RISCV_INS_LD:
                    return riscv64_op_ld;
                case RISCV_INS_LH:
                    return riscv64_op_lh;
                case RISCV_INS_LHU:
                    return riscv64_op_lhu;
                case RISCV_INS_LR_D:
                    return riscv64_op_d;
                case RISCV_INS_LR_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_LR_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_LR_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_LR_W:
                    return riscv64_op_w;
                case RISCV_INS_LR_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_LR_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_LR_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_LUI:
                    return riscv64_op_lui;
                case RISCV_INS_LW:
                    return riscv64_op_lw;
                case RISCV_INS_LWU:
                    return riscv64_op_lwu;
                case RISCV_INS_MRET:
                    return riscv64_op_mret;
                case RISCV_INS_MUL:
                    return riscv64_op_mul;
                case RISCV_INS_MULH:
                    return riscv64_op_mulh;
                case RISCV_INS_MULHSU:
                    return riscv64_op_mulhsu;
                case RISCV_INS_MULHU:
                    return riscv64_op_mulhu;
                case RISCV_INS_MULW:
                    return riscv64_op_mulw;
                case RISCV_INS_OR:
                    return riscv64_op_or;
                case RISCV_INS_ORI:
                    return riscv64_op_ori;
                case RISCV_INS_REM:
                    return riscv64_op_rem;
                case RISCV_INS_REMU:
                    return riscv64_op_remu;
                case RISCV_INS_REMUW:
                    return riscv64_op_remuw;
                case RISCV_INS_REMW:
                    return riscv64_op_remw;
                case RISCV_INS_SB:
                    return riscv64_op_sb;
                case RISCV_INS_SC_D:
                    return riscv64_op_d;
                case RISCV_INS_SC_D_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_SC_D_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_SC_D_RL:
                    return riscv64_op_rl;
                case RISCV_INS_SC_W:
                    return riscv64_op_w;
                case RISCV_INS_SC_W_AQ:
                    return riscv64_op_aq;
                case RISCV_INS_SC_W_AQ_RL:
                    return riscv64_op_rl;
                case RISCV_INS_SC_W_RL:
                    return riscv64_op_rl;
                case RISCV_INS_SD:
                    return riscv64_op_sd;
                case RISCV_INS_SFENCE_VMA:
                    return riscv64_op_vma;
                case RISCV_INS_SH:
                    return riscv64_op_sh;
                case RISCV_INS_SLL:
                    return riscv64_op_sll;
                case RISCV_INS_SLLI:
                    return riscv64_op_slli;
                case RISCV_INS_SLLIW:
                    return riscv64_op_slliw;
                case RISCV_INS_SLLW:
                    return riscv64_op_sllw;
                case RISCV_INS_SLT:
                    return riscv64_op_slt;
                case RISCV_INS_SLTI:
                    return riscv64_op_slti;
                case RISCV_INS_SLTIU:
                    return riscv64_op_sltiu;
                case RISCV_INS_SLTU:
                    return riscv64_op_sltu;
                case RISCV_INS_SRA:
                    return riscv64_op_sra;
                case RISCV_INS_SRAI:
                    return riscv64_op_srai;
                case RISCV_INS_SRAIW:
                    return riscv64_op_sraiw;
                case RISCV_INS_SRAW:
                    return riscv64_op_sraw;
                case RISCV_INS_SRET:
                    return riscv64_op_sret;
                case RISCV_INS_SRL:
                    return riscv64_op_srl;
                case RISCV_INS_SRLI:
                    return riscv64_op_srli;
                case RISCV_INS_SRLIW:
                    return riscv64_op_srliw;
                case RISCV_INS_SRLW:
                    return riscv64_op_srlw;
                case RISCV_INS_SUB:
                    return riscv64_op_sub;
                case RISCV_INS_SUBW:
                    return riscv64_op_subw;
                case RISCV_INS_SW:
                    return riscv64_op_sw;
                case RISCV_INS_UNIMP:
                    return riscv64_op_unimp;
                case RISCV_INS_URET:
                    return riscv64_op_uret;
                case RISCV_INS_WFI:
                    return riscv64_op_wfi;
                case RISCV_INS_XOR:
                    return riscv64_op_xor;
                case RISCV_INS_XORI:
                    return riscv64_op_xori;
                default:
                    return e_No_Entry;
            }
        }

        MachRegister InstructionDecoder_Capstone::registerTranslation_riscv64(riscv_reg cap_reg) {
            switch (cap_reg) {
                case RISCV_REG_X0:
                    return riscv64::x0;
                case RISCV_REG_X1:
                    return riscv64::x1;
                case RISCV_REG_X2:
                    return riscv64::x2;
                case RISCV_REG_X3:
                    return riscv64::x3;
                case RISCV_REG_X4:
                    return riscv64::x4;
                case RISCV_REG_X5:
                    return riscv64::x5;
                case RISCV_REG_X6:
                    return riscv64::x6;
                case RISCV_REG_X7:
                    return riscv64::x7;
                case RISCV_REG_X8:
                    return riscv64::x8;
                case RISCV_REG_X9:
                    return riscv64::x9;
                case RISCV_REG_X10:
                    return riscv64::x10;
                case RISCV_REG_X11:
                    return riscv64::x11;
                case RISCV_REG_X12:
                    return riscv64::x12;
                case RISCV_REG_X13:
                    return riscv64::x13;
                case RISCV_REG_X14:
                    return riscv64::x14;
                case RISCV_REG_X15:
                    return riscv64::x15;
                case RISCV_REG_X16:
                    return riscv64::x16;
                case RISCV_REG_X17:
                    return riscv64::x17;
                case RISCV_REG_X18:
                    return riscv64::x18;
                case RISCV_REG_X19:
                    return riscv64::x19;
                case RISCV_REG_X20:
                    return riscv64::x20;
                case RISCV_REG_X21:
                    return riscv64::x21;
                case RISCV_REG_X22:
                    return riscv64::x22;
                case RISCV_REG_X23:
                    return riscv64::x23;
                case RISCV_REG_X24:
                    return riscv64::x24;
                case RISCV_REG_X25:
                    return riscv64::x25;
                case RISCV_REG_X26:
                    return riscv64::x26;
                case RISCV_REG_X27:
                    return riscv64::x27;
                case RISCV_REG_X28:
                    return riscv64::x28;
                case RISCV_REG_X29:
                    return riscv64::x29;
                case RISCV_REG_X30:
                    return riscv64::x30;
                case RISCV_REG_X31:
                    return riscv64::x31;
                case RISCV_REG_F0_32:
                    return riscv64::f0_32;
                case RISCV_REG_F0_64:
                    return riscv64::f0_64;
                case RISCV_REG_F1_32:
                    return riscv64::f1_32;
                case RISCV_REG_F1_64:
                    return riscv64::f1_64;
                case RISCV_REG_F2_32:
                    return riscv64::f2_32;
                case RISCV_REG_F2_64:
                    return riscv64::f2_64;
                case RISCV_REG_F3_32:
                    return riscv64::f3_32;
                case RISCV_REG_F3_64:
                    return riscv64::f3_64;
                case RISCV_REG_F4_32:
                    return riscv64::f4_32;
                case RISCV_REG_F4_64:
                    return riscv64::f4_64;
                case RISCV_REG_F5_32:
                    return riscv64::f5_32;
                case RISCV_REG_F5_64:
                    return riscv64::f5_64;
                case RISCV_REG_F6_32:
                    return riscv64::f6_32;
                case RISCV_REG_F6_64:
                    return riscv64::f6_64;
                case RISCV_REG_F7_32:
                    return riscv64::f7_32;
                case RISCV_REG_F7_64:
                    return riscv64::f7_64;
                case RISCV_REG_F8_32:
                    return riscv64::f8_32;
                case RISCV_REG_F8_64:
                    return riscv64::f8_64;
                case RISCV_REG_F9_32:
                    return riscv64::f9_32;
                case RISCV_REG_F9_64:
                    return riscv64::f9_64;
                case RISCV_REG_F10_32:
                    return riscv64::f10_32;
                case RISCV_REG_F10_64:
                    return riscv64::f10_64;
                case RISCV_REG_F11_32:
                    return riscv64::f11_32;
                case RISCV_REG_F11_64:
                    return riscv64::f11_64;
                case RISCV_REG_F12_32:
                    return riscv64::f12_32;
                case RISCV_REG_F12_64:
                    return riscv64::f12_64;
                case RISCV_REG_F13_32:
                    return riscv64::f13_32;
                case RISCV_REG_F13_64:
                    return riscv64::f13_64;
                case RISCV_REG_F14_32:
                    return riscv64::f14_32;
                case RISCV_REG_F14_64:
                    return riscv64::f14_64;
                case RISCV_REG_F15_32:
                    return riscv64::f15_32;
                case RISCV_REG_F15_64:
                    return riscv64::f15_64;
                case RISCV_REG_F16_32:
                    return riscv64::f16_32;
                case RISCV_REG_F16_64:
                    return riscv64::f16_64;
                case RISCV_REG_F17_32:
                    return riscv64::f17_32;
                case RISCV_REG_F17_64:
                    return riscv64::f17_64;
                case RISCV_REG_F18_32:
                    return riscv64::f18_32;
                case RISCV_REG_F18_64:
                    return riscv64::f18_64;
                case RISCV_REG_F19_32:
                    return riscv64::f19_32;
                case RISCV_REG_F19_64:
                    return riscv64::f19_64;
                case RISCV_REG_F20_32:
                    return riscv64::f20_32;
                case RISCV_REG_F20_64:
                    return riscv64::f20_64;
                case RISCV_REG_F21_32:
                    return riscv64::f21_32;
                case RISCV_REG_F21_64:
                    return riscv64::f21_64;
                case RISCV_REG_F22_32:
                    return riscv64::f22_32;
                case RISCV_REG_F22_64:
                    return riscv64::f22_64;
                case RISCV_REG_F23_32:
                    return riscv64::f23_32;
                case RISCV_REG_F23_64:
                    return riscv64::f23_64;
                case RISCV_REG_F24_32:
                    return riscv64::f24_32;
                case RISCV_REG_F24_64:
                    return riscv64::f24_64;
                case RISCV_REG_F25_32:
                    return riscv64::f25_32;
                case RISCV_REG_F25_64:
                    return riscv64::f25_64;
                case RISCV_REG_F26_32:
                    return riscv64::f26_32;
                case RISCV_REG_F26_64:
                    return riscv64::f26_64;
                case RISCV_REG_F27_32:
                    return riscv64::f27_32;
                case RISCV_REG_F27_64:
                    return riscv64::f27_64;
                case RISCV_REG_F28_32:
                    return riscv64::f28_32;
                case RISCV_REG_F28_64:
                    return riscv64::f28_64;
                case RISCV_REG_F29_32:
                    return riscv64::f29_32;
                case RISCV_REG_F29_64:
                    return riscv64::f29_64;
                case RISCV_REG_F30_32:
                    return riscv64::f30_32;
                case RISCV_REG_F30_64:
                    return riscv64::f30_64;
                case RISCV_REG_F31_32:
                    return riscv64::f31_32;
                case RISCV_REG_F31_64:
                    return riscv64::f31_64;
                default:
                    return InvalidReg;
            }
        }
    }
}

