#include "InstructionDecoder-Capstone.h"
#include "string"

#include <boost/assign/list_of.hpp>

namespace Dyninst {

namespace InstructionAPI {


/**************  Architecture independent functions  **********************/
dyn_tls bool InstructionDecoder_Capstone::handle_init = false;
dyn_tls Architecture InstructionDecoder_Capstone::current_arch = Arch_none;
dyn_tls std::map<std::string, std::string>* InstructionDecoder_Capstone::opcode_alias = nullptr;
dyn_tls dyn_hash_map<entryID, std::string>* InstructionDecoder_Capstone::opcode_str = nullptr;
dyn_tls cs_insn* InstructionDecoder_Capstone::capstone_ins_no_detail = nullptr;
dyn_tls cs_insn* InstructionDecoder_Capstone::capstone_ins_with_detail = nullptr;
dyn_tls csh InstructionDecoder_Capstone::handle_no_detail;
dyn_tls csh InstructionDecoder_Capstone::handle_with_detail;


InstructionDecoder_Capstone::InstructionDecoder_Capstone(Architecture a):
    InstructionDecoderImpl(a)
    {}


bool InstructionDecoder_Capstone::openCapstoneHandle() {
    if (handle_init && m_Arch == current_arch) return true;

    if (!handle_init) {
        // The first time of performing decoding
        initializeOpcodeData();
    }
    if (handle_init && m_Arch != current_arch) {
        // We now switch to decode instructions for a different architecture,
        // release previous decodign resources
        cs_free(capstone_ins_no_detail, 1);
        cs_free(capstone_ins_with_detail, 1);
        cs_close(&handle_no_detail);
        cs_close(&handle_with_detail);
    }    

    cs_err ret1, ret2;    
    handle_init = true;
    current_arch = m_Arch;

    switch (m_Arch) {
        case Arch_x86: 
            ret1 = cs_open(CS_ARCH_X86, CS_MODE_32, &handle_no_detail);
            ret2 = cs_open(CS_ARCH_X86, CS_MODE_32, &handle_with_detail);
            break;
        case Arch_x86_64:
            ret1 = cs_open(CS_ARCH_X86, CS_MODE_64, &handle_no_detail);
            ret2 = cs_open(CS_ARCH_X86, CS_MODE_64, &handle_with_detail);
            break;
        case Arch_ppc32:
            ret1 = cs_open(CS_ARCH_PPC, CS_MODE_32, &handle_no_detail);
            ret2 = cs_open(CS_ARCH_PPC, CS_MODE_32, &handle_with_detail);
            break;
        case Arch_ppc64:
            ret1 = cs_open(CS_ARCH_PPC, CS_MODE_64, &handle_no_detail);
            ret2 = cs_open(CS_ARCH_PPC, CS_MODE_64, &handle_with_detail);
            break;
        case Arch_aarch64:
            ret1 = cs_open(CS_ARCH_ARM64, CS_MODE_ARM, &handle_no_detail);
            ret2 = cs_open(CS_ARCH_ARM64, CS_MODE_ARM, &handle_with_detail);
            break;
        default:
            ret1 = ret2 = CS_ERR_ARCH;
            break;
    }

    if (ret1 == CS_ERR_OK && ret2 == CS_ERR_OK) {
        cs_option(handle_no_detail, CS_OPT_DETAIL, CS_OPT_OFF); 
        capstone_ins_no_detail = cs_malloc(handle_no_detail);
        cs_option(handle_with_detail, CS_OPT_DETAIL, CS_OPT_ON); 
        capstone_ins_with_detail = cs_malloc(handle_with_detail);
        return true;
    }
    return false;
}

void InstructionDecoder_Capstone::doDelayedDecode(const Instruction* insn) {
    if (!openCapstoneHandle()) {
        return;
    }
    const unsigned char* code = (const unsigned char*) insn->ptr();
    size_t codeSize = insn->size();
    uint64_t cap_addr = 0;
    if (cs_disasm_iter(handle_with_detail, &code, &codeSize, &cap_addr, capstone_ins_with_detail)) {
        if (m_Arch == Arch_x86 || m_Arch == Arch_x86_64)
            decodeOperands_x86(insn, capstone_ins_with_detail->detail);
        else if (m_Arch == Arch_ppc32 || m_Arch == Arch_ppc64)
            decodeOperands_ppc(insn, capstone_ins_with_detail->detail);
        else if (m_Arch == Arch_aarch64) 
            decodeOperands_aarch64(insn, capstone_ins_with_detail->detail); 
    }
}
bool InstructionDecoder_Capstone::decodeOperands(const Instruction*) {
    return false;
}

std::string InstructionDecoder_Capstone::mnemonicNormalization(std::string m) {
    if (opcode_alias->find(m) == opcode_alias->end())
        return m;
    else
        return (*opcode_alias)[m];
}

void InstructionDecoder_Capstone::decodeOpcode(InstructionDecoder::buffer& buf) {
    if (!openCapstoneHandle()) {
        m_Operation = Operation(e_No_Entry, "INVALID", m_Arch);
        return;
    }
    const unsigned char* code = buf.start;
    size_t codeSize = buf.end - buf.start;
    uint64_t cap_addr = 0;
    if (cs_disasm_iter(handle_no_detail, &code, &codeSize, &cap_addr, capstone_ins_no_detail)) {
        entryID e = opcodeTranslation(capstone_ins_no_detail->id);

        std::string opcodeString = "INVALID";
        auto strit = opcode_str->find(e);
        if (strit != opcode_str->end())
            opcodeString = strit->second;
        opcodeString = mnemonicNormalization(opcodeString);

        m_Operation = Operation(e, opcodeString, m_Arch);
        buf.start += capstone_ins_no_detail->size;
	} else
        m_Operation = Operation(e_No_Entry, "INVALID", m_Arch);
}

entryID InstructionDecoder_Capstone::opcodeTranslation(unsigned int cap_id) {
    if (m_Arch == Arch_x86 || m_Arch == Arch_x86_64)
        return opcodeTranslation_x86(cap_id);
    else if (m_Arch == Arch_ppc32 || m_Arch == Arch_ppc64)
        return opcodeTranslation_ppc(cap_id);
    else if (m_Arch == Arch_aarch64) 
        return opcodeTranslation_aarch64(cap_id);
    else {
        fprintf(stderr, "Unsupported architecture\n");
        return e_No_Entry; 
    }
}

Result_Type InstructionDecoder_Capstone::operandSizeTranslation(uint8_t cap_size) {
    switch (cap_size) {
        case 1:  return u8;
        case 2:  return u16;
        case 4:  return u32;
        case 8:  return u64;
        case 10: return m80;
        case 12: return m96;
        case 14: return m14;
        case 16: return dbl128; 
        case 24: return m192;
        case 28: return m224;
        case 32: return m256;
        case 48: return m384;
        case 64: return m512;
        default:
            return invalid_type;
    }
}

bool InstructionDecoder_Capstone::checkCapstoneGroup(cs_detail *d, uint8_t g) {
    for (uint8_t i = 0; i < d->groups_count; ++i)
        if (d->groups[i] == g)
            return true;
    return false;
}

void InstructionDecoder_Capstone::setMode(bool) {
    // Unused
    return;
}

Result_Type InstructionDecoder_Capstone::makeSizeType(unsigned int) {
    // Unused
    return u32;
}


void InstructionDecoder_Capstone::initializeOpcodeData() {
    
    opcode_alias = new std::map<std::string, std::string>();
    opcode_alias->emplace("ja", "jnbe");
    opcode_alias->emplace("jae", "jnb");
    opcode_alias->emplace("je", "jz");
    opcode_alias->emplace("jne", "jnz");
    opcode_alias->emplace("jg", "jnle");
    opcode_alias->emplace("jge", "jnl");    

    opcode_str = new dyn_hash_map<entryID, std::string>();
    opcode_str->reserve(2000);
    opcode_str->emplace(e_aaa,"aaa");
    opcode_str->emplace(e_aad,"aad");
    opcode_str->emplace(e_aam,"aam");
    opcode_str->emplace(e_aas,"aas");
    opcode_str->emplace(e_fabs,"fabs");
    opcode_str->emplace(e_adc,"adc");
    opcode_str->emplace(e_adcx,"adcx");
    opcode_str->emplace(e_add,"add");
    opcode_str->emplace(e_addpd,"addpd");
    opcode_str->emplace(e_addps,"addps");
    opcode_str->emplace(e_addsd,"addsd");
    opcode_str->emplace(e_addss,"addss");
    opcode_str->emplace(e_addsubpd,"addsubpd");
    opcode_str->emplace(e_addsubps,"addsubps");
    opcode_str->emplace(e_fadd,"fadd");
    opcode_str->emplace(e_fiadd,"fiadd");
    opcode_str->emplace(e_adox,"adox");
    opcode_str->emplace(e_aesdeclast,"aesdeclast");
    opcode_str->emplace(e_aesdec,"aesdec");
    opcode_str->emplace(e_aesenclast,"aesenclast");
    opcode_str->emplace(e_aesenc,"aesenc");
    opcode_str->emplace(e_aesimc,"aesimc");
    opcode_str->emplace(e_aeskeygenassist,"aeskeygenassist");
    opcode_str->emplace(e_and,"and");
    opcode_str->emplace(e_andn,"andn");
    opcode_str->emplace(e_andnpd,"andnpd");
    opcode_str->emplace(e_andnps,"andnps");
    opcode_str->emplace(e_andpd,"andpd");
    opcode_str->emplace(e_andps,"andps");
    opcode_str->emplace(e_arpl,"arpl");
    opcode_str->emplace(e_bextr,"bextr");
    opcode_str->emplace(e_blcfill,"blcfill");
    opcode_str->emplace(e_blci,"blci");
    opcode_str->emplace(e_blcic,"blcic");
    opcode_str->emplace(e_blcmsk,"blcmsk");
    opcode_str->emplace(e_blcs,"blcs");
    opcode_str->emplace(e_blendpd,"blendpd");
    opcode_str->emplace(e_blendps,"blendps");
    opcode_str->emplace(e_blendvpd,"blendvpd");
    opcode_str->emplace(e_blendvps,"blendvps");
    opcode_str->emplace(e_blsfill,"blsfill");
    opcode_str->emplace(e_blsi,"blsi");
    opcode_str->emplace(e_blsic,"blsic");
    opcode_str->emplace(e_blsmsk,"blsmsk");
    opcode_str->emplace(e_blsr,"blsr");
    opcode_str->emplace(e_bndcl,"bndcl");
    opcode_str->emplace(e_bndcn,"bndcn");
    opcode_str->emplace(e_bndcu,"bndcu");
    opcode_str->emplace(e_bndldx,"bndldx");
    opcode_str->emplace(e_bndmk,"bndmk");
    opcode_str->emplace(e_bndmov,"bndmov");
    opcode_str->emplace(e_bndstx,"bndstx");
    opcode_str->emplace(e_bound,"bound");
    opcode_str->emplace(e_bsf,"bsf");
    opcode_str->emplace(e_bsr,"bsr");
    opcode_str->emplace(e_bswap,"bswap");
    opcode_str->emplace(e_bt,"bt");
    opcode_str->emplace(e_btc,"btc");
    opcode_str->emplace(e_btr,"btr");
    opcode_str->emplace(e_bts,"bts");
    opcode_str->emplace(e_bzhi,"bzhi");
    opcode_str->emplace(e_call,"call");
    opcode_str->emplace(e_cbw,"cbw");
    opcode_str->emplace(e_cdq,"cdq");
    opcode_str->emplace(e_cdqe,"cdqe");
    opcode_str->emplace(e_fchs,"fchs");
    opcode_str->emplace(e_clac,"clac");
    opcode_str->emplace(e_clc,"clc");
    opcode_str->emplace(e_cld,"cld");
    opcode_str->emplace(e_cldemote,"cldemote");
    opcode_str->emplace(e_clflush,"clflush");
    opcode_str->emplace(e_clflushopt,"clflushopt");
    opcode_str->emplace(e_clgi,"clgi");
    opcode_str->emplace(e_cli,"cli");
    opcode_str->emplace(e_clrssbsy,"clrssbsy");
    opcode_str->emplace(e_clts,"clts");
    opcode_str->emplace(e_clwb,"clwb");
    opcode_str->emplace(e_clzero,"clzero");
    opcode_str->emplace(e_cmc,"cmc");
    opcode_str->emplace(e_cmova,"cmova");
    opcode_str->emplace(e_cmovae,"cmovae");
    opcode_str->emplace(e_cmovb,"cmovb");
    opcode_str->emplace(e_cmovbe,"cmovbe");
    opcode_str->emplace(e_fcmovbe,"fcmovbe");
    opcode_str->emplace(e_fcmovb,"fcmovb");
    opcode_str->emplace(e_cmove,"cmove");
    opcode_str->emplace(e_fcmove,"fcmove");
    opcode_str->emplace(e_cmovg,"cmovg");
    opcode_str->emplace(e_cmovge,"cmovge");
    opcode_str->emplace(e_cmovl,"cmovl");
    opcode_str->emplace(e_cmovle,"cmovle");
    opcode_str->emplace(e_fcmovnbe,"fcmovnbe");
    opcode_str->emplace(e_fcmovnb,"fcmovnb");
    opcode_str->emplace(e_cmovne,"cmovne");
    opcode_str->emplace(e_fcmovne,"fcmovne");
    opcode_str->emplace(e_cmovno,"cmovno");
    opcode_str->emplace(e_cmovnp,"cmovnp");
    opcode_str->emplace(e_fcmovnu,"fcmovnu");
    opcode_str->emplace(e_fcmovnp,"fcmovnp");
    opcode_str->emplace(e_cmovns,"cmovns");
    opcode_str->emplace(e_cmovo,"cmovo");
    opcode_str->emplace(e_cmovp,"cmovp");
    opcode_str->emplace(e_fcmovu,"fcmovu");
    opcode_str->emplace(e_cmovs,"cmovs");
    opcode_str->emplace(e_cmp,"cmp");
    opcode_str->emplace(e_cmppd,"cmppd");
    opcode_str->emplace(e_cmpps,"cmpps");
    opcode_str->emplace(e_cmpsb,"cmpsb");
    opcode_str->emplace(e_cmpsd,"cmpsd");
    opcode_str->emplace(e_cmpsq,"cmpsq");
    opcode_str->emplace(e_cmpss,"cmpss");
    opcode_str->emplace(e_cmpsw,"cmpsw");
    opcode_str->emplace(e_cmpxchg16b,"cmpxchg16b");
    opcode_str->emplace(e_cmpxchg,"cmpxchg");
    opcode_str->emplace(e_cmpxchg8b,"cmpxchg8b");
    opcode_str->emplace(e_comisd,"comisd");
    opcode_str->emplace(e_comiss,"comiss");
    opcode_str->emplace(e_fcomp,"fcomp");
    opcode_str->emplace(e_fcompi,"fcompi");
    opcode_str->emplace(e_fcomi,"fcomi");
    opcode_str->emplace(e_fcom,"fcom");
    opcode_str->emplace(e_fcos,"fcos");
    opcode_str->emplace(e_cpuid,"cpuid");
    opcode_str->emplace(e_cqo,"cqo");
    opcode_str->emplace(e_crc32,"crc32");
    opcode_str->emplace(e_cvtdq2pd,"cvtdq2pd");
    opcode_str->emplace(e_cvtdq2ps,"cvtdq2ps");
    opcode_str->emplace(e_cvtpd2dq,"cvtpd2dq");
    opcode_str->emplace(e_cvtpd2ps,"cvtpd2ps");
    opcode_str->emplace(e_cvtps2dq,"cvtps2dq");
    opcode_str->emplace(e_cvtps2pd,"cvtps2pd");
    opcode_str->emplace(e_cvtsd2si,"cvtsd2si");
    opcode_str->emplace(e_cvtsd2ss,"cvtsd2ss");
    opcode_str->emplace(e_cvtsi2sd,"cvtsi2sd");
    opcode_str->emplace(e_cvtsi2ss,"cvtsi2ss");
    opcode_str->emplace(e_cvtss2sd,"cvtss2sd");
    opcode_str->emplace(e_cvtss2si,"cvtss2si");
    opcode_str->emplace(e_cvttpd2dq,"cvttpd2dq");
    opcode_str->emplace(e_cvttps2dq,"cvttps2dq");
    opcode_str->emplace(e_cvttsd2si,"cvttsd2si");
    opcode_str->emplace(e_cvttss2si,"cvttss2si");
    opcode_str->emplace(e_cwd,"cwd");
    opcode_str->emplace(e_cwde,"cwde");
    opcode_str->emplace(e_daa,"daa");
    opcode_str->emplace(e_das,"das");
    opcode_str->emplace(e_data16,"data16");
    opcode_str->emplace(e_dec,"dec");
    opcode_str->emplace(e_div,"div");
    opcode_str->emplace(e_divpd,"divpd");
    opcode_str->emplace(e_divps,"divps");
    opcode_str->emplace(e_fdivr,"fdivr");
    opcode_str->emplace(e_fidivr,"fidivr");
    opcode_str->emplace(e_fdivrp,"fdivrp");
    opcode_str->emplace(e_divsd,"divsd");
    opcode_str->emplace(e_divss,"divss");
    opcode_str->emplace(e_fdiv,"fdiv");
    opcode_str->emplace(e_fidiv,"fidiv");
    opcode_str->emplace(e_fdivp,"fdivp");
    opcode_str->emplace(e_dppd,"dppd");
    opcode_str->emplace(e_dpps,"dpps");
    opcode_str->emplace(e_encls,"encls");
    opcode_str->emplace(e_enclu,"enclu");
    opcode_str->emplace(e_enclv,"enclv");
    opcode_str->emplace(e_endbr32,"endbr32");
    opcode_str->emplace(e_endbr64,"endbr64");
    opcode_str->emplace(e_enter,"enter");
    opcode_str->emplace(e_extractps,"extractps");
    opcode_str->emplace(e_extrq,"extrq");
    opcode_str->emplace(e_f2xm1,"f2xm1");
    opcode_str->emplace(e_lcall,"lcall");
    opcode_str->emplace(e_ljmp,"ljmp");
    opcode_str->emplace(e_jmp,"jmp");
    opcode_str->emplace(e_fbld,"fbld");
    opcode_str->emplace(e_fbstp,"fbstp");
    opcode_str->emplace(e_fcompp,"fcompp");
    opcode_str->emplace(e_fdecstp,"fdecstp");
    opcode_str->emplace(e_nop,"nop");
    opcode_str->emplace(e_femms,"femms");
    opcode_str->emplace(e_nop,"nop");
    opcode_str->emplace(e_ffree,"ffree");
    opcode_str->emplace(e_ffreep,"ffreep");
    opcode_str->emplace(e_ficom,"ficom");
    opcode_str->emplace(e_ficomp,"ficomp");
    opcode_str->emplace(e_fincstp,"fincstp");
    opcode_str->emplace(e_fldcw,"fldcw");
    opcode_str->emplace(e_fldenv,"fldenv");
    opcode_str->emplace(e_fldl2e,"fldl2e");
    opcode_str->emplace(e_fldl2t,"fldl2t");
    opcode_str->emplace(e_fldlg2,"fldlg2");
    opcode_str->emplace(e_fldln2,"fldln2");
    opcode_str->emplace(e_fldpi,"fldpi");
    opcode_str->emplace(e_fnclex,"fnclex");
    opcode_str->emplace(e_fninit,"fninit");
    opcode_str->emplace(e_fnop,"fnop");
    opcode_str->emplace(e_fnstcw,"fnstcw");
    opcode_str->emplace(e_fnstsw,"fnstsw");
    opcode_str->emplace(e_fpatan,"fpatan");
    opcode_str->emplace(e_fstpnce,"fstpnce");
    opcode_str->emplace(e_fprem,"fprem");
    opcode_str->emplace(e_fprem1,"fprem1");
    opcode_str->emplace(e_fptan,"fptan");
    opcode_str->emplace(e_frndint,"frndint");
    opcode_str->emplace(e_frstor,"frstor");
    opcode_str->emplace(e_fnsave,"fnsave");
    opcode_str->emplace(e_fscale,"fscale");
    opcode_str->emplace(e_fsetpm,"fsetpm");
    opcode_str->emplace(e_fsincos,"fsincos");
    opcode_str->emplace(e_fnstenv,"fnstenv");
    opcode_str->emplace(e_fxam,"fxam");
    opcode_str->emplace(e_fxrstor,"fxrstor");
    opcode_str->emplace(e_fxrstor64,"fxrstor64");
    opcode_str->emplace(e_fxsave,"fxsave");
    opcode_str->emplace(e_fxsave64,"fxsave64");
    opcode_str->emplace(e_fxtract,"fxtract");
    opcode_str->emplace(e_fyl2x,"fyl2x");
    opcode_str->emplace(e_fyl2xp1,"fyl2xp1");
    opcode_str->emplace(e_getsec,"getsec");
    opcode_str->emplace(e_gf2p8affineinvqb,"gf2p8affineinvqb");
    opcode_str->emplace(e_gf2p8affineqb,"gf2p8affineqb");
    opcode_str->emplace(e_gf2p8mulb,"gf2p8mulb");
    opcode_str->emplace(e_haddpd,"haddpd");
    opcode_str->emplace(e_haddps,"haddps");
    opcode_str->emplace(e_hlt,"hlt");
    opcode_str->emplace(e_hsubpd,"hsubpd");
    opcode_str->emplace(e_hsubps,"hsubps");
    opcode_str->emplace(e_idiv,"idiv");
    opcode_str->emplace(e_fild,"fild");
    opcode_str->emplace(e_imul,"imul");
    opcode_str->emplace(e_in,"in");
    opcode_str->emplace(e_inc,"inc");
    opcode_str->emplace(e_incsspd,"incsspd");
    opcode_str->emplace(e_incsspq,"incsspq");
    opcode_str->emplace(e_insb,"insb");
    opcode_str->emplace(e_insertps,"insertps");
    opcode_str->emplace(e_insertq,"insertq");
    opcode_str->emplace(e_insd,"insd");
    opcode_str->emplace(e_insw,"insw");
    opcode_str->emplace(e_int,"int");
    opcode_str->emplace(e_int1,"int1");
    opcode_str->emplace(e_int3,"int3");
    opcode_str->emplace(e_into,"into");
    opcode_str->emplace(e_invd,"invd");
    opcode_str->emplace(e_invept,"invept");
    opcode_str->emplace(e_invlpg,"invlpg");
    opcode_str->emplace(e_invlpga,"invlpga");
    opcode_str->emplace(e_invpcid,"invpcid");
    opcode_str->emplace(e_invvpid,"invvpid");
    opcode_str->emplace(e_iret,"iret");
    opcode_str->emplace(e_iretd,"iretd");
    opcode_str->emplace(e_iretq,"iretq");
    opcode_str->emplace(e_fisttp,"fisttp");
    opcode_str->emplace(e_fist,"fist");
    opcode_str->emplace(e_fistp,"fistp");
    opcode_str->emplace(e_jnb,"jnb");
    opcode_str->emplace(e_jnbe,"jnbe");
    opcode_str->emplace(e_jbe,"jbe");
    opcode_str->emplace(e_jb,"jb");
    opcode_str->emplace(e_jcxz,"jcxz");
    opcode_str->emplace(e_jecxz,"jecxz");
    opcode_str->emplace(e_jz,"jz");
    opcode_str->emplace(e_jnl,"jnl");
    opcode_str->emplace(e_jnle,"jnle");
    opcode_str->emplace(e_jle,"jle");
    opcode_str->emplace(e_jl,"jl");
    opcode_str->emplace(e_jnz,"jnz");
    opcode_str->emplace(e_jno,"jno");
    opcode_str->emplace(e_jnp,"jnp");
    opcode_str->emplace(e_jns,"jns");
    opcode_str->emplace(e_jo,"jo");
    opcode_str->emplace(e_jp,"jp");
    opcode_str->emplace(e_jrcxz,"jrcxz");
    opcode_str->emplace(e_js,"js");
    opcode_str->emplace(e_kaddb,"kaddb");
    opcode_str->emplace(e_kaddd,"kaddd");
    opcode_str->emplace(e_kaddq,"kaddq");
    opcode_str->emplace(e_kaddw,"kaddw");
    opcode_str->emplace(e_kandb,"kandb");
    opcode_str->emplace(e_kandd,"kandd");
    opcode_str->emplace(e_kandnb,"kandnb");
    opcode_str->emplace(e_kandnd,"kandnd");
    opcode_str->emplace(e_kandnq,"kandnq");
    opcode_str->emplace(e_kandnw,"kandnw");
    opcode_str->emplace(e_kandq,"kandq");
    opcode_str->emplace(e_kandw,"kandw");
    opcode_str->emplace(e_kmovb,"kmovb");
    opcode_str->emplace(e_kmovd,"kmovd");
    opcode_str->emplace(e_kmovq,"kmovq");
    opcode_str->emplace(e_kmovw,"kmovw");
    opcode_str->emplace(e_knotb,"knotb");
    opcode_str->emplace(e_knotd,"knotd");
    opcode_str->emplace(e_knotq,"knotq");
    opcode_str->emplace(e_knotw,"knotw");
    opcode_str->emplace(e_korb,"korb");
    opcode_str->emplace(e_kord,"kord");
    opcode_str->emplace(e_korq,"korq");
    opcode_str->emplace(e_kortestb,"kortestb");
    opcode_str->emplace(e_kortestd,"kortestd");
    opcode_str->emplace(e_kortestq,"kortestq");
    opcode_str->emplace(e_kortestw,"kortestw");
    opcode_str->emplace(e_korw,"korw");
    opcode_str->emplace(e_kshiftlb,"kshiftlb");
    opcode_str->emplace(e_kshiftld,"kshiftld");
    opcode_str->emplace(e_kshiftlq,"kshiftlq");
    opcode_str->emplace(e_kshiftlw,"kshiftlw");
    opcode_str->emplace(e_kshiftrb,"kshiftrb");
    opcode_str->emplace(e_kshiftrd,"kshiftrd");
    opcode_str->emplace(e_kshiftrq,"kshiftrq");
    opcode_str->emplace(e_kshiftrw,"kshiftrw");
    opcode_str->emplace(e_ktestb,"ktestb");
    opcode_str->emplace(e_ktestd,"ktestd");
    opcode_str->emplace(e_ktestq,"ktestq");
    opcode_str->emplace(e_ktestw,"ktestw");
    opcode_str->emplace(e_kunpckbw,"kunpckbw");
    opcode_str->emplace(e_kunpckdq,"kunpckdq");
    opcode_str->emplace(e_kunpckwd,"kunpckwd");
    opcode_str->emplace(e_kxnorb,"kxnorb");
    opcode_str->emplace(e_kxnord,"kxnord");
    opcode_str->emplace(e_kxnorq,"kxnorq");
    opcode_str->emplace(e_kxnorw,"kxnorw");
    opcode_str->emplace(e_kxorb,"kxorb");
    opcode_str->emplace(e_kxord,"kxord");
    opcode_str->emplace(e_kxorq,"kxorq");
    opcode_str->emplace(e_kxorw,"kxorw");
    opcode_str->emplace(e_lahf,"lahf");
    opcode_str->emplace(e_lar,"lar");
    opcode_str->emplace(e_lddqu,"lddqu");
    opcode_str->emplace(e_ldmxcsr,"ldmxcsr");
    opcode_str->emplace(e_lds,"lds");
    opcode_str->emplace(e_fldz,"fldz");
    opcode_str->emplace(e_fld1,"fld1");
    opcode_str->emplace(e_fld,"fld");
    opcode_str->emplace(e_lea,"lea");
    opcode_str->emplace(e_leave,"leave");
    opcode_str->emplace(e_les,"les");
    opcode_str->emplace(e_lfence,"lfence");
    opcode_str->emplace(e_lfs,"lfs");
    opcode_str->emplace(e_lgdt,"lgdt");
    opcode_str->emplace(e_lgs,"lgs");
    opcode_str->emplace(e_lidt,"lidt");
    opcode_str->emplace(e_lldt,"lldt");
    opcode_str->emplace(e_llwpcb,"llwpcb");
    opcode_str->emplace(e_lmsw,"lmsw");
    opcode_str->emplace(e_lock,"lock");
    opcode_str->emplace(e_lodsb,"lodsb");
    opcode_str->emplace(e_lodsd,"lodsd");
    opcode_str->emplace(e_lodsq,"lodsq");
    opcode_str->emplace(e_lodsw,"lodsw");
    opcode_str->emplace(e_loop,"loop");
    opcode_str->emplace(e_loope,"loope");
    opcode_str->emplace(e_loopne,"loopne");
    opcode_str->emplace(e_retf,"retf");
    opcode_str->emplace(e_retfq,"retfq");
    opcode_str->emplace(e_lsl,"lsl");
    opcode_str->emplace(e_lss,"lss");
    opcode_str->emplace(e_ltr,"ltr");
    opcode_str->emplace(e_lwpins,"lwpins");
    opcode_str->emplace(e_lwpval,"lwpval");
    opcode_str->emplace(e_lzcnt,"lzcnt");
    opcode_str->emplace(e_maskmovdqu,"maskmovdqu");
    opcode_str->emplace(e_maxpd,"maxpd");
    opcode_str->emplace(e_maxps,"maxps");
    opcode_str->emplace(e_maxsd,"maxsd");
    opcode_str->emplace(e_maxss,"maxss");
    opcode_str->emplace(e_mfence,"mfence");
    opcode_str->emplace(e_minpd,"minpd");
    opcode_str->emplace(e_minps,"minps");
    opcode_str->emplace(e_minsd,"minsd");
    opcode_str->emplace(e_minss,"minss");
    opcode_str->emplace(e_cvtpd2pi,"cvtpd2pi");
    opcode_str->emplace(e_cvtpi2pd,"cvtpi2pd");
    opcode_str->emplace(e_cvtpi2ps,"cvtpi2ps");
    opcode_str->emplace(e_cvtps2pi,"cvtps2pi");
    opcode_str->emplace(e_cvttpd2pi,"cvttpd2pi");
    opcode_str->emplace(e_cvttps2pi,"cvttps2pi");
    opcode_str->emplace(e_emms,"emms");
    opcode_str->emplace(e_maskmovq,"maskmovq");
    opcode_str->emplace(e_movd,"movd");
    opcode_str->emplace(e_movq,"movq");
    opcode_str->emplace(e_movdq2q,"movdq2q");
    opcode_str->emplace(e_movntq,"movntq");
    opcode_str->emplace(e_movq2dq,"movq2dq");
    opcode_str->emplace(e_pabsb,"pabsb");
    opcode_str->emplace(e_pabsd,"pabsd");
    opcode_str->emplace(e_pabsw,"pabsw");
    opcode_str->emplace(e_packssdw,"packssdw");
    opcode_str->emplace(e_packsswb,"packsswb");
    opcode_str->emplace(e_packuswb,"packuswb");
    opcode_str->emplace(e_paddb,"paddb");
    opcode_str->emplace(e_paddd,"paddd");
    opcode_str->emplace(e_paddq,"paddq");
    opcode_str->emplace(e_paddsb,"paddsb");
    opcode_str->emplace(e_paddsw,"paddsw");
    opcode_str->emplace(e_paddusb,"paddusb");
    opcode_str->emplace(e_paddusw,"paddusw");
    opcode_str->emplace(e_paddw,"paddw");
    opcode_str->emplace(e_palignr,"palignr");
    opcode_str->emplace(e_pandn,"pandn");
    opcode_str->emplace(e_pand,"pand");
    opcode_str->emplace(e_pavgb,"pavgb");
    opcode_str->emplace(e_pavgw,"pavgw");
    opcode_str->emplace(e_pcmpeqb,"pcmpeqb");
    opcode_str->emplace(e_pcmpeqd,"pcmpeqd");
    opcode_str->emplace(e_pcmpeqw,"pcmpeqw");
    opcode_str->emplace(e_pcmpgtb,"pcmpgtb");
    opcode_str->emplace(e_pcmpgtd,"pcmpgtd");
    opcode_str->emplace(e_pcmpgtw,"pcmpgtw");
    opcode_str->emplace(e_pextrw,"pextrw");
    opcode_str->emplace(e_phaddd,"phaddd");
    opcode_str->emplace(e_phaddsw,"phaddsw");
    opcode_str->emplace(e_phaddw,"phaddw");
    opcode_str->emplace(e_phsubd,"phsubd");
    opcode_str->emplace(e_phsubsw,"phsubsw");
    opcode_str->emplace(e_phsubw,"phsubw");
    opcode_str->emplace(e_pinsrw,"pinsrw");
    opcode_str->emplace(e_pmaddubsw,"pmaddubsw");
    opcode_str->emplace(e_pmaddwd,"pmaddwd");
    opcode_str->emplace(e_pmaxsw,"pmaxsw");
    opcode_str->emplace(e_pmaxub,"pmaxub");
    opcode_str->emplace(e_pminsw,"pminsw");
    opcode_str->emplace(e_pminub,"pminub");
    opcode_str->emplace(e_pmovmskb,"pmovmskb");
    opcode_str->emplace(e_pmulhrsw,"pmulhrsw");
    opcode_str->emplace(e_pmulhuw,"pmulhuw");
    opcode_str->emplace(e_pmulhw,"pmulhw");
    opcode_str->emplace(e_pmullw,"pmullw");
    opcode_str->emplace(e_pmuludq,"pmuludq");
    opcode_str->emplace(e_por,"por");
    opcode_str->emplace(e_psadbw,"psadbw");
    opcode_str->emplace(e_pshufb,"pshufb");
    opcode_str->emplace(e_pshufw,"pshufw");
    opcode_str->emplace(e_psignb,"psignb");
    opcode_str->emplace(e_psignd,"psignd");
    opcode_str->emplace(e_psignw,"psignw");
    opcode_str->emplace(e_pslld,"pslld");
    opcode_str->emplace(e_psllq,"psllq");
    opcode_str->emplace(e_psllw,"psllw");
    opcode_str->emplace(e_psrad,"psrad");
    opcode_str->emplace(e_psraw,"psraw");
    opcode_str->emplace(e_psrld,"psrld");
    opcode_str->emplace(e_psrlq,"psrlq");
    opcode_str->emplace(e_psrlw,"psrlw");
    opcode_str->emplace(e_psubb,"psubb");
    opcode_str->emplace(e_psubd,"psubd");
    opcode_str->emplace(e_psubq,"psubq");
    opcode_str->emplace(e_psubsb,"psubsb");
    opcode_str->emplace(e_psubsw,"psubsw");
    opcode_str->emplace(e_psubusb,"psubusb");
    opcode_str->emplace(e_psubusw,"psubusw");
    opcode_str->emplace(e_psubw,"psubw");
    opcode_str->emplace(e_punpckhbw,"punpckhbw");
    opcode_str->emplace(e_punpckhdq,"punpckhdq");
    opcode_str->emplace(e_punpckhwd,"punpckhwd");
    opcode_str->emplace(e_punpcklbw,"punpcklbw");
    opcode_str->emplace(e_punpckldq,"punpckldq");
    opcode_str->emplace(e_punpcklwd,"punpcklwd");
    opcode_str->emplace(e_pxor,"pxor");
    opcode_str->emplace(e_monitorx,"monitorx");
    opcode_str->emplace(e_monitor,"monitor");
    opcode_str->emplace(e_montmul,"montmul");
    opcode_str->emplace(e_mov,"mov");
    opcode_str->emplace(e_movabs,"movabs");
    opcode_str->emplace(e_movapd,"movapd");
    opcode_str->emplace(e_movaps,"movaps");
    opcode_str->emplace(e_movbe,"movbe");
    opcode_str->emplace(e_movddup,"movddup");
    opcode_str->emplace(e_movdir64b,"movdir64b");
    opcode_str->emplace(e_movdiri,"movdiri");
    opcode_str->emplace(e_movdqa,"movdqa");
    opcode_str->emplace(e_movdqu,"movdqu");
    opcode_str->emplace(e_movhlps,"movhlps");
    opcode_str->emplace(e_movhpd,"movhpd");
    opcode_str->emplace(e_movhps,"movhps");
    opcode_str->emplace(e_movlhps,"movlhps");
    opcode_str->emplace(e_movlpd,"movlpd");
    opcode_str->emplace(e_movlps,"movlps");
    opcode_str->emplace(e_movmskpd,"movmskpd");
    opcode_str->emplace(e_movmskps,"movmskps");
    opcode_str->emplace(e_movntdqa,"movntdqa");
    opcode_str->emplace(e_movntdq,"movntdq");
    opcode_str->emplace(e_movnti,"movnti");
    opcode_str->emplace(e_movntpd,"movntpd");
    opcode_str->emplace(e_movntps,"movntps");
    opcode_str->emplace(e_movntsd,"movntsd");
    opcode_str->emplace(e_movntss,"movntss");
    opcode_str->emplace(e_movsb,"movsb");
    opcode_str->emplace(e_movsd,"movsd");
    opcode_str->emplace(e_movshdup,"movshdup");
    opcode_str->emplace(e_movsldup,"movsldup");
    opcode_str->emplace(e_movsq,"movsq");
    opcode_str->emplace(e_movss,"movss");
    opcode_str->emplace(e_movsw,"movsw");
    opcode_str->emplace(e_movsx,"movsx");
    opcode_str->emplace(e_movsxd,"movsxd");
    opcode_str->emplace(e_movupd,"movupd");
    opcode_str->emplace(e_movups,"movups");
    opcode_str->emplace(e_movzx,"movzx");
    opcode_str->emplace(e_mpsadbw,"mpsadbw");
    opcode_str->emplace(e_mul,"mul");
    opcode_str->emplace(e_mulpd,"mulpd");
    opcode_str->emplace(e_mulps,"mulps");
    opcode_str->emplace(e_mulsd,"mulsd");
    opcode_str->emplace(e_mulss,"mulss");
    opcode_str->emplace(e_mulx,"mulx");
    opcode_str->emplace(e_fmul,"fmul");
    opcode_str->emplace(e_fimul,"fimul");
    opcode_str->emplace(e_fmulp,"fmulp");
    opcode_str->emplace(e_mwaitx,"mwaitx");
    opcode_str->emplace(e_mwait,"mwait");
    opcode_str->emplace(e_neg,"neg");
    opcode_str->emplace(e_nop,"nop");
    opcode_str->emplace(e_not,"not");
    opcode_str->emplace(e_or,"or");
    opcode_str->emplace(e_orpd,"orpd");
    opcode_str->emplace(e_orps,"orps");
    opcode_str->emplace(e_out,"out");
    opcode_str->emplace(e_outsb,"outsb");
    opcode_str->emplace(e_outsd,"outsd");
    opcode_str->emplace(e_outsw,"outsw");
    opcode_str->emplace(e_packusdw,"packusdw");
    opcode_str->emplace(e_pause,"pause");
    opcode_str->emplace(e_pavgusb,"pavgusb");
    opcode_str->emplace(e_pblendvb,"pblendvb");
    opcode_str->emplace(e_pblendw,"pblendw");
    opcode_str->emplace(e_pclmulqdq,"pclmulqdq");
    opcode_str->emplace(e_pcmpeqq,"pcmpeqq");
    opcode_str->emplace(e_pcmpestri,"pcmpestri");
    opcode_str->emplace(e_pcmpestrm,"pcmpestrm");
    opcode_str->emplace(e_pcmpgtq,"pcmpgtq");
    opcode_str->emplace(e_pcmpistri,"pcmpistri");
    opcode_str->emplace(e_pcmpistrm,"pcmpistrm");
    opcode_str->emplace(e_pconfig,"pconfig");
    opcode_str->emplace(e_pdep,"pdep");
    opcode_str->emplace(e_pext,"pext");
    opcode_str->emplace(e_pextrb,"pextrb");
    opcode_str->emplace(e_pextrd,"pextrd");
    opcode_str->emplace(e_pextrq,"pextrq");
    opcode_str->emplace(e_pf2id,"pf2id");
    opcode_str->emplace(e_pf2iw,"pf2iw");
    opcode_str->emplace(e_pfacc,"pfacc");
    opcode_str->emplace(e_pfadd,"pfadd");
    opcode_str->emplace(e_pfcmpeq,"pfcmpeq");
    opcode_str->emplace(e_pfcmpge,"pfcmpge");
    opcode_str->emplace(e_pfcmpgt,"pfcmpgt");
    opcode_str->emplace(e_pfmax,"pfmax");
    opcode_str->emplace(e_pfmin,"pfmin");
    opcode_str->emplace(e_pfmul,"pfmul");
    opcode_str->emplace(e_pfnacc,"pfnacc");
    opcode_str->emplace(e_pfpnacc,"pfpnacc");
    opcode_str->emplace(e_pfrcpit1,"pfrcpit1");
    opcode_str->emplace(e_pfrcpit2,"pfrcpit2");
    opcode_str->emplace(e_pfrcp,"pfrcp");
    opcode_str->emplace(e_pfrsqit1,"pfrsqit1");
    opcode_str->emplace(e_pfrsqrt,"pfrsqrt");
    opcode_str->emplace(e_pfsubr,"pfsubr");
    opcode_str->emplace(e_pfsub,"pfsub");
    opcode_str->emplace(e_phminposuw,"phminposuw");
    opcode_str->emplace(e_pi2fd,"pi2fd");
    opcode_str->emplace(e_pi2fw,"pi2fw");
    opcode_str->emplace(e_pinsrb,"pinsrb");
    opcode_str->emplace(e_pinsrd,"pinsrd");
    opcode_str->emplace(e_pinsrq,"pinsrq");
    opcode_str->emplace(e_pmaxsb,"pmaxsb");
    opcode_str->emplace(e_pmaxsd,"pmaxsd");
    opcode_str->emplace(e_pmaxud,"pmaxud");
    opcode_str->emplace(e_pmaxuw,"pmaxuw");
    opcode_str->emplace(e_pminsb,"pminsb");
    opcode_str->emplace(e_pminsd,"pminsd");
    opcode_str->emplace(e_pminud,"pminud");
    opcode_str->emplace(e_pminuw,"pminuw");
    opcode_str->emplace(e_pmovsxbd,"pmovsxbd");
    opcode_str->emplace(e_pmovsxbq,"pmovsxbq");
    opcode_str->emplace(e_pmovsxbw,"pmovsxbw");
    opcode_str->emplace(e_pmovsxdq,"pmovsxdq");
    opcode_str->emplace(e_pmovsxwd,"pmovsxwd");
    opcode_str->emplace(e_pmovsxwq,"pmovsxwq");
    opcode_str->emplace(e_pmovzxbd,"pmovzxbd");
    opcode_str->emplace(e_pmovzxbq,"pmovzxbq");
    opcode_str->emplace(e_pmovzxbw,"pmovzxbw");
    opcode_str->emplace(e_pmovzxdq,"pmovzxdq");
    opcode_str->emplace(e_pmovzxwd,"pmovzxwd");
    opcode_str->emplace(e_pmovzxwq,"pmovzxwq");
    opcode_str->emplace(e_pmuldq,"pmuldq");
    opcode_str->emplace(e_pmulhrw,"pmulhrw");
    opcode_str->emplace(e_pmulld,"pmulld");
    opcode_str->emplace(e_pop,"pop");
    opcode_str->emplace(e_popaw,"popaw");
    opcode_str->emplace(e_popal,"popal");
    opcode_str->emplace(e_popcnt,"popcnt");
    opcode_str->emplace(e_popf,"popf");
    opcode_str->emplace(e_popfd,"popfd");
    opcode_str->emplace(e_popfq,"popfq");
    opcode_str->emplace(e_prefetch,"prefetch");
    opcode_str->emplace(e_prefetchnta,"prefetchnta");
    opcode_str->emplace(e_prefetcht0,"prefetcht0");
    opcode_str->emplace(e_prefetcht1,"prefetcht1");
    opcode_str->emplace(e_prefetcht2,"prefetcht2");
    opcode_str->emplace(e_prefetchw,"prefetchw");
    opcode_str->emplace(e_prefetchwt1,"prefetchwt1");
    opcode_str->emplace(e_pshufd,"pshufd");
    opcode_str->emplace(e_pshufhw,"pshufhw");
    opcode_str->emplace(e_pshuflw,"pshuflw");
    opcode_str->emplace(e_pslldq,"pslldq");
    opcode_str->emplace(e_psrldq,"psrldq");
    opcode_str->emplace(e_pswapd,"pswapd");
    opcode_str->emplace(e_ptest,"ptest");
    opcode_str->emplace(e_ptwrite,"ptwrite");
    opcode_str->emplace(e_punpckhqdq,"punpckhqdq");
    opcode_str->emplace(e_punpcklqdq,"punpcklqdq");
    opcode_str->emplace(e_push,"push");
    opcode_str->emplace(e_pushaw,"pushaw");
    opcode_str->emplace(e_pushal,"pushal");
    opcode_str->emplace(e_pushf,"pushf");
    opcode_str->emplace(e_pushfd,"pushfd");
    opcode_str->emplace(e_pushfq,"pushfq");
    opcode_str->emplace(e_rcl,"rcl");
    opcode_str->emplace(e_rcpps,"rcpps");
    opcode_str->emplace(e_rcpss,"rcpss");
    opcode_str->emplace(e_rcr,"rcr");
    opcode_str->emplace(e_rdfsbase,"rdfsbase");
    opcode_str->emplace(e_rdgsbase,"rdgsbase");
    opcode_str->emplace(e_rdmsr,"rdmsr");
    opcode_str->emplace(e_rdpid,"rdpid");
    opcode_str->emplace(e_rdpkru,"rdpkru");
    opcode_str->emplace(e_rdpmc,"rdpmc");
    opcode_str->emplace(e_rdrand,"rdrand");
    opcode_str->emplace(e_rdseed,"rdseed");
    opcode_str->emplace(e_rdsspd,"rdsspd");
    opcode_str->emplace(e_rdsspq,"rdsspq");
    opcode_str->emplace(e_rdtsc,"rdtsc");
    opcode_str->emplace(e_rdtscp,"rdtscp");
    opcode_str->emplace(e_repne,"repne");
    opcode_str->emplace(e_rep,"rep");
    opcode_str->emplace(e_ret_near,"ret_near");
    opcode_str->emplace(e_rex64,"rex64");
    opcode_str->emplace(e_rol,"rol");
    opcode_str->emplace(e_ror,"ror");
    opcode_str->emplace(e_rorx,"rorx");
    opcode_str->emplace(e_roundpd,"roundpd");
    opcode_str->emplace(e_roundps,"roundps");
    opcode_str->emplace(e_roundsd,"roundsd");
    opcode_str->emplace(e_roundss,"roundss");
    opcode_str->emplace(e_rsm,"rsm");
    opcode_str->emplace(e_rsqrtps,"rsqrtps");
    opcode_str->emplace(e_rsqrtss,"rsqrtss");
    opcode_str->emplace(e_rstorssp,"rstorssp");
    opcode_str->emplace(e_sahf,"sahf");
    opcode_str->emplace(e_sal,"sal");
    opcode_str->emplace(e_salc,"salc");
    opcode_str->emplace(e_sar,"sar");
    opcode_str->emplace(e_sarx,"sarx");
    opcode_str->emplace(e_saveprevssp,"saveprevssp");
    opcode_str->emplace(e_sbb,"sbb");
    opcode_str->emplace(e_scasb,"scasb");
    opcode_str->emplace(e_scasd,"scasd");
    opcode_str->emplace(e_scasq,"scasq");
    opcode_str->emplace(e_scasw,"scasw");
    opcode_str->emplace(e_setae,"setae");
    opcode_str->emplace(e_seta,"seta");
    opcode_str->emplace(e_setbe,"setbe");
    opcode_str->emplace(e_setb,"setb");
    opcode_str->emplace(e_sete,"sete");
    opcode_str->emplace(e_setge,"setge");
    opcode_str->emplace(e_setg,"setg");
    opcode_str->emplace(e_setle,"setle");
    opcode_str->emplace(e_setl,"setl");
    opcode_str->emplace(e_setne,"setne");
    opcode_str->emplace(e_setno,"setno");
    opcode_str->emplace(e_setnp,"setnp");
    opcode_str->emplace(e_setns,"setns");
    opcode_str->emplace(e_seto,"seto");
    opcode_str->emplace(e_setp,"setp");
    opcode_str->emplace(e_setssbsy,"setssbsy");
    opcode_str->emplace(e_sets,"sets");
    opcode_str->emplace(e_sfence,"sfence");
    opcode_str->emplace(e_sgdt,"sgdt");
    opcode_str->emplace(e_sha1msg1,"sha1msg1");
    opcode_str->emplace(e_sha1msg2,"sha1msg2");
    opcode_str->emplace(e_sha1nexte,"sha1nexte");
    opcode_str->emplace(e_sha1rnds4,"sha1rnds4");
    opcode_str->emplace(e_sha256msg1,"sha256msg1");
    opcode_str->emplace(e_sha256msg2,"sha256msg2");
    opcode_str->emplace(e_sha256rnds2,"sha256rnds2");
    opcode_str->emplace(e_shl,"shl");
    opcode_str->emplace(e_shld,"shld");
    opcode_str->emplace(e_shlx,"shlx");
    opcode_str->emplace(e_shr,"shr");
    opcode_str->emplace(e_shrd,"shrd");
    opcode_str->emplace(e_shrx,"shrx");
    opcode_str->emplace(e_shufpd,"shufpd");
    opcode_str->emplace(e_shufps,"shufps");
    opcode_str->emplace(e_sidt,"sidt");
    opcode_str->emplace(e_fsin,"fsin");
    opcode_str->emplace(e_skinit,"skinit");
    opcode_str->emplace(e_sldt,"sldt");
    opcode_str->emplace(e_slwpcb,"slwpcb");
    opcode_str->emplace(e_smsw,"smsw");
    opcode_str->emplace(e_sqrtpd,"sqrtpd");
    opcode_str->emplace(e_sqrtps,"sqrtps");
    opcode_str->emplace(e_sqrtsd,"sqrtsd");
    opcode_str->emplace(e_sqrtss,"sqrtss");
    opcode_str->emplace(e_fsqrt,"fsqrt");
    opcode_str->emplace(e_stac,"stac");
    opcode_str->emplace(e_stc,"stc");
    opcode_str->emplace(e_std,"std");
    opcode_str->emplace(e_stgi,"stgi");
    opcode_str->emplace(e_sti,"sti");
    opcode_str->emplace(e_stmxcsr,"stmxcsr");
    opcode_str->emplace(e_stosb,"stosb");
    opcode_str->emplace(e_stosd,"stosd");
    opcode_str->emplace(e_stosq,"stosq");
    opcode_str->emplace(e_stosw,"stosw");
    opcode_str->emplace(e_str,"str");
    opcode_str->emplace(e_fst,"fst");
    opcode_str->emplace(e_fstp,"fstp");
    opcode_str->emplace(e_sub,"sub");
    opcode_str->emplace(e_subpd,"subpd");
    opcode_str->emplace(e_subps,"subps");
    opcode_str->emplace(e_fsubr,"fsubr");
    opcode_str->emplace(e_fisubr,"fisubr");
    opcode_str->emplace(e_fsubrp,"fsubrp");
    opcode_str->emplace(e_subsd,"subsd");
    opcode_str->emplace(e_subss,"subss");
    opcode_str->emplace(e_fsub,"fsub");
    opcode_str->emplace(e_fisub,"fisub");
    opcode_str->emplace(e_fsubp,"fsubp");
    opcode_str->emplace(e_swapgs,"swapgs");
    opcode_str->emplace(e_syscall,"syscall");
    opcode_str->emplace(e_sysenter,"sysenter");
    opcode_str->emplace(e_sysexit,"sysexit");
    opcode_str->emplace(e_sysexitq,"sysexitq");
    opcode_str->emplace(e_sysret,"sysret");
    opcode_str->emplace(e_sysretq,"sysretq");
    opcode_str->emplace(e_t1mskc,"t1mskc");
    opcode_str->emplace(e_test,"test");
    opcode_str->emplace(e_tpause,"tpause");
    opcode_str->emplace(e_ftst,"ftst");
    opcode_str->emplace(e_tzcnt,"tzcnt");
    opcode_str->emplace(e_tzmsk,"tzmsk");
    opcode_str->emplace(e_ucomisd,"ucomisd");
    opcode_str->emplace(e_ucomiss,"ucomiss");
    opcode_str->emplace(e_fucompi,"fucompi");
    opcode_str->emplace(e_fucomi,"fucomi");
    opcode_str->emplace(e_fucompp,"fucompp");
    opcode_str->emplace(e_fucomp,"fucomp");
    opcode_str->emplace(e_fucom,"fucom");
    opcode_str->emplace(e_ud0,"ud0");
    opcode_str->emplace(e_ud1,"ud1");
    opcode_str->emplace(e_ud2,"ud2");
    opcode_str->emplace(e_umonitor,"umonitor");
    opcode_str->emplace(e_umwait,"umwait");
    opcode_str->emplace(e_unpckhpd,"unpckhpd");
    opcode_str->emplace(e_unpckhps,"unpckhps");
    opcode_str->emplace(e_unpcklpd,"unpcklpd");
    opcode_str->emplace(e_unpcklps,"unpcklps");
    opcode_str->emplace(e_v4fmaddps,"v4fmaddps");
    opcode_str->emplace(e_v4fmaddss,"v4fmaddss");
    opcode_str->emplace(e_v4fnmaddps,"v4fnmaddps");
    opcode_str->emplace(e_v4fnmaddss,"v4fnmaddss");
    opcode_str->emplace(e_vaddpd,"vaddpd");
    opcode_str->emplace(e_vaddps,"vaddps");
    opcode_str->emplace(e_vaddsd,"vaddsd");
    opcode_str->emplace(e_vaddss,"vaddss");
    opcode_str->emplace(e_vaddsubpd,"vaddsubpd");
    opcode_str->emplace(e_vaddsubps,"vaddsubps");
    opcode_str->emplace(e_vaesdeclast,"vaesdeclast");
    opcode_str->emplace(e_vaesdec,"vaesdec");
    opcode_str->emplace(e_vaesenclast,"vaesenclast");
    opcode_str->emplace(e_vaesenc,"vaesenc");
    opcode_str->emplace(e_vaesimc,"vaesimc");
    opcode_str->emplace(e_vaeskeygenassist,"vaeskeygenassist");
    opcode_str->emplace(e_valignd,"valignd");
    opcode_str->emplace(e_valignq,"valignq");
    opcode_str->emplace(e_vandnpd,"vandnpd");
    opcode_str->emplace(e_vandnps,"vandnps");
    opcode_str->emplace(e_vandpd,"vandpd");
    opcode_str->emplace(e_vandps,"vandps");
    opcode_str->emplace(e_vblendmpd,"vblendmpd");
    opcode_str->emplace(e_vblendmps,"vblendmps");
    opcode_str->emplace(e_vblendpd,"vblendpd");
    opcode_str->emplace(e_vblendps,"vblendps");
    opcode_str->emplace(e_vblendvpd,"vblendvpd");
    opcode_str->emplace(e_vblendvps,"vblendvps");
    opcode_str->emplace(e_vbroadcastf128,"vbroadcastf128");
    opcode_str->emplace(e_vbroadcastf32x2,"vbroadcastf32x2");
    opcode_str->emplace(e_vbroadcastf32x4,"vbroadcastf32x4");
    opcode_str->emplace(e_vbroadcastf32x8,"vbroadcastf32x8");
    opcode_str->emplace(e_vbroadcastf64x2,"vbroadcastf64x2");
    opcode_str->emplace(e_vbroadcastf64x4,"vbroadcastf64x4");
    opcode_str->emplace(e_vbroadcasti128,"vbroadcasti128");
    opcode_str->emplace(e_vbroadcasti32x2,"vbroadcasti32x2");
    opcode_str->emplace(e_vbroadcasti32x4,"vbroadcasti32x4");
    opcode_str->emplace(e_vbroadcasti32x8,"vbroadcasti32x8");
    opcode_str->emplace(e_vbroadcasti64x2,"vbroadcasti64x2");
    opcode_str->emplace(e_vbroadcasti64x4,"vbroadcasti64x4");
    opcode_str->emplace(e_vbroadcastsd,"vbroadcastsd");
    opcode_str->emplace(e_vbroadcastss,"vbroadcastss");
    opcode_str->emplace(e_vcmp,"vcmp");
    opcode_str->emplace(e_vcmppd,"vcmppd");
    opcode_str->emplace(e_vcmpps,"vcmpps");
    opcode_str->emplace(e_vcmpsd,"vcmpsd");
    opcode_str->emplace(e_vcmpss,"vcmpss");
    opcode_str->emplace(e_vcomisd,"vcomisd");
    opcode_str->emplace(e_vcomiss,"vcomiss");
    opcode_str->emplace(e_vcompresspd,"vcompresspd");
    opcode_str->emplace(e_vcompressps,"vcompressps");
    opcode_str->emplace(e_vcvtdq2pd,"vcvtdq2pd");
    opcode_str->emplace(e_vcvtdq2ps,"vcvtdq2ps");
    opcode_str->emplace(e_vcvtpd2dq,"vcvtpd2dq");
    opcode_str->emplace(e_vcvtpd2ps,"vcvtpd2ps");
    opcode_str->emplace(e_vcvtpd2qq,"vcvtpd2qq");
    opcode_str->emplace(e_vcvtpd2udq,"vcvtpd2udq");
    opcode_str->emplace(e_vcvtpd2uqq,"vcvtpd2uqq");
    opcode_str->emplace(e_vcvtph2ps,"vcvtph2ps");
    opcode_str->emplace(e_vcvtps2dq,"vcvtps2dq");
    opcode_str->emplace(e_vcvtps2pd,"vcvtps2pd");
    opcode_str->emplace(e_vcvtps2ph,"vcvtps2ph");
    opcode_str->emplace(e_vcvtps2qq,"vcvtps2qq");
    opcode_str->emplace(e_vcvtps2udq,"vcvtps2udq");
    opcode_str->emplace(e_vcvtps2uqq,"vcvtps2uqq");
    opcode_str->emplace(e_vcvtqq2pd,"vcvtqq2pd");
    opcode_str->emplace(e_vcvtqq2ps,"vcvtqq2ps");
    opcode_str->emplace(e_vcvtsd2si,"vcvtsd2si");
    opcode_str->emplace(e_vcvtsd2ss,"vcvtsd2ss");
    opcode_str->emplace(e_vcvtsd2usi,"vcvtsd2usi");
    opcode_str->emplace(e_vcvtsi2sd,"vcvtsi2sd");
    opcode_str->emplace(e_vcvtsi2ss,"vcvtsi2ss");
    opcode_str->emplace(e_vcvtss2sd,"vcvtss2sd");
    opcode_str->emplace(e_vcvtss2si,"vcvtss2si");
    opcode_str->emplace(e_vcvtss2usi,"vcvtss2usi");
    opcode_str->emplace(e_vcvttpd2dq,"vcvttpd2dq");
    opcode_str->emplace(e_vcvttpd2qq,"vcvttpd2qq");
    opcode_str->emplace(e_vcvttpd2udq,"vcvttpd2udq");
    opcode_str->emplace(e_vcvttpd2uqq,"vcvttpd2uqq");
    opcode_str->emplace(e_vcvttps2dq,"vcvttps2dq");
    opcode_str->emplace(e_vcvttps2qq,"vcvttps2qq");
    opcode_str->emplace(e_vcvttps2udq,"vcvttps2udq");
    opcode_str->emplace(e_vcvttps2uqq,"vcvttps2uqq");
    opcode_str->emplace(e_vcvttsd2si,"vcvttsd2si");
    opcode_str->emplace(e_vcvttsd2usi,"vcvttsd2usi");
    opcode_str->emplace(e_vcvttss2si,"vcvttss2si");
    opcode_str->emplace(e_vcvttss2usi,"vcvttss2usi");
    opcode_str->emplace(e_vcvtudq2pd,"vcvtudq2pd");
    opcode_str->emplace(e_vcvtudq2ps,"vcvtudq2ps");
    opcode_str->emplace(e_vcvtuqq2pd,"vcvtuqq2pd");
    opcode_str->emplace(e_vcvtuqq2ps,"vcvtuqq2ps");
    opcode_str->emplace(e_vcvtusi2sd,"vcvtusi2sd");
    opcode_str->emplace(e_vcvtusi2ss,"vcvtusi2ss");
    opcode_str->emplace(e_vdbpsadbw,"vdbpsadbw");
    opcode_str->emplace(e_vdivpd,"vdivpd");
    opcode_str->emplace(e_vdivps,"vdivps");
    opcode_str->emplace(e_vdivsd,"vdivsd");
    opcode_str->emplace(e_vdivss,"vdivss");
    opcode_str->emplace(e_vdppd,"vdppd");
    opcode_str->emplace(e_vdpps,"vdpps");
    opcode_str->emplace(e_verr,"verr");
    opcode_str->emplace(e_verw,"verw");
    opcode_str->emplace(e_vexp2pd,"vexp2pd");
    opcode_str->emplace(e_vexp2ps,"vexp2ps");
    opcode_str->emplace(e_vexpandpd,"vexpandpd");
    opcode_str->emplace(e_vexpandps,"vexpandps");
    opcode_str->emplace(e_vextractf128,"vextractf128");
    opcode_str->emplace(e_vextractf32x4,"vextractf32x4");
    opcode_str->emplace(e_vextractf32x8,"vextractf32x8");
    opcode_str->emplace(e_vextractf64x2,"vextractf64x2");
    opcode_str->emplace(e_vextractf64x4,"vextractf64x4");
    opcode_str->emplace(e_vextracti128,"vextracti128");
    opcode_str->emplace(e_vextracti32x4,"vextracti32x4");
    opcode_str->emplace(e_vextracti32x8,"vextracti32x8");
    opcode_str->emplace(e_vextracti64x2,"vextracti64x2");
    opcode_str->emplace(e_vextracti64x4,"vextracti64x4");
    opcode_str->emplace(e_vextractps,"vextractps");
    opcode_str->emplace(e_vfixupimmpd,"vfixupimmpd");
    opcode_str->emplace(e_vfixupimmps,"vfixupimmps");
    opcode_str->emplace(e_vfixupimmsd,"vfixupimmsd");
    opcode_str->emplace(e_vfixupimmss,"vfixupimmss");
    opcode_str->emplace(e_vfmadd132pd,"vfmadd132pd");
    opcode_str->emplace(e_vfmadd132ps,"vfmadd132ps");
    opcode_str->emplace(e_vfmadd132sd,"vfmadd132sd");
    opcode_str->emplace(e_vfmadd132ss,"vfmadd132ss");
    opcode_str->emplace(e_vfmadd213pd,"vfmadd213pd");
    opcode_str->emplace(e_vfmadd213ps,"vfmadd213ps");
    opcode_str->emplace(e_vfmadd213sd,"vfmadd213sd");
    opcode_str->emplace(e_vfmadd213ss,"vfmadd213ss");
    opcode_str->emplace(e_vfmadd231pd,"vfmadd231pd");
    opcode_str->emplace(e_vfmadd231ps,"vfmadd231ps");
    opcode_str->emplace(e_vfmadd231sd,"vfmadd231sd");
    opcode_str->emplace(e_vfmadd231ss,"vfmadd231ss");
    opcode_str->emplace(e_vfmaddpd,"vfmaddpd");
    opcode_str->emplace(e_vfmaddps,"vfmaddps");
    opcode_str->emplace(e_vfmaddsd,"vfmaddsd");
    opcode_str->emplace(e_vfmaddss,"vfmaddss");
    opcode_str->emplace(e_vfmaddsub132pd,"vfmaddsub132pd");
    opcode_str->emplace(e_vfmaddsub132ps,"vfmaddsub132ps");
    opcode_str->emplace(e_vfmaddsub213pd,"vfmaddsub213pd");
    opcode_str->emplace(e_vfmaddsub213ps,"vfmaddsub213ps");
    opcode_str->emplace(e_vfmaddsub231pd,"vfmaddsub231pd");
    opcode_str->emplace(e_vfmaddsub231ps,"vfmaddsub231ps");
    opcode_str->emplace(e_vfmaddsubpd,"vfmaddsubpd");
    opcode_str->emplace(e_vfmaddsubps,"vfmaddsubps");
    opcode_str->emplace(e_vfmsub132pd,"vfmsub132pd");
    opcode_str->emplace(e_vfmsub132ps,"vfmsub132ps");
    opcode_str->emplace(e_vfmsub132sd,"vfmsub132sd");
    opcode_str->emplace(e_vfmsub132ss,"vfmsub132ss");
    opcode_str->emplace(e_vfmsub213pd,"vfmsub213pd");
    opcode_str->emplace(e_vfmsub213ps,"vfmsub213ps");
    opcode_str->emplace(e_vfmsub213sd,"vfmsub213sd");
    opcode_str->emplace(e_vfmsub213ss,"vfmsub213ss");
    opcode_str->emplace(e_vfmsub231pd,"vfmsub231pd");
    opcode_str->emplace(e_vfmsub231ps,"vfmsub231ps");
    opcode_str->emplace(e_vfmsub231sd,"vfmsub231sd");
    opcode_str->emplace(e_vfmsub231ss,"vfmsub231ss");
    opcode_str->emplace(e_vfmsubadd132pd,"vfmsubadd132pd");
    opcode_str->emplace(e_vfmsubadd132ps,"vfmsubadd132ps");
    opcode_str->emplace(e_vfmsubadd213pd,"vfmsubadd213pd");
    opcode_str->emplace(e_vfmsubadd213ps,"vfmsubadd213ps");
    opcode_str->emplace(e_vfmsubadd231pd,"vfmsubadd231pd");
    opcode_str->emplace(e_vfmsubadd231ps,"vfmsubadd231ps");
    opcode_str->emplace(e_vfmsubaddpd,"vfmsubaddpd");
    opcode_str->emplace(e_vfmsubaddps,"vfmsubaddps");
    opcode_str->emplace(e_vfmsubpd,"vfmsubpd");
    opcode_str->emplace(e_vfmsubps,"vfmsubps");
    opcode_str->emplace(e_vfmsubsd,"vfmsubsd");
    opcode_str->emplace(e_vfmsubss,"vfmsubss");
    opcode_str->emplace(e_vfnmadd132pd,"vfnmadd132pd");
    opcode_str->emplace(e_vfnmadd132ps,"vfnmadd132ps");
    opcode_str->emplace(e_vfnmadd132sd,"vfnmadd132sd");
    opcode_str->emplace(e_vfnmadd132ss,"vfnmadd132ss");
    opcode_str->emplace(e_vfnmadd213pd,"vfnmadd213pd");
    opcode_str->emplace(e_vfnmadd213ps,"vfnmadd213ps");
    opcode_str->emplace(e_vfnmadd213sd,"vfnmadd213sd");
    opcode_str->emplace(e_vfnmadd213ss,"vfnmadd213ss");
    opcode_str->emplace(e_vfnmadd231pd,"vfnmadd231pd");
    opcode_str->emplace(e_vfnmadd231ps,"vfnmadd231ps");
    opcode_str->emplace(e_vfnmadd231sd,"vfnmadd231sd");
    opcode_str->emplace(e_vfnmadd231ss,"vfnmadd231ss");
    opcode_str->emplace(e_vfnmaddpd,"vfnmaddpd");
    opcode_str->emplace(e_vfnmaddps,"vfnmaddps");
    opcode_str->emplace(e_vfnmaddsd,"vfnmaddsd");
    opcode_str->emplace(e_vfnmaddss,"vfnmaddss");
    opcode_str->emplace(e_vfnmsub132pd,"vfnmsub132pd");
    opcode_str->emplace(e_vfnmsub132ps,"vfnmsub132ps");
    opcode_str->emplace(e_vfnmsub132sd,"vfnmsub132sd");
    opcode_str->emplace(e_vfnmsub132ss,"vfnmsub132ss");
    opcode_str->emplace(e_vfnmsub213pd,"vfnmsub213pd");
    opcode_str->emplace(e_vfnmsub213ps,"vfnmsub213ps");
    opcode_str->emplace(e_vfnmsub213sd,"vfnmsub213sd");
    opcode_str->emplace(e_vfnmsub213ss,"vfnmsub213ss");
    opcode_str->emplace(e_vfnmsub231pd,"vfnmsub231pd");
    opcode_str->emplace(e_vfnmsub231ps,"vfnmsub231ps");
    opcode_str->emplace(e_vfnmsub231sd,"vfnmsub231sd");
    opcode_str->emplace(e_vfnmsub231ss,"vfnmsub231ss");
    opcode_str->emplace(e_vfnmsubpd,"vfnmsubpd");
    opcode_str->emplace(e_vfnmsubps,"vfnmsubps");
    opcode_str->emplace(e_vfnmsubsd,"vfnmsubsd");
    opcode_str->emplace(e_vfnmsubss,"vfnmsubss");
    opcode_str->emplace(e_vfpclasspd,"vfpclasspd");
    opcode_str->emplace(e_vfpclassps,"vfpclassps");
    opcode_str->emplace(e_vfpclasssd,"vfpclasssd");
    opcode_str->emplace(e_vfpclassss,"vfpclassss");
    opcode_str->emplace(e_vfrczpd,"vfrczpd");
    opcode_str->emplace(e_vfrczps,"vfrczps");
    opcode_str->emplace(e_vfrczsd,"vfrczsd");
    opcode_str->emplace(e_vfrczss,"vfrczss");
    opcode_str->emplace(e_vgatherdpd,"vgatherdpd");
    opcode_str->emplace(e_vgatherdps,"vgatherdps");
    opcode_str->emplace(e_vgatherpf0dpd,"vgatherpf0dpd");
    opcode_str->emplace(e_vgatherpf0dps,"vgatherpf0dps");
    opcode_str->emplace(e_vgatherpf0qpd,"vgatherpf0qpd");
    opcode_str->emplace(e_vgatherpf0qps,"vgatherpf0qps");
    opcode_str->emplace(e_vgatherpf1dpd,"vgatherpf1dpd");
    opcode_str->emplace(e_vgatherpf1dps,"vgatherpf1dps");
    opcode_str->emplace(e_vgatherpf1qpd,"vgatherpf1qpd");
    opcode_str->emplace(e_vgatherpf1qps,"vgatherpf1qps");
    opcode_str->emplace(e_vgatherqpd,"vgatherqpd");
    opcode_str->emplace(e_vgatherqps,"vgatherqps");
    opcode_str->emplace(e_vgetexppd,"vgetexppd");
    opcode_str->emplace(e_vgetexpps,"vgetexpps");
    opcode_str->emplace(e_vgetexpsd,"vgetexpsd");
    opcode_str->emplace(e_vgetexpss,"vgetexpss");
    opcode_str->emplace(e_vgetmantpd,"vgetmantpd");
    opcode_str->emplace(e_vgetmantps,"vgetmantps");
    opcode_str->emplace(e_vgetmantsd,"vgetmantsd");
    opcode_str->emplace(e_vgetmantss,"vgetmantss");
    opcode_str->emplace(e_vgf2p8affineinvqb,"vgf2p8affineinvqb");
    opcode_str->emplace(e_vgf2p8affineqb,"vgf2p8affineqb");
    opcode_str->emplace(e_vgf2p8mulb,"vgf2p8mulb");
    opcode_str->emplace(e_vhaddpd,"vhaddpd");
    opcode_str->emplace(e_vhaddps,"vhaddps");
    opcode_str->emplace(e_vhsubpd,"vhsubpd");
    opcode_str->emplace(e_vhsubps,"vhsubps");
    opcode_str->emplace(e_vinsertf128,"vinsertf128");
    opcode_str->emplace(e_vinsertf32x4,"vinsertf32x4");
    opcode_str->emplace(e_vinsertf32x8,"vinsertf32x8");
    opcode_str->emplace(e_vinsertf64x2,"vinsertf64x2");
    opcode_str->emplace(e_vinsertf64x4,"vinsertf64x4");
    opcode_str->emplace(e_vinserti128,"vinserti128");
    opcode_str->emplace(e_vinserti32x4,"vinserti32x4");
    opcode_str->emplace(e_vinserti32x8,"vinserti32x8");
    opcode_str->emplace(e_vinserti64x2,"vinserti64x2");
    opcode_str->emplace(e_vinserti64x4,"vinserti64x4");
    opcode_str->emplace(e_vinsertps,"vinsertps");
    opcode_str->emplace(e_vlddqu,"vlddqu");
    opcode_str->emplace(e_vldmxcsr,"vldmxcsr");
    opcode_str->emplace(e_vmaskmovdqu,"vmaskmovdqu");
    opcode_str->emplace(e_vmaskmovpd,"vmaskmovpd");
    opcode_str->emplace(e_vmaskmovps,"vmaskmovps");
    opcode_str->emplace(e_vmaxpd,"vmaxpd");
    opcode_str->emplace(e_vmaxps,"vmaxps");
    opcode_str->emplace(e_vmaxsd,"vmaxsd");
    opcode_str->emplace(e_vmaxss,"vmaxss");
    opcode_str->emplace(e_vmcall,"vmcall");
    opcode_str->emplace(e_vmclear,"vmclear");
    opcode_str->emplace(e_vmfunc,"vmfunc");
    opcode_str->emplace(e_vminpd,"vminpd");
    opcode_str->emplace(e_vminps,"vminps");
    opcode_str->emplace(e_vminsd,"vminsd");
    opcode_str->emplace(e_vminss,"vminss");
    opcode_str->emplace(e_vmlaunch,"vmlaunch");
    opcode_str->emplace(e_vmload,"vmload");
    opcode_str->emplace(e_vmmcall,"vmmcall");
    opcode_str->emplace(e_vmovq,"vmovq");
    opcode_str->emplace(e_vmovapd,"vmovapd");
    opcode_str->emplace(e_vmovaps,"vmovaps");
    opcode_str->emplace(e_vmovddup,"vmovddup");
    opcode_str->emplace(e_vmovd,"vmovd");
    opcode_str->emplace(e_vmovdqa32,"vmovdqa32");
    opcode_str->emplace(e_vmovdqa64,"vmovdqa64");
    opcode_str->emplace(e_vmovdqa,"vmovdqa");
    opcode_str->emplace(e_vmovdqu16,"vmovdqu16");
    opcode_str->emplace(e_vmovdqu32,"vmovdqu32");
    opcode_str->emplace(e_vmovdqu64,"vmovdqu64");
    opcode_str->emplace(e_vmovdqu8,"vmovdqu8");
    opcode_str->emplace(e_vmovdqu,"vmovdqu");
    opcode_str->emplace(e_vmovhlps,"vmovhlps");
    opcode_str->emplace(e_vmovhpd,"vmovhpd");
    opcode_str->emplace(e_vmovhps,"vmovhps");
    opcode_str->emplace(e_vmovlhps,"vmovlhps");
    opcode_str->emplace(e_vmovlpd,"vmovlpd");
    opcode_str->emplace(e_vmovlps,"vmovlps");
    opcode_str->emplace(e_vmovmskpd,"vmovmskpd");
    opcode_str->emplace(e_vmovmskps,"vmovmskps");
    opcode_str->emplace(e_vmovntdqa,"vmovntdqa");
    opcode_str->emplace(e_vmovntdq,"vmovntdq");
    opcode_str->emplace(e_vmovntpd,"vmovntpd");
    opcode_str->emplace(e_vmovntps,"vmovntps");
    opcode_str->emplace(e_vmovsd,"vmovsd");
    opcode_str->emplace(e_vmovshdup,"vmovshdup");
    opcode_str->emplace(e_vmovsldup,"vmovsldup");
    opcode_str->emplace(e_vmovss,"vmovss");
    opcode_str->emplace(e_vmovupd,"vmovupd");
    opcode_str->emplace(e_vmovups,"vmovups");
    opcode_str->emplace(e_vmpsadbw,"vmpsadbw");
    opcode_str->emplace(e_vmptrld,"vmptrld");
    opcode_str->emplace(e_vmptrst,"vmptrst");
    opcode_str->emplace(e_vmread,"vmread");
    opcode_str->emplace(e_vmresume,"vmresume");
    opcode_str->emplace(e_vmrun,"vmrun");
    opcode_str->emplace(e_vmsave,"vmsave");
    opcode_str->emplace(e_vmulpd,"vmulpd");
    opcode_str->emplace(e_vmulps,"vmulps");
    opcode_str->emplace(e_vmulsd,"vmulsd");
    opcode_str->emplace(e_vmulss,"vmulss");
    opcode_str->emplace(e_vmwrite,"vmwrite");
    opcode_str->emplace(e_vmxoff,"vmxoff");
    opcode_str->emplace(e_vmxon,"vmxon");
    opcode_str->emplace(e_vorpd,"vorpd");
    opcode_str->emplace(e_vorps,"vorps");
    opcode_str->emplace(e_vp4dpwssds,"vp4dpwssds");
    opcode_str->emplace(e_vp4dpwssd,"vp4dpwssd");
    opcode_str->emplace(e_vpabsb,"vpabsb");
    opcode_str->emplace(e_vpabsd,"vpabsd");
    opcode_str->emplace(e_vpabsq,"vpabsq");
    opcode_str->emplace(e_vpabsw,"vpabsw");
    opcode_str->emplace(e_vpackssdw,"vpackssdw");
    opcode_str->emplace(e_vpacksswb,"vpacksswb");
    opcode_str->emplace(e_vpackusdw,"vpackusdw");
    opcode_str->emplace(e_vpackuswb,"vpackuswb");
    opcode_str->emplace(e_vpaddb,"vpaddb");
    opcode_str->emplace(e_vpaddd,"vpaddd");
    opcode_str->emplace(e_vpaddq,"vpaddq");
    opcode_str->emplace(e_vpaddsb,"vpaddsb");
    opcode_str->emplace(e_vpaddsw,"vpaddsw");
    opcode_str->emplace(e_vpaddusb,"vpaddusb");
    opcode_str->emplace(e_vpaddusw,"vpaddusw");
    opcode_str->emplace(e_vpaddw,"vpaddw");
    opcode_str->emplace(e_vpalignr,"vpalignr");
    opcode_str->emplace(e_vpandd,"vpandd");
    opcode_str->emplace(e_vpandnd,"vpandnd");
    opcode_str->emplace(e_vpandnq,"vpandnq");
    opcode_str->emplace(e_vpandn,"vpandn");
    opcode_str->emplace(e_vpandq,"vpandq");
    opcode_str->emplace(e_vpand,"vpand");
    opcode_str->emplace(e_vpavgb,"vpavgb");
    opcode_str->emplace(e_vpavgw,"vpavgw");
    opcode_str->emplace(e_vpblendd,"vpblendd");
    opcode_str->emplace(e_vpblendmb,"vpblendmb");
    opcode_str->emplace(e_vpblendmd,"vpblendmd");
    opcode_str->emplace(e_vpblendmq,"vpblendmq");
    opcode_str->emplace(e_vpblendmw,"vpblendmw");
    opcode_str->emplace(e_vpblendvb,"vpblendvb");
    opcode_str->emplace(e_vpblendw,"vpblendw");
    opcode_str->emplace(e_vpbroadcastb,"vpbroadcastb");
    opcode_str->emplace(e_vpbroadcastd,"vpbroadcastd");
    opcode_str->emplace(e_vpbroadcastmb2q,"vpbroadcastmb2q");
    opcode_str->emplace(e_vpbroadcastmw2d,"vpbroadcastmw2d");
    opcode_str->emplace(e_vpbroadcastq,"vpbroadcastq");
    opcode_str->emplace(e_vpbroadcastw,"vpbroadcastw");
    opcode_str->emplace(e_vpclmulqdq,"vpclmulqdq");
    opcode_str->emplace(e_vpcmov,"vpcmov");
    opcode_str->emplace(e_vpcmp,"vpcmp");
    opcode_str->emplace(e_vpcmpb,"vpcmpb");
    opcode_str->emplace(e_vpcmpd,"vpcmpd");
    opcode_str->emplace(e_vpcmpeqb,"vpcmpeqb");
    opcode_str->emplace(e_vpcmpeqd,"vpcmpeqd");
    opcode_str->emplace(e_vpcmpeqq,"vpcmpeqq");
    opcode_str->emplace(e_vpcmpeqw,"vpcmpeqw");
    opcode_str->emplace(e_vpcmpestri,"vpcmpestri");
    opcode_str->emplace(e_vpcmpestrm,"vpcmpestrm");
    opcode_str->emplace(e_vpcmpgtb,"vpcmpgtb");
    opcode_str->emplace(e_vpcmpgtd,"vpcmpgtd");
    opcode_str->emplace(e_vpcmpgtq,"vpcmpgtq");
    opcode_str->emplace(e_vpcmpgtw,"vpcmpgtw");
    opcode_str->emplace(e_vpcmpistri,"vpcmpistri");
    opcode_str->emplace(e_vpcmpistrm,"vpcmpistrm");
    opcode_str->emplace(e_vpcmpq,"vpcmpq");
    opcode_str->emplace(e_vpcmpub,"vpcmpub");
    opcode_str->emplace(e_vpcmpud,"vpcmpud");
    opcode_str->emplace(e_vpcmpuq,"vpcmpuq");
    opcode_str->emplace(e_vpcmpuw,"vpcmpuw");
    opcode_str->emplace(e_vpcmpw,"vpcmpw");
    opcode_str->emplace(e_vpcom,"vpcom");
    opcode_str->emplace(e_vpcomb,"vpcomb");
    opcode_str->emplace(e_vpcomd,"vpcomd");
    opcode_str->emplace(e_vpcompressb,"vpcompressb");
    opcode_str->emplace(e_vpcompressd,"vpcompressd");
    opcode_str->emplace(e_vpcompressq,"vpcompressq");
    opcode_str->emplace(e_vpcompressw,"vpcompressw");
    opcode_str->emplace(e_vpcomq,"vpcomq");
    opcode_str->emplace(e_vpcomub,"vpcomub");
    opcode_str->emplace(e_vpcomud,"vpcomud");
    opcode_str->emplace(e_vpcomuq,"vpcomuq");
    opcode_str->emplace(e_vpcomuw,"vpcomuw");
    opcode_str->emplace(e_vpcomw,"vpcomw");
    opcode_str->emplace(e_vpconflictd,"vpconflictd");
    opcode_str->emplace(e_vpconflictq,"vpconflictq");
    opcode_str->emplace(e_vpdpbusds,"vpdpbusds");
    opcode_str->emplace(e_vpdpbusd,"vpdpbusd");
    opcode_str->emplace(e_vpdpwssds,"vpdpwssds");
    opcode_str->emplace(e_vpdpwssd,"vpdpwssd");
    opcode_str->emplace(e_vperm2f128,"vperm2f128");
    opcode_str->emplace(e_vperm2i128,"vperm2i128");
    opcode_str->emplace(e_vpermb,"vpermb");
    opcode_str->emplace(e_vpermd,"vpermd");
    opcode_str->emplace(e_vpermi2b,"vpermi2b");
    opcode_str->emplace(e_vpermi2d,"vpermi2d");
    opcode_str->emplace(e_vpermi2pd,"vpermi2pd");
    opcode_str->emplace(e_vpermi2ps,"vpermi2ps");
    opcode_str->emplace(e_vpermi2q,"vpermi2q");
    opcode_str->emplace(e_vpermi2w,"vpermi2w");
    opcode_str->emplace(e_vpermil2pd,"vpermil2pd");
    opcode_str->emplace(e_vpermilpd,"vpermilpd");
    opcode_str->emplace(e_vpermil2ps,"vpermil2ps");
    opcode_str->emplace(e_vpermilps,"vpermilps");
    opcode_str->emplace(e_vpermpd,"vpermpd");
    opcode_str->emplace(e_vpermps,"vpermps");
    opcode_str->emplace(e_vpermq,"vpermq");
    opcode_str->emplace(e_vpermt2b,"vpermt2b");
    opcode_str->emplace(e_vpermt2d,"vpermt2d");
    opcode_str->emplace(e_vpermt2pd,"vpermt2pd");
    opcode_str->emplace(e_vpermt2ps,"vpermt2ps");
    opcode_str->emplace(e_vpermt2q,"vpermt2q");
    opcode_str->emplace(e_vpermt2w,"vpermt2w");
    opcode_str->emplace(e_vpermw,"vpermw");
    opcode_str->emplace(e_vpexpandb,"vpexpandb");
    opcode_str->emplace(e_vpexpandd,"vpexpandd");
    opcode_str->emplace(e_vpexpandq,"vpexpandq");
    opcode_str->emplace(e_vpexpandw,"vpexpandw");
    opcode_str->emplace(e_vpextrb,"vpextrb");
    opcode_str->emplace(e_vpextrd,"vpextrd");
    opcode_str->emplace(e_vpextrq,"vpextrq");
    opcode_str->emplace(e_vpextrw,"vpextrw");
    opcode_str->emplace(e_vpgatherdd,"vpgatherdd");
    opcode_str->emplace(e_vpgatherdq,"vpgatherdq");
    opcode_str->emplace(e_vpgatherqd,"vpgatherqd");
    opcode_str->emplace(e_vpgatherqq,"vpgatherqq");
    opcode_str->emplace(e_vphaddbd,"vphaddbd");
    opcode_str->emplace(e_vphaddbq,"vphaddbq");
    opcode_str->emplace(e_vphaddbw,"vphaddbw");
    opcode_str->emplace(e_vphadddq,"vphadddq");
    opcode_str->emplace(e_vphaddd,"vphaddd");
    opcode_str->emplace(e_vphaddsw,"vphaddsw");
    opcode_str->emplace(e_vphaddubd,"vphaddubd");
    opcode_str->emplace(e_vphaddubq,"vphaddubq");
    opcode_str->emplace(e_vphaddubw,"vphaddubw");
    opcode_str->emplace(e_vphaddudq,"vphaddudq");
    opcode_str->emplace(e_vphadduwd,"vphadduwd");
    opcode_str->emplace(e_vphadduwq,"vphadduwq");
    opcode_str->emplace(e_vphaddwd,"vphaddwd");
    opcode_str->emplace(e_vphaddwq,"vphaddwq");
    opcode_str->emplace(e_vphaddw,"vphaddw");
    opcode_str->emplace(e_vphminposuw,"vphminposuw");
    opcode_str->emplace(e_vphsubbw,"vphsubbw");
    opcode_str->emplace(e_vphsubdq,"vphsubdq");
    opcode_str->emplace(e_vphsubd,"vphsubd");
    opcode_str->emplace(e_vphsubsw,"vphsubsw");
    opcode_str->emplace(e_vphsubwd,"vphsubwd");
    opcode_str->emplace(e_vphsubw,"vphsubw");
    opcode_str->emplace(e_vpinsrb,"vpinsrb");
    opcode_str->emplace(e_vpinsrd,"vpinsrd");
    opcode_str->emplace(e_vpinsrq,"vpinsrq");
    opcode_str->emplace(e_vpinsrw,"vpinsrw");
    opcode_str->emplace(e_vplzcntd,"vplzcntd");
    opcode_str->emplace(e_vplzcntq,"vplzcntq");
    opcode_str->emplace(e_vpmacsdd,"vpmacsdd");
    opcode_str->emplace(e_vpmacsdqh,"vpmacsdqh");
    opcode_str->emplace(e_vpmacsdql,"vpmacsdql");
    opcode_str->emplace(e_vpmacssdd,"vpmacssdd");
    opcode_str->emplace(e_vpmacssdqh,"vpmacssdqh");
    opcode_str->emplace(e_vpmacssdql,"vpmacssdql");
    opcode_str->emplace(e_vpmacsswd,"vpmacsswd");
    opcode_str->emplace(e_vpmacssww,"vpmacssww");
    opcode_str->emplace(e_vpmacswd,"vpmacswd");
    opcode_str->emplace(e_vpmacsww,"vpmacsww");
    opcode_str->emplace(e_vpmadcsswd,"vpmadcsswd");
    opcode_str->emplace(e_vpmadcswd,"vpmadcswd");
    opcode_str->emplace(e_vpmadd52huq,"vpmadd52huq");
    opcode_str->emplace(e_vpmadd52luq,"vpmadd52luq");
    opcode_str->emplace(e_vpmaddubsw,"vpmaddubsw");
    opcode_str->emplace(e_vpmaddwd,"vpmaddwd");
    opcode_str->emplace(e_vpmaskmovd,"vpmaskmovd");
    opcode_str->emplace(e_vpmaskmovq,"vpmaskmovq");
    opcode_str->emplace(e_vpmaxsb,"vpmaxsb");
    opcode_str->emplace(e_vpmaxsd,"vpmaxsd");
    opcode_str->emplace(e_vpmaxsq,"vpmaxsq");
    opcode_str->emplace(e_vpmaxsw,"vpmaxsw");
    opcode_str->emplace(e_vpmaxub,"vpmaxub");
    opcode_str->emplace(e_vpmaxud,"vpmaxud");
    opcode_str->emplace(e_vpmaxuq,"vpmaxuq");
    opcode_str->emplace(e_vpmaxuw,"vpmaxuw");
    opcode_str->emplace(e_vpminsb,"vpminsb");
    opcode_str->emplace(e_vpminsd,"vpminsd");
    opcode_str->emplace(e_vpminsq,"vpminsq");
    opcode_str->emplace(e_vpminsw,"vpminsw");
    opcode_str->emplace(e_vpminub,"vpminub");
    opcode_str->emplace(e_vpminud,"vpminud");
    opcode_str->emplace(e_vpminuq,"vpminuq");
    opcode_str->emplace(e_vpminuw,"vpminuw");
    opcode_str->emplace(e_vpmovb2m,"vpmovb2m");
    opcode_str->emplace(e_vpmovd2m,"vpmovd2m");
    opcode_str->emplace(e_vpmovdb,"vpmovdb");
    opcode_str->emplace(e_vpmovdw,"vpmovdw");
    opcode_str->emplace(e_vpmovm2b,"vpmovm2b");
    opcode_str->emplace(e_vpmovm2d,"vpmovm2d");
    opcode_str->emplace(e_vpmovm2q,"vpmovm2q");
    opcode_str->emplace(e_vpmovm2w,"vpmovm2w");
    opcode_str->emplace(e_vpmovmskb,"vpmovmskb");
    opcode_str->emplace(e_vpmovq2m,"vpmovq2m");
    opcode_str->emplace(e_vpmovqb,"vpmovqb");
    opcode_str->emplace(e_vpmovqd,"vpmovqd");
    opcode_str->emplace(e_vpmovqw,"vpmovqw");
    opcode_str->emplace(e_vpmovsdb,"vpmovsdb");
    opcode_str->emplace(e_vpmovsdw,"vpmovsdw");
    opcode_str->emplace(e_vpmovsqb,"vpmovsqb");
    opcode_str->emplace(e_vpmovsqd,"vpmovsqd");
    opcode_str->emplace(e_vpmovsqw,"vpmovsqw");
    opcode_str->emplace(e_vpmovswb,"vpmovswb");
    opcode_str->emplace(e_vpmovsxbd,"vpmovsxbd");
    opcode_str->emplace(e_vpmovsxbq,"vpmovsxbq");
    opcode_str->emplace(e_vpmovsxbw,"vpmovsxbw");
    opcode_str->emplace(e_vpmovsxdq,"vpmovsxdq");
    opcode_str->emplace(e_vpmovsxwd,"vpmovsxwd");
    opcode_str->emplace(e_vpmovsxwq,"vpmovsxwq");
    opcode_str->emplace(e_vpmovusdb,"vpmovusdb");
    opcode_str->emplace(e_vpmovusdw,"vpmovusdw");
    opcode_str->emplace(e_vpmovusqb,"vpmovusqb");
    opcode_str->emplace(e_vpmovusqd,"vpmovusqd");
    opcode_str->emplace(e_vpmovusqw,"vpmovusqw");
    opcode_str->emplace(e_vpmovuswb,"vpmovuswb");
    opcode_str->emplace(e_vpmovw2m,"vpmovw2m");
    opcode_str->emplace(e_vpmovwb,"vpmovwb");
    opcode_str->emplace(e_vpmovzxbd,"vpmovzxbd");
    opcode_str->emplace(e_vpmovzxbq,"vpmovzxbq");
    opcode_str->emplace(e_vpmovzxbw,"vpmovzxbw");
    opcode_str->emplace(e_vpmovzxdq,"vpmovzxdq");
    opcode_str->emplace(e_vpmovzxwd,"vpmovzxwd");
    opcode_str->emplace(e_vpmovzxwq,"vpmovzxwq");
    opcode_str->emplace(e_vpmuldq,"vpmuldq");
    opcode_str->emplace(e_vpmulhrsw,"vpmulhrsw");
    opcode_str->emplace(e_vpmulhuw,"vpmulhuw");
    opcode_str->emplace(e_vpmulhw,"vpmulhw");
    opcode_str->emplace(e_vpmulld,"vpmulld");
    opcode_str->emplace(e_vpmullq,"vpmullq");
    opcode_str->emplace(e_vpmullw,"vpmullw");
    opcode_str->emplace(e_vpmultishiftqb,"vpmultishiftqb");
    opcode_str->emplace(e_vpmuludq,"vpmuludq");
    opcode_str->emplace(e_vpopcntb,"vpopcntb");
    opcode_str->emplace(e_vpopcntd,"vpopcntd");
    opcode_str->emplace(e_vpopcntq,"vpopcntq");
    opcode_str->emplace(e_vpopcntw,"vpopcntw");
    opcode_str->emplace(e_vpord,"vpord");
    opcode_str->emplace(e_vporq,"vporq");
    opcode_str->emplace(e_vpor,"vpor");
    opcode_str->emplace(e_vpperm,"vpperm");
    opcode_str->emplace(e_vprold,"vprold");
    opcode_str->emplace(e_vprolq,"vprolq");
    opcode_str->emplace(e_vprolvd,"vprolvd");
    opcode_str->emplace(e_vprolvq,"vprolvq");
    opcode_str->emplace(e_vprord,"vprord");
    opcode_str->emplace(e_vprorq,"vprorq");
    opcode_str->emplace(e_vprorvd,"vprorvd");
    opcode_str->emplace(e_vprorvq,"vprorvq");
    opcode_str->emplace(e_vprotb,"vprotb");
    opcode_str->emplace(e_vprotd,"vprotd");
    opcode_str->emplace(e_vprotq,"vprotq");
    opcode_str->emplace(e_vprotw,"vprotw");
    opcode_str->emplace(e_vpsadbw,"vpsadbw");
    opcode_str->emplace(e_vpscatterdd,"vpscatterdd");
    opcode_str->emplace(e_vpscatterdq,"vpscatterdq");
    opcode_str->emplace(e_vpscatterqd,"vpscatterqd");
    opcode_str->emplace(e_vpscatterqq,"vpscatterqq");
    opcode_str->emplace(e_vpshab,"vpshab");
    opcode_str->emplace(e_vpshad,"vpshad");
    opcode_str->emplace(e_vpshaq,"vpshaq");
    opcode_str->emplace(e_vpshaw,"vpshaw");
    opcode_str->emplace(e_vpshlb,"vpshlb");
    opcode_str->emplace(e_vpshldd,"vpshldd");
    opcode_str->emplace(e_vpshldq,"vpshldq");
    opcode_str->emplace(e_vpshldvd,"vpshldvd");
    opcode_str->emplace(e_vpshldvq,"vpshldvq");
    opcode_str->emplace(e_vpshldvw,"vpshldvw");
    opcode_str->emplace(e_vpshldw,"vpshldw");
    opcode_str->emplace(e_vpshld,"vpshld");
    opcode_str->emplace(e_vpshlq,"vpshlq");
    opcode_str->emplace(e_vpshlw,"vpshlw");
    opcode_str->emplace(e_vpshrdd,"vpshrdd");
    opcode_str->emplace(e_vpshrdq,"vpshrdq");
    opcode_str->emplace(e_vpshrdvd,"vpshrdvd");
    opcode_str->emplace(e_vpshrdvq,"vpshrdvq");
    opcode_str->emplace(e_vpshrdvw,"vpshrdvw");
    opcode_str->emplace(e_vpshrdw,"vpshrdw");
    opcode_str->emplace(e_vpshufbitqmb,"vpshufbitqmb");
    opcode_str->emplace(e_vpshufb,"vpshufb");
    opcode_str->emplace(e_vpshufd,"vpshufd");
    opcode_str->emplace(e_vpshufhw,"vpshufhw");
    opcode_str->emplace(e_vpshuflw,"vpshuflw");
    opcode_str->emplace(e_vpsignb,"vpsignb");
    opcode_str->emplace(e_vpsignd,"vpsignd");
    opcode_str->emplace(e_vpsignw,"vpsignw");
    opcode_str->emplace(e_vpslldq,"vpslldq");
    opcode_str->emplace(e_vpslld,"vpslld");
    opcode_str->emplace(e_vpsllq,"vpsllq");
    opcode_str->emplace(e_vpsllvd,"vpsllvd");
    opcode_str->emplace(e_vpsllvq,"vpsllvq");
    opcode_str->emplace(e_vpsllvw,"vpsllvw");
    opcode_str->emplace(e_vpsllw,"vpsllw");
    opcode_str->emplace(e_vpsrad,"vpsrad");
    opcode_str->emplace(e_vpsraq,"vpsraq");
    opcode_str->emplace(e_vpsravd,"vpsravd");
    opcode_str->emplace(e_vpsravq,"vpsravq");
    opcode_str->emplace(e_vpsravw,"vpsravw");
    opcode_str->emplace(e_vpsraw,"vpsraw");
    opcode_str->emplace(e_vpsrldq,"vpsrldq");
    opcode_str->emplace(e_vpsrld,"vpsrld");
    opcode_str->emplace(e_vpsrlq,"vpsrlq");
    opcode_str->emplace(e_vpsrlvd,"vpsrlvd");
    opcode_str->emplace(e_vpsrlvq,"vpsrlvq");
    opcode_str->emplace(e_vpsrlvw,"vpsrlvw");
    opcode_str->emplace(e_vpsrlw,"vpsrlw");
    opcode_str->emplace(e_vpsubb,"vpsubb");
    opcode_str->emplace(e_vpsubd,"vpsubd");
    opcode_str->emplace(e_vpsubq,"vpsubq");
    opcode_str->emplace(e_vpsubsb,"vpsubsb");
    opcode_str->emplace(e_vpsubsw,"vpsubsw");
    opcode_str->emplace(e_vpsubusb,"vpsubusb");
    opcode_str->emplace(e_vpsubusw,"vpsubusw");
    opcode_str->emplace(e_vpsubw,"vpsubw");
    opcode_str->emplace(e_vpternlogd,"vpternlogd");
    opcode_str->emplace(e_vpternlogq,"vpternlogq");
    opcode_str->emplace(e_vptestmb,"vptestmb");
    opcode_str->emplace(e_vptestmd,"vptestmd");
    opcode_str->emplace(e_vptestmq,"vptestmq");
    opcode_str->emplace(e_vptestmw,"vptestmw");
    opcode_str->emplace(e_vptestnmb,"vptestnmb");
    opcode_str->emplace(e_vptestnmd,"vptestnmd");
    opcode_str->emplace(e_vptestnmq,"vptestnmq");
    opcode_str->emplace(e_vptestnmw,"vptestnmw");
    opcode_str->emplace(e_vptest,"vptest");
    opcode_str->emplace(e_vpunpckhbw,"vpunpckhbw");
    opcode_str->emplace(e_vpunpckhdq,"vpunpckhdq");
    opcode_str->emplace(e_vpunpckhqdq,"vpunpckhqdq");
    opcode_str->emplace(e_vpunpckhwd,"vpunpckhwd");
    opcode_str->emplace(e_vpunpcklbw,"vpunpcklbw");
    opcode_str->emplace(e_vpunpckldq,"vpunpckldq");
    opcode_str->emplace(e_vpunpcklqdq,"vpunpcklqdq");
    opcode_str->emplace(e_vpunpcklwd,"vpunpcklwd");
    opcode_str->emplace(e_vpxord,"vpxord");
    opcode_str->emplace(e_vpxorq,"vpxorq");
    opcode_str->emplace(e_vpxor,"vpxor");
    opcode_str->emplace(e_vrangepd,"vrangepd");
    opcode_str->emplace(e_vrangeps,"vrangeps");
    opcode_str->emplace(e_vrangesd,"vrangesd");
    opcode_str->emplace(e_vrangess,"vrangess");
    opcode_str->emplace(e_vrcp14pd,"vrcp14pd");
    opcode_str->emplace(e_vrcp14ps,"vrcp14ps");
    opcode_str->emplace(e_vrcp14sd,"vrcp14sd");
    opcode_str->emplace(e_vrcp14ss,"vrcp14ss");
    opcode_str->emplace(e_vrcp28pd,"vrcp28pd");
    opcode_str->emplace(e_vrcp28ps,"vrcp28ps");
    opcode_str->emplace(e_vrcp28sd,"vrcp28sd");
    opcode_str->emplace(e_vrcp28ss,"vrcp28ss");
    opcode_str->emplace(e_vrcpps,"vrcpps");
    opcode_str->emplace(e_vrcpss,"vrcpss");
    opcode_str->emplace(e_vreducepd,"vreducepd");
    opcode_str->emplace(e_vreduceps,"vreduceps");
    opcode_str->emplace(e_vreducesd,"vreducesd");
    opcode_str->emplace(e_vreducess,"vreducess");
    opcode_str->emplace(e_vrndscalepd,"vrndscalepd");
    opcode_str->emplace(e_vrndscaleps,"vrndscaleps");
    opcode_str->emplace(e_vrndscalesd,"vrndscalesd");
    opcode_str->emplace(e_vrndscaless,"vrndscaless");
    opcode_str->emplace(e_vroundpd,"vroundpd");
    opcode_str->emplace(e_vroundps,"vroundps");
    opcode_str->emplace(e_vroundsd,"vroundsd");
    opcode_str->emplace(e_vroundss,"vroundss");
    opcode_str->emplace(e_vrsqrt14pd,"vrsqrt14pd");
    opcode_str->emplace(e_vrsqrt14ps,"vrsqrt14ps");
    opcode_str->emplace(e_vrsqrt14sd,"vrsqrt14sd");
    opcode_str->emplace(e_vrsqrt14ss,"vrsqrt14ss");
    opcode_str->emplace(e_vrsqrt28pd,"vrsqrt28pd");
    opcode_str->emplace(e_vrsqrt28ps,"vrsqrt28ps");
    opcode_str->emplace(e_vrsqrt28sd,"vrsqrt28sd");
    opcode_str->emplace(e_vrsqrt28ss,"vrsqrt28ss");
    opcode_str->emplace(e_vrsqrtps,"vrsqrtps");
    opcode_str->emplace(e_vrsqrtss,"vrsqrtss");
    opcode_str->emplace(e_vscalefpd,"vscalefpd");
    opcode_str->emplace(e_vscalefps,"vscalefps");
    opcode_str->emplace(e_vscalefsd,"vscalefsd");
    opcode_str->emplace(e_vscalefss,"vscalefss");
    opcode_str->emplace(e_vscatterdpd,"vscatterdpd");
    opcode_str->emplace(e_vscatterdps,"vscatterdps");
    opcode_str->emplace(e_vscatterpf0dpd,"vscatterpf0dpd");
    opcode_str->emplace(e_vscatterpf0dps,"vscatterpf0dps");
    opcode_str->emplace(e_vscatterpf0qpd,"vscatterpf0qpd");
    opcode_str->emplace(e_vscatterpf0qps,"vscatterpf0qps");
    opcode_str->emplace(e_vscatterpf1dpd,"vscatterpf1dpd");
    opcode_str->emplace(e_vscatterpf1dps,"vscatterpf1dps");
    opcode_str->emplace(e_vscatterpf1qpd,"vscatterpf1qpd");
    opcode_str->emplace(e_vscatterpf1qps,"vscatterpf1qps");
    opcode_str->emplace(e_vscatterqpd,"vscatterqpd");
    opcode_str->emplace(e_vscatterqps,"vscatterqps");
    opcode_str->emplace(e_vshuff32x4,"vshuff32x4");
    opcode_str->emplace(e_vshuff64x2,"vshuff64x2");
    opcode_str->emplace(e_vshufi32x4,"vshufi32x4");
    opcode_str->emplace(e_vshufi64x2,"vshufi64x2");
    opcode_str->emplace(e_vshufpd,"vshufpd");
    opcode_str->emplace(e_vshufps,"vshufps");
    opcode_str->emplace(e_vsqrtpd,"vsqrtpd");
    opcode_str->emplace(e_vsqrtps,"vsqrtps");
    opcode_str->emplace(e_vsqrtsd,"vsqrtsd");
    opcode_str->emplace(e_vsqrtss,"vsqrtss");
    opcode_str->emplace(e_vstmxcsr,"vstmxcsr");
    opcode_str->emplace(e_vsubpd,"vsubpd");
    opcode_str->emplace(e_vsubps,"vsubps");
    opcode_str->emplace(e_vsubsd,"vsubsd");
    opcode_str->emplace(e_vsubss,"vsubss");
    opcode_str->emplace(e_vtestpd,"vtestpd");
    opcode_str->emplace(e_vtestps,"vtestps");
    opcode_str->emplace(e_vucomisd,"vucomisd");
    opcode_str->emplace(e_vucomiss,"vucomiss");
    opcode_str->emplace(e_vunpckhpd,"vunpckhpd");
    opcode_str->emplace(e_vunpckhps,"vunpckhps");
    opcode_str->emplace(e_vunpcklpd,"vunpcklpd");
    opcode_str->emplace(e_vunpcklps,"vunpcklps");
    opcode_str->emplace(e_vxorpd,"vxorpd");
    opcode_str->emplace(e_vxorps,"vxorps");
    opcode_str->emplace(e_vzeroall,"vzeroall");
    opcode_str->emplace(e_vzeroupper,"vzeroupper");
    opcode_str->emplace(e_wait,"wait");
    opcode_str->emplace(e_wbinvd,"wbinvd");
    opcode_str->emplace(e_wbnoinvd,"wbnoinvd");
    opcode_str->emplace(e_wrfsbase,"wrfsbase");
    opcode_str->emplace(e_wrgsbase,"wrgsbase");
    opcode_str->emplace(e_wrmsr,"wrmsr");
    opcode_str->emplace(e_wrpkru,"wrpkru");
    opcode_str->emplace(e_wrssd,"wrssd");
    opcode_str->emplace(e_wrssq,"wrssq");
    opcode_str->emplace(e_wrussd,"wrussd");
    opcode_str->emplace(e_wrussq,"wrussq");
    opcode_str->emplace(e_xabort,"xabort");
    opcode_str->emplace(e_xacquire,"xacquire");
    opcode_str->emplace(e_xadd,"xadd");
    opcode_str->emplace(e_xbegin,"xbegin");
    opcode_str->emplace(e_xchg,"xchg");
    opcode_str->emplace(e_fxch,"fxch");
    opcode_str->emplace(e_xcryptcbc,"xcryptcbc");
    opcode_str->emplace(e_xcryptcfb,"xcryptcfb");
    opcode_str->emplace(e_xcryptctr,"xcryptctr");
    opcode_str->emplace(e_xcryptecb,"xcryptecb");
    opcode_str->emplace(e_xcryptofb,"xcryptofb");
    opcode_str->emplace(e_xend,"xend");
    opcode_str->emplace(e_xgetbv,"xgetbv");
    opcode_str->emplace(e_xlatb,"xlatb");
    opcode_str->emplace(e_xor,"xor");
    opcode_str->emplace(e_xorpd,"xorpd");
    opcode_str->emplace(e_xorps,"xorps");
    opcode_str->emplace(e_xrelease,"xrelease");
    opcode_str->emplace(e_xrstor,"xrstor");
    opcode_str->emplace(e_xrstor64,"xrstor64");
    opcode_str->emplace(e_xrstors,"xrstors");
    opcode_str->emplace(e_xrstors64,"xrstors64");
    opcode_str->emplace(e_xsave,"xsave");
    opcode_str->emplace(e_xsave64,"xsave64");
    opcode_str->emplace(e_xsavec,"xsavec");
    opcode_str->emplace(e_xsavec64,"xsavec64");
    opcode_str->emplace(e_xsaveopt,"xsaveopt");
    opcode_str->emplace(e_xsaveopt64,"xsaveopt64");
    opcode_str->emplace(e_xsaves,"xsaves");
    opcode_str->emplace(e_xsaves64,"xsaves64");
    opcode_str->emplace(e_xsetbv,"xsetbv");
    opcode_str->emplace(e_xsha1,"xsha1");
    opcode_str->emplace(e_xsha256,"xsha256");
    opcode_str->emplace(e_xstore,"xstore");
    opcode_str->emplace(e_xtest,"xtest");
    opcode_str->emplace(e_No_Entry, "No_Entry");
}


/******************************  ppc functions  *************************************/

void InstructionDecoder_Capstone::decodeOperands_ppc(const Instruction*, cs_detail *) {

}

entryID InstructionDecoder_Capstone::opcodeTranslation_ppc(unsigned int) {
    return e_No_Entry; 
}


/******************************  aarch64 functions  *************************************/

void InstructionDecoder_Capstone::decodeOperands_aarch64(const Instruction* , cs_detail *) {

}

entryID InstructionDecoder_Capstone::opcodeTranslation_aarch64(unsigned int) {
    return e_No_Entry; 
}

} // namespace InstructionAPI

} // namespace Dyninst
