PDFLATEX    ?=pdflatex

all:
	${PDFLATEX} instructionapi
	${PDFLATEX} instructionapi

clean:
	rm -f instructionapi.aux instructionapi.bbl instructionapi.blg instructionapi.dvi instructionapi.log instructionapi.pdf instructionapi.ps instructionapi.toc instructionapi.out
