#!/usr/local/bin/tcsh

if($# > 1) then
	echo "usage : $0 [<additional args>]"
	exit
endif


set CWD=`pwd`
echo $CWD

cd $CWD/ijpeg

if(-e ijpeg.gz) then
	echo "gunzip ijpeg.gz"
	gunzip ijpeg.gz
endif

echo "../../dyncov $1 --run ./ijpeg -image_file specmun.ppm -compression.quality 90 -compression.optimize_coding 0 -compression.smoothing_factor 90 -difference.image 1 -difference.x_stride 10 -difference.y_stride 10 -verbose 1 -GO.findoptcomp"
../../dyncov $1 --run ./ijpeg -image_file specmun.ppm -compression.quality 90 -compression.optimize_coding 0 -compression.smoothing_factor 90 -difference.image 1 -difference.x_stride 10 -difference.y_stride 10 -verbose 1 -GO.findoptcomp

if(-e core) then
        echo "\tThe execution is terminated by Segmentation Fault"
	rm -rf core
endif

cd $CWD/cc1

if(-e cc1.gz) then
	echo "gunzip cc1.gz"
	gunzip cc1.gz
endif

echo "../../dyncov $1 --run ./cc1 `ls *.i`"
../../dyncov $1 --run ./cc1 `ls *.i`
rm *.s

if(-e core) then
        echo "\tThe execution is terminated by Segmentation Fault"
	rm -rf core
endif
