#Defines:
#
#  LAUNCHMON_FOUND
#  LAUNCHMON_INCLUDE_DIRS
#  LAUNCHMON_FE_LIBRARIES
#  LAUNCHMON_BE_LIBRARIES
#  LAUNCHMON_DEFINITIONS

find_path(LAUNCHMON_INCLUDE_DIR NAMES lmon_api/lmon_fe.h HINTS ${LAUNCHMON_INCLUDE_DIRS} ${LAUNCHMON_DIR}/include)
find_library(LAUNCHMON_FE_LIBRARIES NAMES monfeapi HINTS ${LAUNCHMON_LIBRARIES} ${LAUNCHMON_DIR}/lib)
find_library(LAUNCHMON_BE_LIBRARIES NAMES monbeapi HINTS ${LAUNCHMON_LIBRARIES} ${LAUNCHMON_DIR}/lib)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LaunchMON DEFAULT_MSG LAUNCHMON_FE_LIBRARIES LAUNCHMON_INCLUDE_DIR)
set (LAUNCHMON_DEFINITIONS -Dcap_launchmon)

