PDFLATEX    ?=pdflatex

all:
	${PDFLATEX} stackwalkerapi
	${PDFLATEX} stackwalkerapi
	cp stackwalkerapi.pdf ../../../docs/stackwalkerapi.pdf

clean:
	rm -f stackwalkerapi.aux stackwalkerapi.bbl stackwalkerapi.blg stackwalkerapi.dvi stackwalkerapi.log stackwalkerapi.pdf stackwalkerapi.ps stackwalkerapi.toc stackwalkerapi.out
