PDFLATEX    ?=pdflatex

all:
	${PDFLATEX} parseapi
	${PDFLATEX} parseapi

clean:
	rm -f parseapi.aux parseapi.bbl parseapi.blg parseapi.dvi parseapi.log parseapi.pdf parseapi.ps parseapi.toc parseapi.out
