PDFLATEX    ?=pdflatex

all:
	${PDFLATEX} symtabapi
	${PDFLATEX} symtabapi

clean:
	rm -f symtabapi.aux symtabapi.bbl symtabapi.blg symtabapi.dvi symtabapi.log symtabapi.pdf symtabapi.ps symtabapi.toc symtabapi.out
