#define yy_create_buffer dynC_create_buffer
#define yy_delete_buffer dynC_delete_buffer
#define yy_scan_buffer dynC_scan_buffer
#define yy_scan_string dynC_scan_string
#define yy_scan_bytes dynC_scan_bytes
#define yy_flex_debug dynC_flex_debug
#define yy_init_buffer dynC_init_buffer
#define yy_flush_buffer dynC_flush_buffer
#define yy_load_buffer_state dynC_load_buffer_state
#define yy_switch_to_buffer dynC_switch_to_buffer
#define yyin dynCin
#define yyleng dynCleng
#define yylex dynClex
#define yyout dynCout
#define yyrestart dynCrestart
#define yytext dynCtext

/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
static yyconst short int yy_accept[253] =
    {   0,
        0,    0,    1,    1,    0,    0,  104,  102,  100,  101,
       87,   39,  102,   93,   86,  102,   81,   82,   91,   90,
       78,   89,   85,   92,   31,   31,   79,   73,   94,   80,
       95,   98,   29,   29,   83,   84,   96,   99,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   74,   97,   75,   88,    1,    3,    2,
       50,   41,   40,  103,   72,   30,   58,   75,   77,   67,
       59,    0,    0,   56,   64,   54,   65,   55,   66,    0,
       37,    6,    5,   57,   38,   31,    0,   34,    0,   31,
       74,   63,   69,   71,   70,   62,   29,    0,   60,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   16,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   76,   61,   68,    1,
        2,    2,    4,   50,   49,   42,   43,   47,   48,   44,
       46,   45,   30,   35,   51,    0,   37,    5,   37,    0,
       38,   33,    0,   36,   32,   53,   52,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,    7,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   42,   43,    0,   37,    0,
       37,    0,   38,   36,   32,   29,   12,   29,   29,   29,

       15,   10,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   22,   29,   29,   42,    0,
       37,   11,   13,   29,   29,   23,   29,   24,   29,   25,
       29,   29,   29,   29,   29,   29,   29,    9,   29,   27,
       29,   17,   18,   19,    8,   20,   26,   29,   14,   28,
       21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   30,   49,   50,   51,   52,
       53,   54,   30,   55,   56,   57,   58,   59,   60,   33,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    5,    1,    1,    1,    1,    1,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    7,    7,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    1,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[265] =
    {   0,
        0,    0,   64,   65,   66,   67,  450,  451,  451,  451,
      425,  451,    0,   49,   67,  413,  451,  451,  423,   65,
      451,   68,   66,   82,   99,   77,  451,  451,   80,  422,
       55,  451,    0,  436,  451,  451,  420,  451,   35,   58,
       56,   70,   73,  393,   76,  389,  401,  400,  395,   77,
       86,  386,  384,  429,   84,  451,  451,    0,  451,   95,
        0,  451,  451,  120,  451,    0,  451,  451,  451,  451,
      451,  107,  126,  451,  451,  451,  451,  451,  451,  419,
      135,  451,    0,  451,  163,  137,  183,  128,    0,    0,
      451,  410,  451,  451,  451,  409,    0,  397,  451,  378,

      386,  373,  388,  375,  381,  367,  368,  365,  372,  368,
      367,    0,  362,   84,  376,  362,  351,  337,  327,  112,
      333,  321,  315,  310,  293,  292,  451,  451,  451,    0,
      133,  134,  451,    0,  451,  170,  186,  451,  451,  451,
      451,  451,    0,  451,  451,  196,  451,    0,  199,  216,
      451,  189,  204,  222,  206,  451,  451,  289,  298,  292,
      280,  278,  293,  291,  287,  279,  273,  288,  286,    0,
      286,  279,  277,  280,  261,  263,  272,  258,  256,  256,
      260,  258,  255,  244,  253,  239,  242,  250,  255,  263,
      451,  269,  272,  451,  248,  236,    0,  220,  213,  216,

        0,    0,  221,  206,  215,  204,  204,  199,  193,  189,
      192,  185,  190,  184,  185,    0,  169,  158,  275,  289,
      292,    0,    0,  150,  155,    0,  147,    0,  141,    0,
      132,  131,  132,  116,  124,  119,  114,    0,   99,    0,
      100,    0,    0,    0,    0,    0,    0,   36,    0,    0,
        0,  451,  342,  350,  352,  360,  363,  371,  379,  387,
      395,  398,  406,  409
    } ;

static yyconst short int yy_def[265] =
    {   0,
      252,    1,  253,  253,  254,  254,  252,  252,  252,  252,
      252,  252,  255,  252,  252,  256,  252,  252,  252,  252,
      252,  252,  252,  252,  252,   25,  252,  252,  252,  252,
      252,  252,  257,  257,  252,  252,  252,  252,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  252,  252,  252,  252,  258,  252,  259,
      260,  252,  252,  261,  252,  262,  252,  252,  252,  252,
      252,  256,  256,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  263,  252,  252,   25,  252,  252,  264,   26,
      252,  252,  252,  252,  252,  252,  257,  256,  252,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  252,  252,  252,  258,
      259,  259,  252,  260,  252,  252,  252,  252,  252,  252,
      252,  252,  262,  252,  252,  252,  252,  263,  252,  252,
      252,  252,  252,  252,  264,  252,  252,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  257,  257,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  252,  252,
      252,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,    0,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252
    } ;

static yyconst short int yy_nxt[518] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   33,   33,   33,
       34,   33,   33,   35,    8,   36,   37,    8,   38,   33,
       39,   40,   41,   42,   43,   44,   33,   45,   33,   46,
       47,   33,   33,   48,   49,   50,   51,   52,   53,   33,
       33,   33,   54,   55,   56,   57,   59,   59,   62,   62,
       63,   63,   67,   68,   70,   60,   60,   75,   95,   96,
      251,   80,   77,   81,   81,   81,   91,  100,   76,  101,
       71,   78,   79,   82,   90,   90,   90,  102,   83,  105,

       64,   64,   92,   93,  103,   84,  132,  128,  106,  252,
      104,  133,  109,   69,   85,  144,   86,   86,   86,  107,
      112,  108,  110,  118,  119,  171,   87,  113,  252,   88,
       88,   89,  122,  120,   72,  172,  121,  136,  136,  137,
      123,   73,   87,  250,  252,  132,  124,  129,   88,  252,
      133,  178,   81,   81,   81,  249,   88,  248,   88,   88,
      138,  247,  146,  147,  139,  147,  179,  152,  152,  252,
      246,  140,  245,  244,  141,  243,  142,   88,  146,  147,
      149,  149,  149,  242,  147,   88,  152,  186,  186,  187,
      150,  151,  241,  151,  152,  153,  240,  153,  170,  239,

      154,  154,  154,  187,  187,  187,  150,  151,  188,  238,
      188,  237,  151,  189,  189,  189,  149,  149,  149,  152,
      152,  154,  154,  154,  236,  235,  190,  191,  192,  191,
      192,  234,  233,  193,  193,  193,  195,  195,  152,  154,
      154,  154,  190,  191,  232,  170,  152,  231,  191,  230,
      194,  229,  194,  228,  227,  195,  219,  219,  187,  187,
      187,  187,  170,  195,  226,  225,  194,  189,  189,  189,
      224,  194,  189,  189,  189,  220,  223,  220,  195,  195,
      221,  221,  221,  147,  222,  147,  193,  193,  193,  193,
      193,  193,  187,  187,  187,  170,  218,  195,  217,  147,

      151,  216,  151,  215,  147,  195,  221,  221,  221,  221,
      221,  221,  214,  213,  212,  211,  151,  210,  209,  208,
      191,  151,  191,  207,  170,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  170,  197,  191,  196,  170,  185,
      184,  191,   58,   58,   58,   58,   58,   58,   58,   58,
       61,   61,   61,   61,   61,   61,   61,   61,   66,   66,
       72,   72,   72,  183,   72,   72,   72,   72,   97,   97,
       97,  130,  182,  130,  130,  181,  130,  130,  130,  131,
      180,  131,  131,  131,  131,  131,  131,  134,  177,  176,
      134,  134,  134,  134,  134,  135,  135,  135,  135,  135,

      135,  135,  135,  143,  143,  143,  148,  175,  148,  148,
      148,  148,  148,  148,  155,  155,  174,  173,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,   73,  157,  156,  145,  127,  126,  125,  117,  116,
      115,  114,  111,   99,   98,   94,   74,   73,   65,  252,
        7,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252
    } ;

static yyconst short int yy_chk[518] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
        5,    6,   14,   14,   15,    3,    4,   20,   31,   31,
      248,   23,   22,   23,   23,   23,   29,   39,   20,   39,
       15,   22,   22,   24,   26,   26,   26,   40,   24,   41,

        5,    6,   29,   29,   40,   24,   60,   55,   41,   26,
       40,   60,   43,   14,   25,   72,   25,   25,   25,   42,
       45,   42,   43,   50,   50,  114,   25,   45,   73,   25,
       25,   25,   51,   50,   73,  114,   50,   64,   64,   64,
       51,   72,   25,  241,  131,  132,   51,   55,   25,  131,
      132,  120,   81,   81,   81,  239,   25,  237,   88,   88,
       64,  236,   81,   81,   64,   81,  120,   86,   86,   86,
      235,   64,  234,  233,   64,  232,   64,   88,   81,   81,
       85,   85,   85,  231,   81,   88,   86,  136,  136,  136,
       85,   85,  229,   85,   86,   87,  227,   87,  225,  224,

       87,   87,   87,  137,  137,  137,   85,   85,  146,  218,
      146,  217,   85,  146,  146,  146,  149,  149,  149,  152,
      152,  153,  153,  153,  215,  214,  149,  149,  150,  149,
      150,  213,  212,  150,  150,  150,  155,  155,  152,  154,
      154,  154,  149,  149,  211,  210,  152,  209,  149,  208,
      154,  207,  154,  206,  205,  155,  186,  186,  186,  187,
      187,  187,  204,  155,  203,  200,  154,  188,  188,  188,
      199,  154,  189,  189,  189,  190,  198,  190,  195,  195,
      190,  190,  190,  189,  196,  189,  192,  192,  192,  193,
      193,  193,  219,  219,  219,  185,  184,  195,  183,  189,

      193,  182,  193,  181,  189,  195,  220,  220,  220,  221,
      221,  221,  180,  179,  178,  177,  193,  176,  175,  174,
      221,  193,  221,  173,  172,  171,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  221,  159,  158,  126,
      125,  221,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  254,  254,  254,  254,  254,  254,  254,  255,  255,
      256,  256,  256,  124,  256,  256,  256,  256,  257,  257,
      257,  258,  123,  258,  258,  122,  258,  258,  258,  259,
      121,  259,  259,  259,  259,  259,  259,  260,  119,  118,
      260,  260,  260,  260,  260,  261,  261,  261,  261,  261,

      261,  261,  261,  262,  262,  262,  263,  117,  263,  263,
      263,  263,  263,  263,  264,  264,  116,  115,  113,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   98,   96,   92,   80,   54,   53,   52,   49,   48,
       47,   46,   44,   37,   34,   30,   19,   16,   11,    7,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../src/C.l"
#define INITIAL 0
#define comment 1

#define stringmode 2

#line 14 "../src/C.l"

#include <stdio.h>
#include <string>
#include "BPatch_snippet.h"
#include <vector>
#include "dynC.tab.h"

int line_num;

extern "C" {
  void set_lex_input(char *);
}

static char *input_str = NULL;  

#define input() (*input_str++)
//#define unput(c) (*--input_str = c)
#define yylval dynClval

std::string c_string_buf = "";

bool lexVerbose = false;

#line 621 "lex.dynC.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 39 "../src/C.l"


#line 775 "lex.dynC.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 451 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 43 "../src/C.l"
/* eat anything that's not a '*' */                              
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "../src/C.l"
/* eat up '*'s not followed by '/'s */                           
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "../src/C.l"
++line_num;                                                      
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "../src/C.l"
BEGIN(INITIAL);                                                  
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 50 "../src/C.l"
{ if(lexVerbose)printf("Inline Comment\n") /* inline comment */; ++line_num; }                            
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "../src/C.l"
{ BEGIN(comment); }                                                  
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "../src/C.l"
{ yylval.sval = strdup(yytext); return TYPE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "../src/C.l"
{return STRUCT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "../src/C.l"
{return UNION; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "../src/C.l"
{return ENUM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "../src/C.l"
{ return(BREAK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "../src/C.l"
{ return(CASE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "../src/C.l"
{ return(CONST); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "../src/C.l"
{ return(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "../src/C.l"
{ return(ELSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "../src/C.l"
{ return(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "../src/C.l"
{ return(RETURN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "../src/C.l"
{ return(SIZEOF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "../src/C.l"
{ return(STATIC); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "../src/C.l"
{ return(SWITCH); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "../src/C.l"
{ return(TYPEDEF); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "../src/C.l"
{ return(TRUE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "../src/C.l"
{ return(FALSE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "../src/C.l"
{ return(LOCAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "../src/C.l"
{ return(PARAM); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "../src/C.l"
{ return(THREAD); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "../src/C.l"
{ return(GLOBAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "../src/C.l"
{ return(MACHINE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "../src/C.l"
{yylval.sval = strdup(yytext); if(lexVerbose) printf("ID: %s\n", yytext); return(IDENTIFIER); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "../src/C.l"
{ yylval.sval = &yytext[1]; return(DYNINST_CALL); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "../src/C.l"
{ yylval.ival = atoi(yytext); return NUMBER;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "../src/C.l"
{ return(CONSTANT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "../src/C.l"
{if(lexVerbose)printf("String Mode!\n"); c_string_buf = ""; BEGIN(stringmode);} 
	YY_BREAK

case 40:
YY_RULE_SETUP
#line 98 "../src/C.l"
{ /* saw closing quote - all done */
                  // this string handling code was taken from the flex manual
                  if(lexVerbose)printf("string done\n");
                  BEGIN(INITIAL);                                                    
                  char * cstr = new char[c_string_buf.size() + 1];                   

                  strcpy (cstr, c_string_buf.c_str());                               

                  yylval.sval = strdup(cstr);                                   
                  delete[] cstr;                                                     
                  return STRING;                                                     
                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "../src/C.l"
{ /* error - unterminated strin constant */
                  yylval.context = "unterminated string constant";
                  //yylval.line_number = line_num;                                    
                  return ERROR; 
                }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "../src/C.l"
{ /* octal escape sequence */
                  int result;                                                        
                  (void) sscanf( yytext + 1, "%o", &result );                        
                  if ( result > 0xff ){
                      /* error, constant is out-of-bounds */
                      yylval.context = "constant out of bounds";                
                     // yylval.line_number = line_num;                            
                      return ERROR;                                                  
                  }
                  c_string_buf += result;                                            
  
                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "../src/C.l"
{ /* generate error - bad escape sequence */
                  yylval.context = "bad escape sequence";                       
                 // yylval.line_number = line_num;                                
                  return ERROR;                                                      
                }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "../src/C.l"
c_string_buf += '\n';                                                
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 136 "../src/C.l"
c_string_buf += '\t';                                                
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 137 "../src/C.l"
c_string_buf += '\r';                                                
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 138 "../src/C.l"
c_string_buf += '\b';                                             
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 139 "../src/C.l"
c_string_buf += '\f';                                                
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "../src/C.l"
c_string_buf += yytext[1];
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "../src/C.l"
{
                  char *yptr = yytext;
                  while ( *yptr ) { c_string_buf += *yptr++; }
                }
	YY_BREAK

case 51:
YY_RULE_SETUP
#line 149 "../src/C.l"
{ return(ELLIPSIS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 150 "../src/C.l"
{ return(RIGHT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 151 "../src/C.l"
{ return(LEFT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 152 "../src/C.l"
{ return(ADD_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 153 "../src/C.l"
{ return(SUB_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 154 "../src/C.l"
{ return(MUL_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 155 "../src/C.l"
{ return(DIV_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "../src/C.l"
{ return(MOD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 157 "../src/C.l"
{ return(AND_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 158 "../src/C.l"
{ return(XOR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "../src/C.l"
{ return(OR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "../src/C.l"
{ return(RIGHT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 161 "../src/C.l"
{ return(LEFT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 162 "../src/C.l"
{ return(INC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "../src/C.l"
{ return(DEC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 164 "../src/C.l"
{ return(PTR_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "../src/C.l"
{ return(AND); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 166 "../src/C.l"
{ return(OR); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 167 "../src/C.l"
{ return(LESS_EQ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 168 "../src/C.l"
{ return(GREATER_EQ); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "../src/C.l"
{ return(EQ); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 170 "../src/C.l"
{ return(NOT_EQ); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 171 "../src/C.l"
{ return(SEMI); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 172 "../src/C.l"
{ return('{'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 173 "../src/C.l"
{ return('}'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 174 "../src/C.l"
{ return(NOPEN); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "../src/C.l"
{ return(NCLOSE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 176 "../src/C.l"
{ return(COMMA); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "../src/C.l"
{ return(COLON); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "../src/C.l"
{ return(ASSIGN); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 179 "../src/C.l"
{ if(lexVerbose)printf("(\n"); return('('); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "../src/C.l"
{ if(lexVerbose)printf(")\n"); return(')'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 181 "../src/C.l"
{ return('['); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 182 "../src/C.l"
{ return(']'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 183 "../src/C.l"
{ return(DOT); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 184 "../src/C.l"
{ return('&'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 185 "../src/C.l"
{ return('!'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 186 "../src/C.l"
{ return('~'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 187 "../src/C.l"
{ return('-'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "../src/C.l"
{ return('+'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 189 "../src/C.l"
{ return('*'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 190 "../src/C.l"
{ return('/'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 191 "../src/C.l"
{ return('%'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 192 "../src/C.l"
{ return('<'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 193 "../src/C.l"
{ return('>'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 194 "../src/C.l"
{ return('^'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 195 "../src/C.l"
{ return('|'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 196 "../src/C.l"
{ return('?'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 197 "../src/C.l"
{ if(lexVerbose)printf("Backtick\n"); return(BACKTICK); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "../src/C.l"
{ }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 200 "../src/C.l"
{if(lexVerbose)printf("New Line!\n"); line_num++;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 201 "../src/C.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 205 "../src/C.l"
ECHO;
	YY_BREAK
#line 1410 "lex.dynC.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(stringmode):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 252);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 205 "../src/C.l"


void set_lex_input(char *str)
{
   static bool firstCall = true;
   YY_BUFFER_STATE bp;
   input_str = str;
   bp = yy_scan_string(str);

   if(!firstCall) yy_flush_buffer(YY_CURRENT_BUFFER);
   firstCall = false;
}
