if (CMAKE_COMPILER_IS_GNUCXX 
    OR ${CMAKE_C_COMPILER_ID} MATCHES Clang
    OR ${CMAKE_C_COMPILER_ID} MATCHES GNU
    OR ${CMAKE_C_COMPILER_ID} MATCHES Intel)
set (CMAKE_C_FLAGS_DEBUG "-O0 -g")
set (CMAKE_C_FLAGS_RELEASE "-O2")
set (CMAKE_CXX_FLAGS_DEBUG "-O0 -g")
set (CMAKE_CXX_FLAGS_RELEASE "-O2")
set (CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")
set (FORCE_FRAME_POINTER "-fno-omit-frame-pointer")
# Ensure each library is fully linked
set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--no-undefined")
else (MSVC)
set (CMAKE_C_FLAGS_DEBUG "/MP /Od /Zi /MDd /D_DEBUG")
set (CMAKE_C_FLAGS_RELEASE "/MP /O2 /MD /D NDEBUG")
set (CMAKE_CXX_FLAGS_DEBUG "/MP /Od /Zi /MDd /D_DEBUG")
set (CMAKE_CXX_FLAGS_RELEASE "/MP /O2 /MD /D NDEBUG")
set (CMAKE_C_FLAGS_RELWITHDEBINFO "/MP /O2 /Zi /MD /D NDEBUG")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MP /O2 /Zi /MD /D NDEBUG")
set (FORCE_FRAME_POINTER "/Oy-")
endif()
message(STATUS "Set optimization flags")
