if(CMAKE_COMPILER_IS_GNUCXX)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fvisibility=hidden")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
    message(STATUS "Found g++, enabling -fvisibility=hidden")
endif()
