name: 'CDash Status'
on:
  push:
  pull_request_target:

jobs:
  cdash-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: kitware/cdash-status@51f300cc37b887b89cf658543c0465b65c41b25b
        with:
          project: "TOOLS-SDK"
