name: CMake Formatting

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ master ]
    paths:
       - '**.cmake'
       - '**CMakeLists.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cmake-formatting:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        python3 -m pip install gersemi

    - name: gersemi
      shell: bash
      run: |
        function PrintHeader()
        {
          delim='----------------------------------------'
          printf '\n\n%s\n' "$delim"
          printf '%s\n' "$@"
          printf '%s\n' "$delim"
        }

        # use process substitution to avoid early exit if grep or git fail
        # store the cmake files into cmakeFiles array
        mapfile -t cmakeFiles < <( git ls-files | grep -E '(^|/)CMakeLists\.txt$|\.cmake$' )

        # store stdout and stderr lines of 'gersemi --check' into gersemiCheck array
        # adding a line '@@@rc=<RETURN_CODE>' to get the rc from the gersemi process substitution
        mapfile -t gersemiCheck < <( rc=0; gersemi --check "${cmakeFiles[@]}" 2>&1|| rc=$?; echo "@@@rc=$rc" )
        gersemiRc=${gersemiCheck[-1]#@@@rc=}
        unset "gersemiCheck[-1]"

        reformatFiles=( )
        warnings=( )
        reformats=( )
        for line in "${gersemiCheck[@]}"; do
          case "$line" in
            *' would be reformatted')
              reformats+=( "$line" )
              path=${line% would be reformatted}
              reformatFiles+=( "${path#"$PWD"/}" )
              ;;
            *)
              warnings+=( "$line" )
              ;;
          esac
        done

        PrintHeader "Reformatting required from:  gersemi --check ..."
        if [ ${#reformats[@]} -gt 0 ]; then
            printf '%s\n' "${reformats[@]}"
        fi

        PrintHeader "Warnings from:  gersemi --check ..."
        if [ ${#warnings[@]} -gt 0 ]; then
          printf '%s\n' "${warnings[@]}"
        fi

        if [ "$gersemiRc" != 0 ]; then
          PrintHeader "ERROR: gersemi --check failed with rc=$gersemiRc" \
                      "To fix run the following command:"
          printf '%s\n' "gersemi --in-place ${reformatFiles[*]}"
          PrintHeader "gersemi --diff ${reformatFiles[*]}"
          gersemi --diff "${reformatFiles[@]}"
          exit 1
        fi
