
name: formatting

on:
  pull_request:
    branches: [ master ]

jobs:
  cmake-formatting:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        python3 -m pip install cmake-format
    - name: cmake-format
      run: |
        set +e
        cmake-format -i $(find . -type f | egrep 'CMakeLists.txt|\.cmake$')
        if [ $(git diff | wc -l) -gt 0 ]; then
          echo -e "\nError! CMake code not formatted. Run cmake-format...\n"
          echo -e "\nFiles:\n"
          git diff --name-only
          echo -e "\nFull diff:\n"
          git diff
          exit 1
        fi
        
  source-formatting:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-9
    - name: clang-format
      run: |
        set +e
        clang-format-9 -i $(find . -type f | egrep -v '\./(syscalls|external|dataflowAPI/rose)' | egrep '\.(h|c|C)$')
        if [ $(git diff | wc -l) -gt 0 ]; then
          echo -e "\nError! Source code not formatted. Run clang-format-9...\n"
          echo -e "\nFiles:\n"
          git diff --name-only
          echo -e "\nFull diff:\n"
          git diff
          exit 1
        fi
