name: Purge old workflow runs

on:
  schedule:
    - cron: '0 5 1 * *'  # 5AM on the first of the month
  workflow_dispatch:

jobs:

  purge:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@0cf693bc9909e5e867ee8f27b813224ba862939c # main
        with:
          token: ${{ secrets.github_token }}
          repository: ${{ github.repository }}
          # remove anything older than two months
          retain_days: 60
          # keep at least one run of any workflow
          keep_minimum_runs: 1
