name: Purge unused containers/packages

on:
  workflow_dispatch:
  workflow_call:

jobs:

  get-oses:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.all.outputs.all }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: all
        uses: ./.github/actions/os-versions

  purge:
    runs-on: ubuntu-latest
    needs: get-oses
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.get-oses.outputs.all) }}
    permissions:
      packages: write
    name: Purge ${{ matrix.os }}
    steps:
      - name: Development containers
        uses: actions/delete-package-versions@v5
        with:
          package-name: amd64/${{ matrix.os }}
          package-type: 'container'
          token: ${{ secrets.github_token }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"

      - name: Base containers
        uses: actions/delete-package-versions@v5
        with:
          package-name: amd64/${{ matrix.os }}-base
          package-type: 'container'
          token: ${{ secrets.github_token }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"
