name: Build Container on Release

on:

  # Publish packages on release
  release:
    types: [published] 
 
jobs:
  build:
    permissions:
      packages: write

    # Note this inherits the arguments for dependencies from the base container
    # If you move this release trigger to the base-containers workflow you
    # can tweak this, however the release will take longer.
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Space For Build
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Build Dyninst Release Container
        run: |
           cd docker/
           docker build -f Dockerfile.release -t ghcr.io/dyninst/dyninst-ubuntu-20.04:latest ../

      - name: GHCR Login
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Release Image
        run: |
            tag=${GITHUB_REF#refs/tags/}
            echo "Tagging and releasing ghcr.io/dyninst/dyninst-ubuntu-20.04:${tag}"
            docker tag ghcr.io/dyninst/dyninst-ubuntu-20.04:latest ghcr.io/dyninst/dyninst-ubuntu-20.04:${tag}
            docker push ghcr.io/dyninst/dyninst-ubuntu-20.04:${tag}

      - name: Deploy
        run: docker push ghcr.io/dyninst/dyninst-ubuntu-20.04:latest
