name: Parse sys libs

on:
  schedule:
    - cron: '0 1 * * 1'  # 1AM on Monday
  workflow_dispatch:

jobs:

  get-oses:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.all.outputs.all }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: all
        uses: ./.github/actions/os-versions

  parse-system-libs:
    runs-on: ubuntu-latest
    needs: get-oses
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.get-oses.outputs.all) }}
    permissions:
      packages: read    
    container:
      image: ghcr.io/dyninst/amd64/${{ matrix.os }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    name: System libs ${{ matrix.os }}
    steps:
      - name: Build parser
        shell: bash
        run: |
          set -ex
          git clone --depth=1 https://github.com/dyninst/external-tests
          cd external-tests; mkdir build; cd build
          cmake .. -DDyninst_ROOT=/dyninst/install 
          cmake --build . -t simpleParser
          mv parseAPI/simpleParser /usr/bin

      - name: Run parser
        shell: bash
        run: |
          set -ex
          for d in /dyninst/install/lib*; do
           if [ -n "$LD_LIBRARY_PATH" ]; then
             LD_LIBRARY_PATH="$d:$LD_LIBRARY_PATH"
           else
             LD_LIBRARY_PATH="$d"
           fi
          done
          export LD_LIBRARY_PATH
          export OMP_NUM_THREADS=2

          dirs="/usr/lib /usr/lib64"
          
          # Ignored files:
          #
          #  *.hmac
          #    hash files
          #
          #  libclang*
          #    causes hangs

          find ${dirs} -type f -name '*.so.*' \
             \! -name '*.hmac' \
             \! -name 'libclang*' \
           -print -exec /usr/bin/simpleParser {} \;
